= Equipment

This section gives game mechanics for popular equipment, including gear, armor, and weapons, plus how to purchase them.
Game effects for various weapon types are also included.
Game Masters need to decide what’s suitable for their particular settings.
All equipment described herein is of the basic, non-magical variety.

=== Purchasing Equipment

Each piece of equipment has a price difficulty associated with it that expresses how challenging it is for a character to obtain that item.
If using Funds as an attribute, to purchase an item, the player rolls the attribute against the listed purchase difficulty, adjusted by the Game Master for the circumstances around obtaining the item (such as seller’s stock, item quality, general item availability, and so on). If the Funds total equals or exceeds the price difficulty, the character gets the item.
Business, con, charm, and persuasion could all serve as complementary actions to the Funds roll, depending on the factors the Game Master chooses to include (such as local law, relationship of buyer and seller, and so on). Likewise, Game Masters may allow players’ characters to help each other obtain particularly expensive items (such as spaceships) through complementary Funds rolls.

Any item with a price difficulty equal to or less than the number in front of the “D” in the character’s Funds attribute is an automatic purchase.
A character may make several automatic purchases per day.

Any item with a price difficulty greater than the number in front of the “D” in the character’s Funds attribute but less than or equal to 3 times that number is an average purchase.
A character may make one average purchase per day.

Any item with a price difficulty greater than 3 times the number in front of the “D” in the character’s Funds attribute is a luxury purchase.
A character may make one luxury purchase every seven days.

When deciding on the type of purchase, include in the difficulty breakdowns any modifiers due to an Advantage or Disadvantage.

Example: A character has 3D+2 in her Funds attribute.
Her automatic purchases have a difficulty of 3 or less.
Her average purchases have a difficulty of 4 to 9.
Her luxury purchases have a difficulty of 10 or more.
If the character also had Wealth (R1), she would add her bonus of +10 to each of these levels, giving her automatic purchases at 13 or less, average purchases between 14 and 19, and luxury purchases at 20 or more.

Failure on a Funds roll means that the character didn’t have the money for some reason (maxing out a credit card, forgetting to transfer money to the correct account, leaving the wallet at home, etc.). Except when the total is abysmal, the character may roll again after a short period of time and attempting to fix the problem (switching credit cards, moving money, getting money from the safe, etc.).

Unless the Game Master decides otherwise, players may not spend Character and Fate Points on Funds rolls.

*Price Difficulties*

_Cost of Item or Service Level_

Cheap (several credits or less) Very Easy (VE)

Inexpensive (less than 200 credits) Easy (E)

Nominally expensive (hundreds of credits) Moderate (M)

Somewhat expensive (a few thousand credits) Difficult (D)

Expensive (several thousand credits) Very Difficult (VD)

Very Expensive (tens of thousands of credits) Heroic (H)

Costly* (a few hundred thousand credits) Legendary (L)

*“Costly” is hardly the top end, and Game Masters should continue adding to the difficulty for higher prices.

_Item or Service Is… Minimum Modifier_

Common; average quality 0

Very common; local market is flooded; of slightly lower technological complexity than commonly available -5

In high demand; limited availability; of slightly higher technological complexity than commonly available +5

Not generally available to the public; of significantly higher technological complexity than commonly available +15

Out of season or from a distant location +15 or more

Unusually high quality +5

Damaged or low quality -5

_Relationship with Seller Bargain Modifier_

Has dealt with rarely or never 0

Pays on time; frequent customer; no complaints by seller -1 or more

Rarely pays on time; problem buyer +1 or more

=== Cash and Coins

Game Masters preferring to use cash over dice can generate prices by selecting reasonable monetary values based on the difficulty level given, or by rolling 3D and multiplying the total by an appropriate amount for each level.
For example, to convert to U.S.
dollars, use: $1 for Very Easy, $10 for Easy, $100 for Moderate, $500 for Difficult, $1,000 for Very Difficult, $10,000 for Heroic, and $100,000 for Legendary.

Some Game Masters prefer coins to rolling dice for purchasing goods.
They may make their own system to use in their settings, or take this one: eight copper pieces equals one silver piece; eight silver pieces equals one gold piece.
Though this might not seem like an elegant system, it’s more akin to how the coins would have been minted and split: A round coin can easily be sliced into eight relatively equal parts.

Game Masters may then select reasonable monetary values based on the difficulty level given; the lists include sample numbers followed by C for copper, S for silver, and G for gold.
Or Game Masters can roll 3D and multiplying the total by an appropriate amount for each level.
For example, to convert to the suggested monetary system, use: one copper coin for Very Easy, one silver coin for Easy, one gold for Moderate, 10 gold coins for Difficult, 100 gold coins for Very Difficult, 1,000 gold coins for Heroic, and 10,000 gold coins for Legendary.

=== Breaking Things

Use the demolitions skill guidelines in the “Example Skill Difficulties” section for determining the effect of damage on items.

=== Fantasy Gear

*Candle, Lamp:* Small, lit candle or lamp has damage of 1D per round after the first when held in contact with a flammable surface for more than one round.
A lit candle or lamp negates up to 2D (6) in darkness modifiers within a meter of the user.

*Grappling Hook:* +1D bonus to climbing attempts; must be used with a rope.
The hook can inflict Strength Damage +1 in damage.

*Hammer:* Useful with some crafting attempts.
Can inflict Strength Damage +1.

*Healer’s Pack:* A small kit of soothing herbs and clean cloth strips adds a +1 bonus to three to six healing attempts, depending on how much material is used.

*Lockpicking Tools:* +1D bonus to lockpicking attempts only if the user has the lockpicking skill.

*Marbles:* When stepped on, the victim makes Moderate Agility or acrobatics roll per step (each step counting as an action) he wishes to move until he is out of the area of marbles.

*Makeup Kit:* A single kit contains enough coal dust, flour, red powder, and body oil in small vials for five uses, plus application brushes of various sizes.
Adds 1D to disguise attempts.

*Pick, Mining:* Adds 1D to digging attempts, or does Strength Damage +2 in damage when striking.

*Rope, Heavy (Hemp):* Inflicts Strength Damage +2 when used in choking attacks; damage resistance total 5.
Can hold up to 100 kilograms.

*Rope, Light (Silk):* Inflicts Strength Damage +1 when used in choking attacks; damage resistance total 3.
Can hold up to 140 kilograms.

*Shovel:* Adds 1D to digging attempts, or does Strength Damage +2 in damage with bashing attacks.

*Spikes, Iron:* +1D bonus to climbing attempts when several are used; requires a Physique or lifting of 3D or more to insert them into crevices without a hammer.
Each spike can inflect Strength Damage +1.

*Torch:* A small, lit torch has a damage of 3D per round after the first when held in contact with a flammable surface for more than one round.
A lit torch negates up to 4D (12) in darkness modifiers within several meters of the user.

*Items and Prices*

_Gear_

Basket, woven VE (8 C)

Bell, small metal E (2 G)

Bedroll E (3 SP)

Blanket, flannel single E (2 SP)

Bowl, wooden soup VE (6 C)

Brazier, portable bronze M (5 G)

Bucket, wooden E (4 SP)

Candle, tallow taper; torch VE (1 C)

Chest, small wooden M (3 G)

Cloth, flannel, about 1 square meter VE (8 C)

Compass D (30 G)

Drum, handheld M (15 S)

Fishing hook and line VE (5 C)

Flute E (2 G)

Grappling hook E (8 S)

Hammer E (3 S)

Healer’s pack VE (16 C)

Holy symbol, silver unblessed M (10 G)

Ink in small glass vial M (3 G)

Incense (2 long sticks) E (8 S)

Lamp, pottery VE (8 C)

Lamp oil, medium flask VE (5 C)

Lockpicking tools VD (27 G)

Lute M ( 4 G)

Marbles, hard clay VE (8 C)

Makeup kit (5 uses) E (8 S)

Mirror, silver M (5 G)

Mirror, polished steel or bronze M (3 G)

Parchment, rice paper, or vellum E (8 S)

Pick, mining E (16 S)

Perfumed water in small glass vial E (10 S)

Pouch, large leather E (4 S)

Pouch, small flannel VE (6 C)

Pot, iron cooking E (16 S)

Quill VE (16 C)

Quiver E (8 S)

Room in an inn (average per day per person) M (1 S)

Room in an inn (common room bed) VE (1 C)

Rope, heavy (hemp, 15 meters) E (4 S)

Rope, light (silk, 15 meters) M (15 G)

Sack, rough cloth VE (6 C)

Scabbard E (8 S)

Sealing wax VE (16 C)

Shovel E (8 S)

Spoon or fork, brass dinner (each) VE (3 C)

Spikes, iron E (6 S)

Tent, two-person M (7 G)

Tinder box with flint and steel VE (8 C)

Vial with stopper, ceramic VE (2 C)

Vial with stopper, glass VE (7 C)

Waterskin E (7 S)

Whetstone VE (1 C)

_Fashion_

Type Price

Belt VE (6 C)

Boots E (16 S)

Cloak, flannel E (7 S)

Dress E (5 S)

Hat E (3 S)

Jerkin E (5 S)

Robe E (8 S)

Sandals VE (7 C)

Shoes VE (16 C)

Skirt E (3 S)

Tunic E (5 S)

_Food and Drink_

Ale (mug) VE (2 C)

Bread (loaf) VE (2 C)

Butter (small crock) VE (5 C)

Cheese (wheel) VE (7 C)

Cookies, sweet (a few) VE (4 C)

Eggs (a few) VE (1 C)

Feed (for animals) VE (5 C)

Fruit, fresh or dried (each or handful) VE (2 C)

Grains, flour (a few kilograms) E (8 S)

Gruel (bowl) VE (1 C)

Herbs, fresh or dried (bunch) VE (3 C)

Jam, jelly, preserves (small crock) VE (5 C)

Meat, fresh local pork, mutton, beef, fowl,

or fish (a few kilograms) VE (16 C)

Meat, smoked (a few kilograms) E (16 S)

Milk (a few liters) VE (8 C)

Nuts (handful) VE (8 C)

Pastry (each) VE (8 C)

Rations (day) VE (8 C)

Spices, rare (small pouch) E (8 S)

Stew (bowl) VE (5 C)

Vegetable (a few) VE ( 2 C)

Water (glass) VE (1 C)

Wine (glass) VE (8 C)

Note: All food and drink prices assume the items are commonly available for sale in the location.

=== Adventure Gear

The price difficulties given in the equipment descriptions in this section are suitable for most post-1940s U.S.
settings.
Those not available in pulp fiction settings are marked; modern setting prices are given for them.
Nonetheless, players may use these as inspiration for weird science projects of that era.
Prices do not reflect any modifiers the Game Master may wish to include.

*Binoculars:* +1D bonus to sight-based rolls for viewing objects beyond two meters in the daylight only.

*Crowbar*: +1D bonus to prying attempts, or does Strength Damage +2 in damage with bashing attacks.

*Duct Tape:* In the 1940s, duct tape (then called “duck tape,” because it was made from cotton duck cloth) only came in military green, in modern times, duct tape comes in a variety of colors, strengths, widths, and reflectivity.
It can hold about 90 kilograms (depending on how well it’s secured to something else) and has a damage resistance total of 10.

*Flashlight:* A large flashlights reduces darkness modifiers by 2D in a cone-shaped area up to five meters from the user.
Batteries have a price difficulty of Very Easy for two batteries.

*Gas Mask:* When worn, the gas mask provides a +2D to stamina rolls against gas attacks or negates up to 1D in relevant modifiers.
(Use the game mechanic appropriate for the situation.)

*Handcuffs:* Requires the key or a Moderate lockpicking roll to remove; damage resistance total 15.
Key comes with purchase of handcuffs.

*Jungle Adventurer’s Pack:* Includes a pith helmet, insect repellent, and mosquito netting in a small knapsack.
Provides a +2 to survival checks in the jungle or heavy forest.

*Iron Spikes And Piton:* +1D bonus to climbing attempts; must be used with a rope.
Each spike can inflict Strength Damage +1.

*Lockpicking Tools:* +1D bonus to lockpicking attempts only if the user has the lockpicking skill.

*Marbles*: When stepped on, the victim makes Moderate Reflexes or acrobatics roll per step (each step counting as an action) until he moves out of the area of marbles.

*First-aid Kit:* A small kit adds a +1 bonus to five to 10 medicine attempts, depending on how much material is used.
A larger one costs a few difficulty points more and adds 1D to two to five medicine attempts, again, depending on the contents used.

*Quick-draw Holster:* A favorite among gunslingers, the springloaded quick-draw holster is only available for nonbulky handguns or melee weapons.
With this holster, drawing the weapon does not count as an action, so characters may perform it in the same turn as using the weapon without penalty.
In addition, when the character engages in a “quick-draw” contest, she can add 1D to her initiative.
It does not provide any special initiative bonus during normal combat.

*Rifle Scope:* Attaches to a rifle and allows the user to magnify the target, thus increasing the accuracy at greater ranges.
Adds 2 to marksmanship rolls for attempts at Medium or Long range.
Must spend one round aiming in order to gain benefit.

*Rope, Heavy (Hemp):* Inflicts Strength Damage +2 when used in choking attacks; damage resistance total 5.

*Rope, Light (Cotton):* Inflicts Strength Damage +1 when used in choking attacks; damage resistance total 3.

*Shovel:* +1D bonus to digging attempts, or does Strength Damage +2 in damage with bashing attacks.

*Signal Locator:* This device, which has a restricted distribution, monitors the signals of tracking devices.
It includes a small display to show direction of movement.
Pricier ones can pinpoint the location on a map.

*Telescope:* Adds 2D to vision-based search rolls, though the user must take one round (and getting no preparation bonus) to focus the telescope.

*Tool Kits:* Contains tool (and possibly parts or storage containers) necessary for accomplishing basic related tasks.
Adds 1D to relevant skill attempts only if the user has the appropriate skill (usually repair or tech, but investigation in the case of an evidence or archaeologist’s kit, disguise in the case of a disguise kit, or certain applications of artist or forgery with the artist supplies).

*Torch:* A small, lit fire-torch has damage of 3D per round after the first when held in contact with a flammable surface for more than one round.
A lit torch negates up to 4D (12) in darkness modifiers within several meters of the user.

*Tracking Device:* Used with a signal locator, this miniature transmitter electronically signals the location of whatever it’s attached to over a distance.
Active devices emit a signal, while passive ones wait for a signal to come to it before sending out a response.

*Gear*

_Item (Availability*) Price_

Alarm clock (A) VE

Archaeologist’s tool kit (U) E

Art supplies (C) E

Backpack (A) VE

Basic clothing (A) E

Basic field rations, few days’ worth (A) VE

Binoculars (C) E

Blanket (A) VE

Camera, basic point and shoot (C) E

Film, basic color or B&W (C) VE

Carpenter’s/construction tool kit (A) E

Compass (C) VE

Crowbar (A) VE

Daily newspaper, weekly magazine (A) VE

Disguise kit (C) E

Duct tape, 10 meters (C) VE

Duffel bag (A) VE

Eating utensils (A) VE

Electrician’s tool kit (C) E

Evidence kit (U) M

Field radio (U) E

First-aid kit (C) VE

Fishing gear (A) VE

Flashlight, large (C) VE

Gas mask (U) E

Gas stove (C) E

Geiger counter (U) E

Handcuffs (U) E

Holster (C) VE

Jungle adventurer’s pack (U) E

Iron spikes (8) and piton (A) VE

Kerosene heater (C) VE

Lantern (A) VE

Lighter (A) VE

Lockpicking tools (U) VE

Marbles (A) VE

Mechanic’s tool kit (C) E

Movie camera, small (U) M

Movie camera film or tape (U) VE

Parachute (U) E

Personal hygiene kit (A) VE

PDA (C/N) M

Quick-draw holster (C) E

Radio, portable (A) VE

Rifle scope (C) E

Rope, hemp, 50 meters (A) VE

Rope, cotton, 50 meters (A) VE

Sewing machine, small (A) VE

Shovel (A) VE

Signal locator (U/N) D

Sleeping bag or bedroll (A) E

Steamer trunk (A) VE

Tape recorder (A) E

Tapes for recorder (A) VE

Telescope (C) E

Tent, 1-person (A) VE

Tent, 3-person (A) E

Tracking device (C/N) M

Typewriter (C) E

Torch (A) VE

Watch (A) VE–E

Wood stove (A) E

=== Sci-Fi Gear

The price difficulties given in the equipment descriptions in this section are suitable for most science fiction settings.
They do not take into account any modifiers the Game Master may wish to include.

*Binoculars:* +1D bonus to sight-based rolls for viewing objects beyond seven feet in the daylight and twilight.
Cost: Easy.

*Comlink:* The standard unit of communication equipment, comlinks come in a number of different forms.
The most common is the handset, which has an effective range of 10 kilometers and is widely available on the open market.
These also can be purchased as headsets.
Cost: Easy.

Military comlinks have a greater range (approximately 25 kilometers), and are frequently belt units or built into enviro-suit helmets, to allow the soldier to keep her hands free for combat.
Cost: Moderate.

Many high-tech worlds feature communications satellites that allow comlink signals to reach anywhere on the planet.

*Cred-key:* A small plastic card that, when placed in a cred-key receiver, can perform all banking functions.
Cred-keys are used by virtually all high-tech worlds, though not all worlds have compatible banking systems.
Many frontier worlds do not have the equipment necessary to read the cards and so will only accept hard currency.

Standard cred-keys contain the name of the bearer and a personal identification number.
Megacorporate-issued cred-keys usually feature the name of the firm and a code for it as well.
Military officers, who may have extensive credit limits owing to their status, carry cards with their DNA pattern encoded on them for ease of identification.

Cred-keys are not common on worlds with extensive smuggling, piracy, or other criminal activities — they are too hard to steal and use.
A character must be able to generate a forgery, a personal equipment repair, and a computer interface/repair skill total of at least 21 each to forge or strip a civilian cred-key.
(Military and megacorp keys are harder to do this to.) Even then, decent detection equipment (not usually found in stores and bars, but common in banks and large-purchase retail outlets) will probably be able to detect the forgery.
Cost: Very Easy to set one up; some fees to transfer money.

*Crowbar:* Gives a +1D bonus to prying attempts, or does Strength Damage +2 in damage with bashing attacks.
Cost: Very Easy.

*Enviro-suit:* The basic environmental protection gear, the enviro-suit is designed for use in hostile climates or worlds whose atmosphere is unsafe.
The enviro-suit features a helmet and full body suit (the helmet is detachable). Air is recycled by the mechanisms in the suit and bodily moisture is also filtered, to be stored in pouches inside the suit.
Straws run up the suit and into the helmet to allow the user to take a drink.

Enviro-suits commonly have comlink units built into the helmet and the belt.
A small indicator light in the helmet flashes when in the presence of another comlink trained to the same frequency.
An enviro-suit maintains a constant temperature around its wearer that can be adjusted via controls on the belt.
A standard enviro-suit offers only a single layer of protection (Armor Value +1), which, if torn or pierced, renders the entire suit inoperative.
More expensive suits offer two layers of protection, with a liquid sealant stored between the interior and the exterior.
Damage done to the exterior layer can be sealed within one round (Armor Value +2). However, extensive damage rapidly exhausts the supply of sealant.
(The average outfit comes with enough sealant to repair 20 small tears or 10 large ones.)

Enviro-suits can hold enough air, food, and recycled water for several days to several weeks of use; about two weeks is standard.
They can be refilled off of shipboard supplies (deducting the life support from the ship’s life support) or they can be refilled at stations and similar places for 10% of the base cost of the suit.
Cost of suit: Moderate.

*Flashlight:* Small flashlights reduces darkness modifiers by 2D in a cone-shaped area up to five meters from the user.
The internal batteries can be recharged off any local current (the base includes several adapters). Cost: Very Easy.

*Hand* *Comp*: Portable and easy to use, hand computers feature rapid processing power, including high quantities of high-speed memory and high capacity, multifunctional chip drives.
Most come with a port for connection to a neural jack, as well as cable interfaces for connecting to larger terminals.
Smaller computers have slots for a few scholarchips, while larger ones have room for several.
Cost: Moderate.

*Handcuffs:* Low-tech metal adjustable restraints require the key or a Moderate sleight of hand roll to remove; 18 Body Points/2 Woundlevels; damage resistance total 15.
Key comes with purchase of handcuffs.
Cost: Very Easy.

*Hand* *Scanner:* A portable sensor device, the hand scanner has an effective range of 10 kilometers.
It can be set to pick up motion, particular types of matter, and even indications of power generation.
They are standard equipment for scouts and are frequently used by miners.
Use of a scanner provides a +1D to sensors.
Use the “Information Difficulties” or “Observation Difficulties” charts in the “Example Skill Difficulties” chapter to determine what the scanner reveals.
Most hand scanners can only be blocked by cover over three solid meters thick (several thick concrete walls or the bulkhead of a ship will usually block scanner readings, but only the most dense of forests or jungles will have any effect at all). Cost: Moderate.

*Holo-vid* *Player:* This device provides holographic images drawn from data chips for entertainment or informational purposes.
Holo-vids can also be connected to comlinks to provide for audio and visual contact between parties.
Some holo-vids have the capability to jack into hand computers, projecting the information on scholarchips out for all to read.
Cost: Moderate.

*Life-Support* *Refills:* These are “tanks” of atmosphere and food supplies that can be attached to an environment suit and some portable shelters.
They last roughly two weeks and weigh less than 10 kilograms.
Cost: Moderate.

*Lockpicking* *Tools:* +1D bonus to lockpicking attempts only if the user has the sleight of hand skill.
Cost: Easy.

*Med-kit:* An assortment of medical supplies collected into a light-weight container that allows for easy transport.
Med-kits normally contain antibiotic patches, a compressed-air hypodermic injector, three doses of pain killers, bandages, and tape.
Use of a standard med-kit provides a +1D bonus to medicine skill checks.
Cost: Easy.

*Rope,* *Heavy* *(braided* *plastic):* Inflicts Strength Damage +2 when used in choking attacks; 10 Body Points/1 Wound level; damage resistance total 5.
Cost: Very Easy.

*Rope,* *Light* *(braided* *nylon):* Inflicts Strength Damage +1 when used in choking attacks; 6 Body Points/1 Wound level; damage resistance total 3.
Cost: Very Easy.

*Scholarchips:* Computer chips intended for use with both hand units and larger terminals.
These contain available information on sectors, planets, some alien species, equipment, ships, personal data, business transactions, and so on.
Use of a computer with a standard scholarchip in place allows the operator to roll as if he possessed a scholar or appropriate Knowledge-based skill in the subject detailed on the chip.
Of course, the broader the range of information, and the more encrypted it is, the harder it is to get at what the character needs.
Cost: Very Easy for base die code of 1D, +1 to the price for each additional +1D.

*Shovel:* Add 1D to digging attempts, or does Strength Damage +2 in damage with bashing attacks.
Cost: Very Easy.

*Signal* *Locator*: This device, which has a restricted distribution, monitors the signals of tracking devices.
It includes a small display to show direction of movement.
Pricier ones can pinpoint the location on an electronic map.
Cost: Moderate.

*Thermo-disk:* Useful gear when traveling in a wilderness area, thermo-disks are spheroid plasticene items, roughly the size of the average Human’s fist.
They contain storage batteries that, when switched on, give off heat in a 25-meter radius.
As they do not provide light, they can be used in hostile areas without betraying of one’s presence.
Cost: Easy.

*Tool* *Kit:* Contains tools (and possibly parts or storage containers) necessary to accomplish basic related tasks.
Add 1D to relevant skill attempts only if the user has the appropriate skill (usually some version of repair, but investigation in the case of an evidence or archaeologist’s kit, con: disguise in the case of a disguise kit, or certain applications of artist or forgery with artistic supplies). Cost: Very Easy to Moderate.

*Tracking* *Device:* Used with a signal locator, this miniature transmitter allows whatever is attached to it to be electronically located over a distance.
Active devices emit a signal, while passive ones wait for a signal to come to it before sending out a response.
Cost: Moderate.

== Mystical Items

Mystical items are standard pieces of equipment or weapons that have been enhanced through supernatural means.
The Game Master may either give them whatever sort of game characteristics she desires, or she may use Special Abilities to represent what they can do.
Any item that doesn’t somehow stay permanently connected to a character should have the Limitation Burn-out (R1), can be lost or stolen.

=== Magical Artifacts

Forged by an ancient race, created by supernatural beings, or discarded from another dimension, magical artifacts take many forms.
Some are completely beneficial, while others have a secret or obvious curse.

*Amulet Of Protection:* An oddly shaped pendant on a thick leather cord envelopes the wearer in a defensive aura (Attack Resistance: Nonenchanted Weapons (R1), +1D to damage resistance total, with Limitation: Burn-out (R1), can be lost or stolen).

*Enchanted Dagger:* The weapon gives the user a greater chance of harming magical creatures (Natural Hand-to-Hand Weapon: Dagger (R1), +1D damage, with Magically Empowered (R2) and Burn-out (R1), can be lost or stolen).

*Ring Of Power:* With this ring, the user can cast low-level magical spells (Increased Attribute: Magic (R3), +1D; Skill Bonus: Magic Skills (R1), +1 to alteration, apportation, and conjuration totals; both with Burn-out (R1), can be lost or stolen)

=== Holy Items

Holy items are handheld objects representing a person’s faith.
Some are material worked into a symbol of the faith, such as crosses, stars, figures, and writing characters.
Others show the significance of the material itself, such as water or an herb, or an action, such as prayer beads.
The higher the level of the spiritual leader (such as a priest, rabbi, or other cleric), the greater the benefit the symbol imparts.
Additionally, the faith of the user and the target can influence the effect.

*Warding Holy Symbol:* Shaped from metal or wood in a sacred representation, this item helps the user turn away undead creatures (Skill Bonus: Intimidation (R1), +3 to intimidation totals, with Ability Loss (R1), only works on undead beings; Burn-out (R1), can be lost or stolen)

*Blessed Water Or Herbs:* Sprinkled on the opponent, this causes harm only to those with evil in their hearts (Natural Magick: Harm to Evil, effect: 5D magical physical damage, range: 10 meters, duration: 2.5 seconds, cast time: 1.5 seconds, Component: blessed water or herbs, Other Condition: Against Evil Only, rank cost 10, with Burnout (R5), one-time use).

=== Robots

Robots are nonsentient automatons with a programmed algorithm they must follow.
They can be used for maintenance, security — just about anything.
Interaction skills have no effect on them.
Movement may be provided by legs, wheels, treads, hoverjets, or something similar and appropriate for the medium the robot most likely travels through or on.
A robot is preprogrammed for each task it can do; its skills represent this programming.
Furthermore, most robots don’t have dice in attributes, though highly sophisticated ones might.

Most robots can only attempt action they have skills for.
Any action that requires a skill the mechanical construct does not have cannot be done.
Robots with any of the attributes can adapt to circumstances covered by that attribute and make limited decisions not necessarily dealt with by their programming (that is, their listed skills). For robots that can do this, skill attempts that default to the attribute are at +7.
This accounts for the robot being smart but not terribly creative.

Example: A character and a robot (with no attributes) are challenged with repairing a damaged laser pistol.
If neither has the firearms repair skill, the character gets to attempt to roll her Technical with +5 to the difficulty of the task.
The simply programmed robot would not be able to repair the damaged weapon at all, because it doesn’t know how.

A robot can never perform con, willpower, or Metaphysics or other Extranormal attribute actions.
Robots use their dodge or search to determine initiative; if they have neither, they go last.

*Maintenance Robot*

This little robot comes packed with a variety of tools and diagnostic equipment to perform maintenance on just about anything.
Its locking wheels allow it scoot across most relatively flat surfaces, though it can’t increase its rate beyond its base.

Skills: exoskeleton repair 3D, firearms repair 3D, flight systems repair 3D, gunnery repair 3D, personal equipment repair 3D, robot interface/repair: damage only 3D, vehicle repair 3D.
Move: 8.
Size: 2 meters.
Equipment: Various repair and diagnostic tools, plus parts; laser welder (damage 4D if improperly used). Cost: Very Difficult.

*Robotic Servitor*

Generally humanoid in appearance, robotic servitors perform a variety of tasks around the house.
Though they come with a general program for tidiness, the owner should make certain to define any limits immediately, or she could find herself with a domicile that’s too clean.

Skills: artist: cooking 4D, cultures 3D, know-how: housecleaning 7D, languages 3D, scholar 2D.
Move: 10.
Size: 1.2 meters.
Equipment: cleaning supplies and tools stored in various compartments built into body.
Cost: Very Difficult.

*Security Robot*

The most basic and popular security robots can identify a preprogrammed list of visitors; anyone not on that list is turned away.
Those who refuse receive a stunning blast.
Some crime lords alter the basic model with deadly force.

Skills: firearms 5D, dodge 6D, intimidation 5D, running 4D.
Move: 11.
Size: 1.7 meters.
Equipment: stun gun in arm (damage 6D stun only). Cost: Heroic

== Protective Gear

=== Combining Protective Gear

A character cannot wear two suits of the same type, though he could combine some types.
The listing below tells what armor may be worn with what other armor and the kind of bonus it can provide.
Of course, layering armor assumes that the two pieces fit together — a character couldn’t wear two helmets, even if they were made of different materials.
For protective gear not listed here, use the type in this chart that the armor in question most closely resembles to determine what it can be combined with.

Each additional layer of armor increases Reflexes-based difficulties by +4 or more, depending on the joint flexibility of the pieces.
Except armor providing less than a full die of protection, any allowed combination offers the character the complete armor bonus for both layers, up to any maximums dictated by the game.

*Hides and Fur, Bone and Hide:* May be worn over any other type of armor.
May not be worn under anything.
Adds a maximum of 1 to the Armor Value of the total combination.

*Soft Leather, Canvas, Heavy Khaki, Heavy Fabric, Quilted Silk, Syntheleather:* May be worn over or under any other type of armor.
Adds a maximum of 1 to the Armor Value of the total combination.

*Padded Fabric, Woven Metal Fabric, Padded Leather, Hard Leather, Flying Jacking, Syntheleather Mesh:* May be worn under any type of armor or over soft leather, canvas, heavy khaki, chain mail, padded, or metal fabric (though two armors of the same type may not be combined).

*Chain* *Mail:* May be worn over or under any other type of armor.

*Reflec:* A reflective material layered on a thin plastic base, this may be worn over any other armor or over or under clothes.

*Plastovar:* May be worn under soft leather, canvas, heavy khaki, syntheleather, or syntheleather mesh, or over padded, syntheleather mesh, or woven metal fabric.

*Plasteel:* May be worn over soft leather, canvas, heavy khaki, padded, or syntheleather, or under syntheleather mesh or woven metal fabric.

*Plate Mail, Bulletproof Vest, Flak Jacket, Light Kevlar, Heavy Kevlar, Ceramic Armor:* May not be worn under anything.
May be worn over soft leather, canvas, heavy khaki, metallic woven fabric, or chain mail.

*Plate Mail, Bronze:* May be worn under soft leather, heavy fabric, or quilted silk.
May be worn over soft leather, heavy fabric, padded leather, quilted silk, or chain mail.

*Shields:* May be combined with any armor, but only offer protection if held between the attacker and the user.
May not be combined with other shields unless stacked in a stationary position.

=== Encumbrance Option

Wearing a lot of protective gear can make performing certain actions challenging.
For every full die in the Armor Value, the character gets a +1 to all Reflexes-based difficulties.

=== Minimal Armor Option

Many adventurers like to show off their well-endowed (muscled or otherwise) or heavily tattooed bodies.
Against humanoids with an Intellect of less than 4D, the character wearing fanciful armor receives a +1D bonus to all charm or intimidation rolls for the first round of each scene (as appropriate for the character’s physical presence). However, humanoids with Intellects of 4D or more see through the ruse, and the character receives no bonus.

Furthermore, the Game Master should ignore the Armor Value when determining the effects of called shots to unarmored portions of the body.

=== Maximum Damage Resistance Total Option

Some characters carry around their own protection, so it doesn’t make much sense to add more to it.
The maximum damage resistance roll a character can have before adding any negative modifiers, Character Points, or Fate Points but including Physique, protective gear and abilities, and other modifiers is 6D.
Ignore any Armor Value above this.
Game Masters may adjust this depending on how effective they want protective gear to be.

== Weapons

All weapons described in this section were designed with Humans in mind.
Characters more than twice or less than half the size of Humans do not receive their scale modifier when attempting to employ Human-sized weapons.
Additionally, for missile weapons, very large and very small humanoids may incur at least a +5 modifier to the combat difficulty or even find it impossible to use the tiny objects.

For simplicity, Game Masters may have the weapons of larger or smaller humanoids deal the same amount of damage as their Human-sized counterparts, making certain to include the scale modifier to account for increased or decreased damage.
Human-sized characters relying on weapons designed for someone larger or smaller than themselves use the scale modifier of the creature for which the item is designed — they do not use their own scale modifier when attacking.
(They do use their own scale modifier when they defend.)

=== Terminology

*Damage:* Damage is the amount of harm a weapon does per single shot (other settings, such as burst, modify this). Melee, thrown, and those missile weapons relying a person’s strength to determine their power are enhanced by the character’s Strength Damage (see page 60 on determine the die code). Weapons affected by strength have a “+” in front of their damage die code.
Note that the damage is based on the rate of fire; most weapons have a rate of fire of once per round.
See the “Combat Options” section for guidelines on other rates of fire.

*Range:* This factor takes into account that the weapon is less effective the farther it is from the target.
The values given are the maximums, in meters, for Short, Medium, and Long ranges.

For generated values, roll the character’s Physique or lifting.
The modifier after “PHYS” indicates the number to take from or add onto the total.
These totals, in meters, determines the ranges the character can throw the item.
If the total becomes zero or less because of the modifier, then the character cannot throw the item to that range.
(Game Master who prefer straight values should multiply the die code in Physique or lifting by 4, then add the pips to get the “PHYS” value.)

*Ammunition:* The number of bullets or projectiles that the weapon holds.
This is only included in firearms entries.

=== Special Weapons

Certain supernatural beings have an Achilles’ Heel Disadvantage relating to some types of metal, particularly silver or iron.
Any sharp-edged weapon or bullet can be made of or coated in (as appropriate for the substance and the weapon) these substances, and they do additional damage as described by the creature’s Disadvantage or description.

=== Firearms

There are a lot of weapons listed here.
Why would you not simply select the weapon with the highest damage score? In addition to the social ramifications, a weapon’s range, its ammo use and capacity, and its various “fire options” are all things an adventurer needs to consider.
The following explanations should help.

*Handguns*

Handguns are small and comparatively light, and usually easily concealable.
In most game settings, most handguns are readily available and not illegal.
In fact, in most modern game settings, they are the weapon of choice for most adventurers — carrying a .45 automatic or a .38 Special is a lot less conspicuous than a submachine gun or an assault rifle.
These weapons are for close-up work.
Even though most handgun rounds travel a good distance with a highimpact velocity, they generally have a fairly short effective range.

Most handguns are good for close-up work because they are easy to aim and quick to fire.
A target at close range gets less time to react.
Of course, there are a wide variety of handguns — from the tiny .22 one-shot Derringer to the large .357 Magnum.

Most handguns hold between six and 15 rounds.
Handguns may always fire once per round, and twice if they are semi-automatic and the user shoots at the same target (with the single fire as multi combat option). Handguns cannot fire full auto — a handgun that can do that is classified as a submachine gun in these rules.

*Rifles*

Single-shot rifles, such as most hunting rifles or the lever action .30-30, are also very common, and not overly regulated in most game settings.
True, they attract considerable attention in cities, but most small towns in modern game settings don’t have a problem with them and they are perfectly acceptable in the wilderness.

Rifles tend to have longer effective ranges than any other weapon (barring the machine gun), and they have slightly better damage die codes than handguns, mainly because (in general) they maintain better velocities over distance and are capable of firing larger rounds.

While some rifles only hold single bullets, typical rifles hold six, nine, or even 15 rounds.
Usually, higher damage score rifles have fewer rounds, since the bullets are larger.

As with handguns, rifles may fire once per round or twice if they are semi-automatic (using the single fire as multi combat option). They cannot fire on full auto, since that is the province of assault rifles.

*Shotguns*

Like rifles, shotguns are considered “civilian” weapons and are not usually overly regulated.
They attract a lot of attention in highly populated areas, but only if they are out in the open.

The range on a shotgun is less than that of a rifle, but shotguns are slightly better “up-close” weapons.
They usually shoot a spray of pellets, rather than a single round.
So, they are more accurate at shorter ranges and they do quite a bit of damage as well.
However, because the spray of pellets scatters quickly, they do not have the range of regular rifles.

There are many single-shot and pump-action shotguns available.
The “double-barrel” shotgun can gain the single fire as multi bonus by firing both barrels at once.

*Submachine Guns*

These firearms fall into the “military/criminal” area.
Submachine guns are illegal in most populated areas, and they attract attention anywhere.
They are very effective weapons for adventurers, but can often cause more trouble than they are worth.

While most submachine guns hold around 20 or 30 rounds, their rate of fire is so high that they unload themselves quickly.
A burst fires about one-fifth of the weapon’s magazine, while a full auto shot discharges the whole clip.
Even so, a full auto shot usually settles most differences between parties quite quickly.

Submachine guns may fire at up to three targets per round.

*Assault Rifles*

Seldom available in many populated areas, they are heavily regulated and usually only brandished by military organizations.
They are marginally more acceptable than submachine guns (since they are less concealable), but they cause the same types of problems.
Their ammunition is usually expensive and harder to get than normal rifle ammo.

These weapons are like a mix between submachine guns and rifles.
They are larger and heavier than either type of weapon, making them bulky to carry, but also more accurate than submachine guns over longer ranges.
Characters may fire them in bursts of three to five rounds (burst fire as single), single-shot, full auto, or single fire as multi.
They may fire at up to three targets per round.

*Machine Guns*

These are truly “military only” weapons.
A character with a machine gun had better keep it under wraps everywhere except the wilderness.
It causes trouble and attention.
Machine guns are usually hard to get, expensive, and their ammunition is not readily available.

These are heavy weapons usually fired from a vehicle mount or a bior tripod.
A single character seldom can fire the weapon while holding it.
As a result, reverse the range difficulties when using a machine gun (so that Point Blank is +10, Short is +5, Medium is 0, and Long is -5), since they are hard to swing around in a tight arc to “bring to bear” on a close, dodging target.
They may fire at up to three targets per round.

Machine guns are almost always belt or drum-fed, meaning they can hold hundreds of rounds.
However, many machine guns have cyclic rates of over 500 rounds per minute.
They seldom fire on anything but full auto, unless they are loaded with only one round (because of their long range and high damage die codes, they are often used by snipers).

*Energy Weapons*

Like machine guns, energy weapons and their power supplies are difficult to come by and quite expensive.
Some settings may consider them experimental at best, while others reserve them for the military and secret government agency offshoots.
In most science-fiction settings, energy weapons are easier to come by than their slug-throwing counterparts.
(Of course, actual availability is up to the Game Master.) They also generally have the benefit of a light, disposable or rechargeable clip, versus the slug thrower’s need for large amounts of individual projectiles.

Their ranges are comparable to their solid projectile counterparts, sometimes longer, sometimes shorter depending on the design.
Those relying on integrated power packs offer three or more times as many shots than a similar non-energy weapon.
Handguns and rifles may fire single shot or single fire as multi unless otherwise noted in their description.

*Types of Energy Weapons*

Blaster pistols and rifles strip particles from their barrels and hyperaccelerate them toward their target.
Their distinctive reports come from the sonic boom of the particles, and the results are messy.
The barrel must be replaced about once for every five power pack replacements.
Personal blasters may only fire once per round (having a longer than normal recharging time).

Accelerated and focused photons form the firepower of the large class of weapons known as lasers, which cause damage through the application of intense heat.

Plasma rifles and pistols fire a bust of super-heated gas.
The clip contains the gas and a disposable battery to charge the electromagnetic pulse of the weapon.
These weapons may fire single shot, single fire as multi, or full auto.

*Miscellaneous Firearms*

Some science fiction settings also offer a few other unusual pieces of ranged weaponry.
Generally, most places consider these to be illegal or, at minimum, deserving of extreme regulation.

Gyrojet rifles and pistols fire miniature rockets with explosive warheads.
The propellant is in the tiny rocket itself, which gives them a long range and high damage from impact and explosion.

Needler rifles and pistols use electromagnetism to fire tiny steel darts at hypersonic speeds.
They do not do as much damage as some other weapons, but have huge ammunition capacities.
These weapons may also fire single shot, single fire as multi, or full auto.

*Multiple Targets*

Users of weapons that may fire at multiple targets in a round do not gain the damage bonus related to the weapon setting when firing at multiple targets.

=== Firearm Accessories

Here is a sampling of firearm accessories that can make certain weapons more effective.

*Gyrostabilization:* This can be built into any personal or heavy weapon (except hand grenades) and provides synchronized stabilization for the wielder.
The unit supplies that small amount of extra bracing that often makes the difference between a hit and a miss (+1D to hit at any range). This gyrostabilization bonus is not used if the character aims first; aiming provides better stabilization than the gyro can.
Cost: 10% of base weapon cost or +1 to the price difficulty.

*Laser* *Sight:* This can be mounted on almost any projectile- or energy-firing weapon (hand grenades are out). The laser sight projects a small, coherent spot of light that can be seen by the weapon’s user, though after 100 meters, the character using the weapon must be equipped with binoculars or other visual aids (like the telescopic sight). The spot helps the character firing the weapon to see where the round is going to go (+1D to firearms roll).

There are only two disadvantages to the laser sight: (1) certain gases can refract the beam and (2) if the character uses the sight to aim, the target may see the little laser-light as well and be alerted.
(Someone who suspects she’s being targeted may make a search attempt with a +1D bonus to the roll to spot the location of the hidden attacker during the round in which the aim takes place.
The difficulty is the attacker’s attempt to hide.) When using this sight to fire at anything other than Point-Blank or Short range, the character must take an action to aim or forfeit the bonus of the laser sight.
(The character gets the aiming bonus.) It is simply too hard to see the “dot” at Medium or Long range with a “quick shot.” Cost: Easy.

*Quick-Draw* *Holster:* A favorite among gunslingers, the spring-loaded quick-draw holster is only available for nonbulky pistol weapons or melee weapons.
With this holster, drawing the weapon does not count as an action, so characters may perform it in the same turn as using the weapon without penalty.
In addition, when the character engages in a “quick-draw” contest, she can add 1D to her initiative.
It does not provide any special initiative bonus during normal combat.
Cost: Easy.

*Telescopic* *Sight:* Only an advantage at Medium or Long range, the standard telescopic sight is equipped to make seeing the weapon’s target at those ranges much easier (+2 to hit at Medium and Long ranges). Individual scopes are fitted to different weapons — so a weapon with a long range of 250 meters would have a different sight than a weapon with a 1,000-meter range.
The scope can be adjusted slightly, but the maximum range is always just a little more than the weapon’s maximum effective range.
When using this sight on a weapon, the character must aim to get the bonus (though the character also gets the aiming bonus as well). Cost: Easy.

*UV* *Sight* *and* *Scope:* Much more expensive, this “SNS” combination is also much more deadly than the laser sight.
The character using the weapon has a UV scope mounted on the weapon (or, less likely, is wearing ultraviolet goggles) and can see the UV laser dot (+1D to firearms roll). No one else can (unless they, also, are so equipped). The UV scope can also be used to track the dot at long distances.
This sighting combination only affects shots taken at Medium or Long range, and only if the character takes the time to aim the weapon.
The character gets the aiming bonus as well.
Cost: Moderate.

*Special Ammunition*

Slug thrower ammunition comes in a few varieties using metallic cases.
The cases can be reused by reloading them with the slug, powder, and primer.
In addition to standard bullets, there are two other types.

Flechette rounds are small, tightly packed slivers of metal designed to damage armor, including dermal plate.
When using flechette rounds, add 2 to the damage of the weapon.

AP bullets are used to pierce armor.
When a character is using AP rounds against a target wearing armor with an armor value of +2 or more, increase the damage of the AP round by +4.
If the character is not wearing the minimum armor requirement, then subtract 2 from the damage of the round.

*Reloading*

Reloading a case requires the firearms repair skill, and it cannot be done untrained (at least one additional pip in the skill). With proper equipment, a character can reload about 50 rounds every hour.
When a character attempts to reload a bullet, he generates one total per clip (Character Points may be spent). The standard difficulty number is 13.

Reloading has both benefits and drawbacks.
It is possible, by adding an extra measure of propellant or two, to improve damage value or accuracy of a bullet.
Bonuses to accuracy are added to the firearms skill total when in combat.
The process can also increase the likelihood of misfires.

When generating the total, consult the following chart to determine the effects, which relate to all bullets reloaded in the same clip.

*Reloading Success Chart*

_Skill Roll > Difficulty; Bonus; Drawback_

0–4; None; Misfire on 1, 2, or 3 on the Wild Die

5–10; +2 accuracy OR +2 damage; Misfire on 1 or 2 on the Wild Die

11–15; +1D accuracy OR +1D damage; Misfire on Critical Failure

16+; +1D+1 accuracy OR +1D+1 damage; None

=== Gunpowder Weapons

Not every fantasy setting includes the invention of gunpowder, but for those that have, here are a few weapons using that propellant.
The guns rely on marksmanship for their accuracy, while the black powder bomb needs throwing to loft it to a new location.

Note that both muskets are quite heavy, requiring a wooden rest to allow proper aiming.
Anyone not using a rest must take a multi-action, using one action to lift the gun (Physique or lifting difficulty of 3) and one to fire the weapon.

*Arquebus:* Also known as the matchlock musket, the arquebus is a simple weapon with a wooden stock and heavy iron barrel.
It varies in length from 1.2 to 1.8 meters or more and weighs nine kilograms.

The weapon is a simple muzzle-loader; in other words, the firer must load powder charge, wadding, and shot down the barrel, then tamp it down using a ramrod.
Once the weapon is loaded, the firer ignites the powder with a device called a matchlock.
This holds a burning match — often a slow-burning piece of thin cord — at the upper end, and a lever or trigger at the lower end.
By pulling the lever or trigger, the firer swings the match smoothly on to the touchhole, igniting the powder.
Musket: damage 3D+2; range 10/20/40; price D (10 G). Charge, wadding, and shot: VE (2 S) per bullet packet.

*Wheellock Musket and Pistol:* The wheellock involves iron pyrites scraping against a wheel that turns when the trigger is pulled, igniting a spark that sets off the primer.
The musket is about 1.2 to 1.8 meters in length, and 10 kilograms in weight, while the pistol is 15 centimeters and a little more than 3.5 kilograms in weight.
Wheellock pistols are commonly carried in a brace of two, alongside the sword, and are of great use against armored foes.
Like the matchlock musket, the wheellock musket requires a stand to aim correctly.
The pistol and the musket each require 12 rounds to reload with no roll or a marksmanship roll of 10 to reload in one round.
Musket: damage 4D; range 10/25/60; price D (12 G). Pistol: damage 3D+1; range 5/10/25; price D (8 G). Charge, wadding, and shot: VE (2 S) per bullet packet.

*Black Powder Bomb:* This bomb consist of melon-sized pottery ball filled with black powder.
A fuse protrudes from the ball, and when the fuse burns down, the ball explodes, usually with a big enough boom to knock down most monsters.
_Bomb:_ damage 6D; range: Physique -2/Physique -1/Physique; price M (6 G).

=== Explosives

Explosives, the most well known of which are grenades, are one-use weapons that bear the same stigma as the machine gun, but they are easier to conceal.
However, using or brandishing a grenade or explosive always attracts unwanted attention.

Using an explosive can get tricky.
Even though a thrown grenade uses the throwing skill to hit, the character using the grenade should not actually aim at a person but, rather, a place.
Grenades do not, typically, explode on contact — they explode after their fuse (usually three seconds) burns up and they damage anything in a given area.
When throwing at a specific area, refer to the “Grenade Targeting” chart.
If the grenade misses, the Game Master determines where it lands.

Ranges for explosives and grenades represent how far a character can throw them, which is based on the Physique or lifting of the character modified by an additional value.
As with other weapons, accuracy decreases as the distance to the target location increases.

Explosives also have an additional game mechanic: the burst radius.
Anyone caught within the burst radius must take damage; the farther a character is from the center of the blast, the less damage she takes.
Three values, in meters, are given for each burst radius.
Compare the attack roll to target the explosive against the defense total of characters not at ground zero; those who have a defense total greater than the targeting roll managed to dive for cover or protect themselves from the burst.
Characters between zero and the first value take full damage.
Those between the first and second values take half damage.
Anyone between the second and third values take quarter damage.
(Round all fractions up.) Characters farther away than the third value are relatively safe.

Characters who haven’t taken their turn yet have a chance of getting out of the way of the blast.
(Here’s another instance of being able to move up a turn.) Technically, normal movement might do it, but this is a combat situation — the grenade thrower is timing his throw to catch a target in the blast radius.

The target has to beat a difficulty to get out of the blast radius of an explosive.
The character makes a dodge or Reflexes attempt, with the result determining how far from ground zero the character managed to get.

A character who meets the difficulty exactly moves one blast radius zone away from where the explosive landed or was set off.
For every four points above the difficulty, the character moves one more blast radius zone away.
So, a character at ground zero (and thus in zone 1) of a grenade explosion needs to beat a difficulty of 23 to get completely out of the range, while a character in zone 3 requires only a 15.
Once the character’s final zone is determine, figure out how much damage he gets.

*Types of Explosives*

Concussion grenades create a powerful shock wave when they explode, designed to stun targets.

Dynamite is commonly used in mining, road construction, and other places where relatively cheap, quick destruction is needed.
A blasting cap, fuse, or timing device is needed to set off this nitroglycerin-based explosive.
Dynamite comes in sticks.

When fragmentation grenades explode, they send shrapnel out in all directions.

Plastic explosives can be formed like putty.
The explosive is inert until an electrical current runs through it (which means that an electrical blasting cap is needed to set it off). Plastic explosives are small (and easily transportable), and can be used to open an otherwise reluctant door (such as to a safe). About two ounces generates the damage for plastic explosives.

Tear gas and smoke grenades do not explode.
Instead, they release their contents through holes in a canister.
The cloud they create quickly fills an area of 9.5 square meters.
Armor provides no protection against this kind of attack, though a gas mask does.
Both tear gas and smoke grenades give all within the blast area a -1D penalty to all Reflexes, Coordination, and sight-based Perception rolls.

White phosphorus grenades create intense heat when they explode.
Not only do they do a base damage, they also ignite all flammable material in the area of effect, doing an additional 4D in damage each round it continues to burn (which can last several rounds).

*Explosive Burst Radius*

_Distance from Explosive* Zone 1; Zone 2; Zone 3_

81mm mortar, fragmentation grenade 0–3; 3–8; 8–16

Dynamite 0–2; 2–5; 5–10

Grenade (any except smoke/tear) 0–3; 3–8; 8–16

Plastic explosive 0–3; –; –

Smoke grenade, tear gas ‡

*All values given in meters.
‡Smoke grenades and tear gas have a burst radius of 9.5 square meters.

*Grenade Targeting*

_Range Difficulty_

Point Blank 0

Short 10

Medium 15

Long 20

_Condition Modifier_

Character cannot directly see target area +6

Target area is not “even ground” +4

Target area is very hard (grenade will bounce) +4

Target area is very soft (grenade will sink) -4

== Muscle-Powered Weapons

Muscle-powered weapons include all those that depend upon a character’s strength to get them to their target.
Instead of having their damage die codes listed as a single number, muscle-powered weapons have damage adds.

=== Missile and Thrown Weapons

One benefit of missile and thrown weapons is their quiet operation and fewer government regulations on ownership.
All such weapons take an action to reload, either to notch another arrow or pull out another dart.
Generally, characters may reload in the same round as firing or throwing (with a multi-action penalty), except with crossbows, which require the character to replace the bolt and crank it in place.

=== Melee Weapons

Most muscle-powered weapons are melee weapons.
Swords, knives, brass knuckles, clubs, and so on are all examples.
All of these weapons require melee weapons to use.
Game Masters may allow characters to employ untrained such simple ones as sticks with only the Reflexes attribute.
Edged or pointed weapons do half damage when used to bludgeon instead of cut.

=== Whips

A whip is a long, plaited strip attached to a handle.
When a character uses it to strike a target, determine the success with the melee combat skill.

A whip can also be used to entangle an opponent up to two meters away.
The character uses throwing to make this kind of attack.
If it’s successful, the whip wraps about the target.
If it’s unsuccessful, the target takes full damage.

It can also be used to disarm opponents (as a throwing called shot) or to swing over pits or other openings.
To swing with the whip, the character makes a Difficult throwing roll to catch the whip around a projection overhead that can support her weight.
(The Game Master may include modifiers depending on the conditions.)

=== Improvised Weapons

When a character’s up against something ugly and angry, and his favorite gun’s back at his hideout, he grabs whatever he can to get the job done.

That means that Game Masters aren’t always going to find established game mechanics for what their players want to use as weapons.
When this happens, the best way to handle the situation is use the mechanics of something similar.
Most items either serve as a dagger (such as a broken bottle) or a club (such as a table leg). Then modify the damage based on how sharp or heavy the improvised weapon is to the comparison weapon.

Improvised weapons always use either melee combat or throwing, and they always receive an improvised weapon modifier to the combat difficulty of +5 or more.
On a card-played setback or a rolled Critical Failure when wielding the item, most improvised weapons break, the user hurts himself, or both — the greater the roll fails, the worse the situation is.
(If the user ends up hurting himself, use only the weapon bonus — do not include the user’s Strength Damage — to determine the amount of damage done.)

Generally, characters may rely on improvised weapons only a few times before they break (regardless of whether a Critical Failure or a setback occurred while using it), though ones designed to take abuse — such a heavy metal pipe, fire iron, or a screwdriver — can survive the battle (including Critical Failures) and continue to function as tools or armament.

== Vehicles

There are a number of conveyances commonly found on planets and moons.
With land vehicles, the prices are for wheeled versions.
Should hovercraft versions exist, up the price by one level and the Maneuverability by +1D.
Hovercraft have the benefit of being able to handle a wider variety of terrain, including shallow pools of water, with ease, at the cost of a higher initial price and greater maintenance difficulty (+3 to all vehicle repair difficulties). Both wheeled and hovercraft have the same move; the difference is in how well they can travel over different terrain.

The accompanying chart introduces a few terms unique to means of conveyance:

*Scale Value:* For Game Masters using the scale option, this number indicates how much larger the vehicle is than a Human, relative to a Human’s scale value of zero.

*Move:* This is approximately cruising speed.

*Passengers:* The number of people, including the crew, that the vehicle can carry.
Unless otherwise specified, the number of crew needed to properly operate the vehicle is one.

*Toughness:* This is the vehicle’s base damage resistance die code.
It can also serve as a reasonable measure of the amount of damage it can inflect.
Players may not modify a vehicle’s Toughness by spending Character or Fate Points on it.

*Maneuverability:* An indication of how easy the vehicle is to handle.
Stunts are easier to perform in vehicles with higher die codes than in those with lower ones.
The Maneuverability die code is added to the driver’s or pilot’s appropriate skill total when that person is attempting to do something fancy.
(Vehicle stunts are further explained in the “Movement” section.)

=== Vehicle Weapons

Occasionally, characters might find it necessary to mount or have mounted weapons on their planetary vehicles.
All of these weapons require the gunnery skill to use them properly.
Additionally, a character who must fire a weapon and maneuver the vehicle incurs a multi-action penalty.

Each weapon may fire once per round, because they need some time to recharge.

All weapons increase the cost by +5 to the price difficulty.
For an additional cost, the vehicle can be installed with a weapons computer that improves the gunnery roll by +1D for each +3 increase in cost.

*Blaster Cannon:* damage 3D; range 200/500/1500

*Laser Cannon:* damage 5D; range 250/750/1750

*Rocket Launcher:* damage 6D+2; 400/1500/3000

=== Ship Weapons

Occasionally, characters might find it necessary to mount or have mounted weapons on their sailing vessels.

*Cannon:* Made of heavy metal, cannons use gunpowder (or a magical substance) to project large metal balls at a target.
Each small cannon requires a crew of two to load and fire, while a large cannon needs a team of four.
It requires one action each round to fire either size, and they can only be fired every other round.
The leader of the cannon team aims and fires the weapon, with the marksmanship skill.

A Critical Failure could mean that powder was added incorrectly and it doesn’t fire at all — or the gunpowder explodes in the cannon and does damage to its users.
Ships with a scale value of at least 15 may add cannons.
Cannons may not be turned, though their crews can raise or lower them.
_Small_ _cannon:_ damage 4D; range 50/200/800; price difficulty of Very Difficult per cannon or 75 gold.
_Large_ _cannon:_ damage 5D; range 50/150/500; price difficulty of Heroic per cannon or 125 gold.

*Catapult:* A small rope-and-wood structure mounted on the fore or aft of the ship, out of the way of the sails, the catapult slings a large object (usually a rock or metal ball) at its target.
It requires a round to reload.
Because of its difficulty to aim correctly, add +5 to the user’s marksmanship difficulty.
They may be mounted on any vessel with a scale value of at least 12.
_Catapult:_ damage 3D+2; range 45/90/180; price difficulty of Very Difficult per catapult (up to two) or 50 gold per catapult.

*Ram:* A long, stout wooden pole, the ram be mounted on any galley or rowed ship with a scale value of at least 15.
When the ship rams another, the pilot must make a successful ramming roll using her pilotry.
With a successful attack, the defender receives double the normal damage, while the attacker gets half.
These values are determined before rolling against Toughness.
A ram adds +5 to the roll to regain control of the ship in the following round.
Critical Failure on a low roll to regain control indicate the ram has broken off and further damages the ship.
A ram adds +1 to the ship’s price difficulty or five gold.

Game Masters might allow a smaller version of this weapon to be mounted on large land vehicles.

:leveloffset: +1

include::armor_weapons_and_vehicles.adoc[]

ifdef::include-space[]
include::basic_ship_design.adoc[]
endif::[]
:leveloffset: -1
