= Miracles

This chapter covers the ability to call upon a higher power for extraordinary effects.
The Miracles skills are available only to char- acters with the Miracles Extranormal attribute.

Although this chapter discusses guidelines for creating miracles, Game Masters may still include uninvoked divine intervention and miraculous artifacts.
Since these sorts of divine intervention don’t have to be explained — they just are — their use is out of the play- ers’ characters’ control.
Only the Game Master can decide the cause and outcome.

=== In the Beginning

As creating miracles relies on similar game mechanics as spells, game- masters and players should reach the “Magic” chapter before delving into this chapter.
The terminology then won’t seem so unfamiliar.

=== Basic Types of Religions

Animism: Belief that all things have a vital life force.
Some versions of animism state that all things have a soul or spirit.

Monotheism: Belief that there is only one god.
Pantheism: Belief that divine beings and the world are the same thing; the creator is the universe.

Panentheism: Belief that all reality is part of the body of a divine being or beings; the universe is a part of the creator.

Polytheism: Belief that there are many gods, though no one god might be vastly greater in power than the others.

Atheism: Belief in the nonexistence of divine beings or spiritual power that can affect the everyday existence of humanity.
Atheists cannot work any miracles, and so cannot have the Miracles attribute.
However, they can have the atheism specialization of mettle, to reflect their extreme support of this philosophy.
Atheists are treated as strong disbelievers by all mythos.

=== Invocations versus Spells

Invoking miracles differs from casting spells in a fundamental way.
Magic bends the forces of the universe according to alternate laws of nature.
Miracles require a connection to a divine will or higher power.
The benefit of this is that invocations can be more effective — they receive a larger result points bonus, have a lower minimum difficulty, don’t need a targeting roll, and don’t require the cleric to see her target.
The downside is that the religious devotee has less freedom than his wizarding counterpart — the religion dictates the aspects the cleric may use and circumstances in which the cleric may call for aid.

=== The Basis of Miracles

A mythos, also known as a religion, encompasses the stories, symbols, practices, beliefs, and history that people use to connect themselves to the spiritual power of their universe.
A mythos is a peoples’ interpretation of the way spiritual power works; their faith in this mythos can act as a conduit for such power.
However, faith can only carry power for purposes that coincide with the mythos, and the power must manifest itself in ways that are consistent with the beliefs.
To have faith and work miracles in a religion is to accept all of the core beliefs of the religion.
If a religion says there is only one true god, a faithful follower of that religion can only perform miracles as long as she believes there is only one true god.

Religions differ dramatically in their interpretation of nature, of humanity’s place in nature, and the ethical structure of the universe.
Some religions set humanity (or one particular sentient race) apart from nature, usually one notch above the rest of the world.
A character believing himself to be separate from nature may use nature as he sees fit; for example, animals may be killed for any reason that benefits Mankind, as Mankind is a more divine creature than any other.
Many religions having a strong link with nature assign humanity a place as a piece of nature.
In some nature-centered mythos, prayers must be spoken to get a deer’s permission to kill it, for a deer is as close to the spirits of the world as humanity is.

Before allowing a player to have a character who performs miracles, the Game Master (possibly with input from the player) must first develop the religion or religions of his setting.
That means deciding on the central higher power or powers, which one the character is devoted to, and several tenets or requirements of the religion, includ- ing any that are specific to the character’s preferred higher power.
The Religion Worksheet on the next page can help.
(Fill out the sheet once for the overall religion and once for any specific gods or powers whose tenets vary from the core.) Knowing a few of the basic tenets can help the Game Master decide what sorts of actions the cleric needs to perform in order to invoke a miracle (see “Required Aspects” under “Creating Miracles” for some suggestions).

Religions that have multiple gods may have general requirements for the religion and specific requirements for each god.
Some of the gods might be jealous and demand complete devotion to them, while others could be more lenient and allow their followers to call upon the aid of other (preferably lesser) gods.

Some religions, even monotheistic ones, have not-quite-omnipo- tent beings aiding or hampering their followers.
Called spirits, ances- tors, celestials, angels, saints, demons, and a host of other terms, these beings are not usually worshipped by themselves but can be called upon to act as intermediaries with the divine presence.
They might have a few additional invocation aspect requirements (generally special prayers or other incantations) necessary to add their help to that of the higher power.

Note that calling upon the aid of a being whose purposes conflict with the character’s core religion can have detrimental effects — from an increased difficulty in performing miracles consistent with the primary religion to losing Fate Points.
(The Game Master decides on the most appropriate penalties.)

=== Obtaining Access to Miracles

All characters who want to have the Miracles Extranormal attribute must have at least one rank each in the Devotion and Employed Disadvantages, both related to their religion.
Neither of these count toward the character’s maximum number of Disadvantages.
After that, there are only two ways for players’ characters to get miraculous abilities.
The first is to put dice in the Miracles attribute and skills at character creation, which costs the same as obtaining other attributes.

The second is to obtain the Game Master’s permission after play has begun.
If the player can come up with a reason for the character to learn or gain magic abilities (such as they were latent or were a gift from a supernatural being) and the Game Master agrees, then the player may purchase them for the character.
The cost to get the initial 1D in Miracles is 20 Character Points.
After that, it is 10 times the number in front of the “D” to improve this attribute by one pip.
The player must still purchase Miracles skill pips separately, though a player may buy one pip in one Miracles skill for the character at the same time as he initially gets the attribute after character creation.
When player gives her character the Miracles attribute, she must declare what specific religion she is faithful to.
A character may never have multiple versions of the Miracles attribute, nor may she have any skill, Advantage, or Disadvantage that affects her because of her faith in another religion.

Game Masters are discouraged from allowing characters to have multiple Extranormal abilities, but it is possible, especially if the character has several Disadvantages that show up frequently in each session.
However, some religions may allow — even require — their clerics to have experience with both magical and divine abilities.

=== Learning & Improving Miracles Skills

Miracles skills may be learned between adventures, like regular skills.
The cost for a Miracles skill, in Character Points, equals twice the normal cost for gaining or improving a normal skill.
This cost is doubled again if a teacher — simply another cleric with the skill at a higher level — is not available to instruct the character.
A character may learn or improve one Miracles skill after each adventure.

=== Miracles Skills

All invocations require one of these skills in order to cast them.
When invoking a special prayer, the character generates a Miracles skill total and tries to beat the invocation’s difficulty.
If the skill total equals or exceeds the difficulty, then the invocation works (to a greater or lesser extent).

==== Divination

Divination involves obtaining knowledge of one’s surroundings and of the past and future.
Miracles that increase or decrease the Intellect or Acumen attributes or the skills that fall under them require the divination skill to work properly.

==== Favor

Miracles that relate to building up, enhancing, or creating some- thing fall under the favor skill.
Some examples include increasing attributes, adding skills, bestowing Special Abilities, and conjuring food — as long as giving any of these in no way harms the target or can be used by the target for harm.
Thus, a devotee would use this skill to improve another character’s dodge but not to improve his marksmanship ability.
Likewise, the favor skill could not work with a miracle that gives a character a Disadvantage (which falls under the strife skill), nor does it affect Intellect or Acumen attributes or skills (those are the domain of the divination skill).

==== Strife

Characters use the strife skill with miracles that deal with destruc- tion, reduction, or harm.
Some examples include slowing another’s movement, decreasing skills or attributes, increasing or gifting combat skills (except dodge), causing injury, interrupting another miracle or spell, and cursing targets with Disadvantages.
It cannot be used to affect Intellect or Acumen attributes or skills, as these fall under the divination skill.

=== Untrained Invocations

Characters might have moments of inspiration in areas in which they have no training.
For those who have some train- ing (that is, pips or dice in any Miracles skill), the difficulty increases by +5 to invoke a miracle using a skill in which they have no experience.
For those who have no training (that is, no pips or dice in any Miracles skill but they do have dice in the Miracles attribute), the difficulty increases by +10 for all invocations.

=== Using Invocations & Their Effects

Roll the skill for the invocation in question to get a skill total.
If the total is higher than the difficulty number, the invocation has succeeded and the devotee may use the miracle effect.

Which Miracles skill the invocation requires is either decided when the effect is developed or listed with a sample miracle.

Remember that players may spend Character and Fate Points to make sure they have sufficiently high skill totals to invoke the miracle.

With a higher power there to help a miracle to happen, most invocations do not require a targeting roll.
(This is quite unlike a magical spell.) Furthermore, the devotee need not even see her target for her prayer to affect it.
Game Masters may allow the requirement of a targeting roll or the target being within the cleric’s line of sight to be optional conditions of the invocation.

For those miracle that do have targeting rolls, invoking them at the same time as using its targeting skill is not considered a multi- action.
However, if the character wishes to call for a miracle with targeting skill roll in addition to using a sword in the same round, then the multi-action modifier of -1D (for taking two actions in the same round) is applied to the miracle skill roll, the miracle targeting roll, and the weapon targeting roll.

=== Strain and Failure Options

If an invocation fails with a Critical Failure, the devotee may not attempt that miracle for at least 24 hours (depending on how much she failed the roll by) or until she undergoes a purification ritual or performs some other restriction dictated by her religion.

To simulate the strain of channeling the divine will, Game Masters may choose to increase the difficulty to invoke miracles by 1 for each invocation that the character performs beyond a set number (such as five or 10) before the cleric has a chance to rest (generally, five minutes or so per miracle cast prior to the break).

=== Circumstances of Invocations

Invocations are spiritual power realized to fulfill a need of the faith- ful, often affecting the material world.
Invocations are not spells, dry processes that may be learned and then safely put away in a magic jar for use when desired.
The conditions facing the faithful who request the miracle greatly affect the outcome of the miracle.

Every mythos has certain certain basic tenets.
A miracle that does not conform to those tenets suffers a modifier to its difficulty.
Game- masters can also penalize miracles if the devotee has no immediate need for them.
Similarly, clerics casting miracles to save their own lives or the lives of the faithful receive a bonus.
See the accompanying chart for details; all modifiers listed are cumulative.

Example: A cleric who belongs to a religion with firm restrictions against killing for any reason decides to invoke a lethal miracle.
This adds 15 to the difficulty.
If the cleric also had urgent need of that kind of miracle, such as to save a friend’s life, the miracle would also get a -5 modifier.

Miracles that benefit no one cannot be performed.
Thus, a cleric belonging to a religion restricting killing can cause only harm to another living being if doing so would save another person (and possibly herself) from injury.

.Miracle circumstances
[%header,format=csv]
|===
include::circumstances.csv[]
|===

== Invocation Success Levels

These guidelines can help you determine how well a miracle occurred.
Subtract the difficulty from the Miracles skill total to get the result points, then use that number to determine the level.
Where appropriate, the invocation receives a miracle success bonus equal to the difference between the skill and the difficulty.
This bonus may apply to to the effect or one aspect of the miracle.

Minimal (0–2): The miracle meets the needs of the devotee while disturbing the environment as little as pos- sible.
It would be hard to convince anyone that it wasn’t simply coincidence.

Good (3–6): The miracle not only happens as desired, there is some small side effect that divine intervention happened.
The effect depends on the type of miracle and the nature of the divinity called upon, but it could include bright colors in the area, sweeter air, an uglier wound, and so on.

Superior (7–12): The miracle occurs much better than hoped, and the devotee gains some additional benefit, such as asking for navigational aid on a cloudy day and not only getting a breeze to disperse the clouds, but also finding a map to guide them.

Spectacular (13 or more): There is no question that divine intervention caused the miracle to occur.
The results are well beyond what the devotee requested, though not more than the situation needs.
For instance, if the charac- ter wished merely to harm someone and not to kill them, a miracle causing injury would not bring death to the target if the devotee managed this level of success.

== Designing Invocations

The game mechanics of creating invocations work the same way (in general) as designing spells, though the game-world process is different.
Read through these restrictions and modifications to spell aspects, then use the guidelines in the “Magic” chapter to create your miracles.

== Choosing the Skill

What happens when a cleric wants to include effects dealt with by more than one Miracle skill? The Game Master and player need to decide what the intent of the invocation is.
For instance, a miracle that creates an undead helper endowed with the ability to lift objects and look for small items falls under favor, while one that resurrects someone in order to wreak havoc — even if that means giving the undead the lift- ing skill to carry off objects or people or the tracking or search skill to look for them — comes under strife.

== Starting the Process

Begin the invocation design process in the same manner as the spell design process, with the starting Spell Total and Negative Spell Total Modifiers (see page 86). Then, continue the process in the same manner as for a spell, keeping the restrictions and requirements for miracles in mind.

Most invocation Spell Totals begin at zero, but Game Masters who want requested divine intervention less common and miracles to be more difficult to invoke should have a greater starting Spell Total.
The Negative Spell Total Modifier always starts at zero.

The blank Invocation Design Sheet, found at the end of this chap- ter, includes a worksheet that can help you with the calculations.
A calculator might also help.

== Required Aspects

Miracles share the same basic aspects as spells — effect, range, speed, duration, and casting time.
However, they also involve one or more limiting factors, as dictated by the religion.
The cleric does gain the benefit from adding it to the miracle.
Clerics must include the required aspects in any miracle they perform, though, unless the religion mandates otherwise, they don’t need to include all of them.
Required aspects include: community, components, concentration, countenance, feedback, gestures, and incantation.

== Disallowed Aspects

A miracle may not include charges (except as a ward) or unreal effects.
Generally, Game Masters should disallow the other alterants aspect; the success of the miracle dictates its effects.
It’s unwise for a devotee to ask for more than the minimum that would satisfy her current need.

== Aspect Specifics

Although miracles can involve most Magic spell aspects as is, a handful have restrictions or modifications.

== Casting Time

The minimum casting time required by all miracles is 1.5 seconds (which has a value of 1). Should the mythos also require any other aspect outside of a single-word or single-sound incantation, quick gesture, or the like, the casting time may need to be readjusted to take this into account.
Subtract this from the miracle’s difficulty.
See the “Adjusting Sample Miracles” part in the “Sample Miracles” section for further details on changing the casting time.

== Charges

The only way a miracle can be charged is to install it as a ward in something.
No skill may circumvent a miraculous ward; therefore, that part of the modifier may not be included.

== Community

A cleric may only gain benefit from those who believe in the same or related mythos.

To determine how effective a community is with a pre-existing invocation, figure the community modifier for the group the cleric intends to use.
(The focus of the miracle, as long as it’s not the miracle invoker, can be considered part of the community.) Subtract the new community modifier from the one required by the miracle (if any). Divide this number by 2 and round up.
Subtract this number from the miracle’s difficulty.

Game Masters may optionally allow the faithfulness of helpers to affect the miracle.
A designer of a ritual may include this factor in the miracle’s design, or it can be tacked on when someone per- forms the miracle.
Use the accompanying chart to determine the helpers’ faithfulness.
The level of faithfulness refers only to helpers who believe in the same mythos as the cleric, or who are strongly opposed to it.
Those who believe in other mythos that share some of the basic tenets of the cleric’s mythos might, at the Game Master’s discretion, provide a modifier of 1 or 2 (depending on how closely the two mythos are). Add the modifier to the Negative Spell Total Modifiers at miracle design or subtract one-half (rounded up) from the sample miracle’s difficulty.

.Miracle community
[%header,format=csv]
|===
include::community.csv[]
|===

== Components, Gestures, Incantations

The most common components include the following: food; plants; enemies; tattoos; locations (such as standing on holy ground or near a sacred tree); alignment of planets; phase of the moon; and items of value (either as defined by the society or personally to the cleric). The rarity of the item, location, or situation determines the modifier that the aspect provides.

The most common gestures include the following: folding hands or arms; touching, waving, or making motions with a holy symbol; holding the hands in a certain way; totem carving; dancing; painting; drawing designs on skin; violent acts; playing a musical instrument; ringing bells or similar items; complex body positions; sensory depri- vation; bathing; specific body movements; and gathering items.
Any of these may be used at any complexity.

The most common incantations include the following: words or thoughts directed or related to the divinity in praise, thanksgiving, pardon, or petition; one or more of the divinity’s names; passages from religious texts; words or phrases sacred to the divinity; and oaths of fealty to the divinity.
They could be sung, spoken, or chanted.
Any of these may be used at any complexity.

== Countenance

Generally, a devotee will go pale, have flushed cheeks, or shake convulsively.
No psychic illusion ever touches their features.

== Feedback

Feedback represents self-sacrifice by the devotee.
It also may include some sort of physical gesture.
Generally, the devotee cannot simply will himself to become injured; he must actually do something harmful to himself.
(As this is a gesture, he also gets the modifier from that aspect.)

However, the Game Master may permit the possibility that the divine power to which the cleric is devoted can injure him.
In this circumstance, the character only receives the modifier from feedback; any self-immolation modifier would be included separately.

== Variable Movement

As invocations generally do not require a targeting roll, nor does the devotee need to see the target, most of this aspect serves no purpose for a miracle.
Nonetheless, the cleric might find that “movement of effect” comes in handy on occasion.

== Other Conditions

Game Masters should carefully consider whether the mythos sup- ports the player’s proposed modifying condition before allowing a player to include it in her miracle design.
Physical touch exists as the most common other condition modi- fier.
It provides a modifier of -1 to -3, depending on how difficult it is to make contact.

== Minimum Difficulty

The minimum difficulty for any invocation is 5.

== Design Time

Miracles that have no aspects providing modifiers greater than 2 have a design time of one round, regardless of the miracle difficulty.
For all others, follow the Magic design time guidelines.

== Sample Invocations

=== Adjusting Sample Invocations

These sample invocations have been designed as generically as possible.
Thus, they do not include any of the required aspects as modifiers.
To add the mythos’ specific requirements, determine the value of all of the modifying aspects needed.
Then divide this by 2 and round up.
Subtract that number from the difficulty to determine the new difficulty of the miracle.
Should the required modifiers drop the miracle’s difficulty below 5 (not including any circumstances modi- fiers), the player will need to recreate the miracle following the Magic spell creation rules, though the minimum difficulty is 5.

For precalculated invocations that the cleric wishes to adapt to his religion, it is best to recreate the miracle using the proper values for the various aspects.

=== Example

A character belongs to a monotheistic religion that requires invocations to include a prayer of at least a sentence or string of holy words (incantation of -1 or more), bowing the head and cross- ing the arms on the chest (a simple gesture of -1 and a fairly simple gesture of -2), or both.
She decides to perform a foresight invocation and include both a complex incantation with a persuasion difficulty of 11 and her gestures.
This gives her a total requirement modifier of 3 (3 for the incantation + 3 for the gesture = 6, divided by 2 = 3). She subtracts this number from the foresight difficulty of 19 to get a modified divination difficulty of 16.

=== Favor

==== Bless Person

Skill Used: Favor

Difficulty: 11

Effect: 6 (+1D bonus to one non-Extranormal attribute)

Range: 10 meters (+5)

Speed: +5

Duration: 5 rounds (+7)

Casting Time: 2 seconds (-1)

Other Aspects:

Other Condition (-3): Bonus may not be used to harm anything (-1); limited to humanoids (-2)

A bless person surrounds and infuses the target character with spiritual energy, as long as the target remains within 10 meters of the blessing cleric.
The blessing enhances one attribute of the cleric’s choosing, which must be selected at the time he performs the bless- ing.
The blessed character receives the miracle success bonus to all related totals.

A character may enjoy the effects of only one bless at any given time.
The cleric may use bless person on himself.

==== Bless Armor

Skill Used: Favor

Difficulty: 13

Effect: 9 (+2D Armor Value bonus)

Range: 10 meters (+5)

Speed: +5

Duration: 8 rounds (+8)

Casting Time: 2 seconds (-1)

Other Aspects:

None required

Bless armor infuses spiritual energy into any armor or garment that a single character is wearing, as long as the target remains within 10 meters of the blessing cleric.
The blessed character adds the miracle success bonus damage resistance totals.

A character may enjoy the effects of only one bless at any given time.
The cleric may use bless armor on herself.

==== Enhance Food

Skill Used: Favor

Difficulty: 8

Effect: 1 (1.5 kilograms of food)

Range: 1 meter or less (0)

Speed: 0

Duration: 4 hours (+21)

Casting Time: 1 round (-4)

Other Aspects:

Components (-2): Any kind of food, in any condition (very common)

Food blessed by this miracle becomes better tasting, more nutri- tious, and possibly transforms into another food entirely.
If not eaten within 10 minutes of its improvement, the food turns back to its original condition.
(The four-hour duration is about how long it takes for the body to break down the food, so the food needs to remain in existence within the body for at least that long.)

Minimal or average success turns spoiled meat, rotted vegetables, and the like into fresh food again.
Good success can cleanse any food of any impurities or poisons.
Superior success increases the quality of the food to the very best possible.
Spectacular success actually transforms the food into a different kind of food; changing from a common fruit to an exotic one, from a cheap cut of pork to an expensive cut of beef, water to wine, and so on.

==== Healing

Skill Used: Favor

Difficulty: 7

Effect: 17 (healing skill of 5D+2)

Range: 1 meter or less or touch (0)

Speed: 0

Duration: 1.5 seconds (+1)

Casting Time: 1 round (-4)

Other Aspects:

None required

By channeling her spiritual energy to an injured person or creature, the devotee can use this miracle to heal harm as if she had 5D+2 in the healing skill.
Add the miracle success bonus to the healing total.

==== Multiply Food

Skill Used: Favor

Difficulty: 8

Effect: 1 (1.5 kilograms of food)

Range: 1 meter or less (0)

Speed: 0

Duration: 4 hours (+21)

Casting Time: 1 round (-4)

Other Aspects:

Components (-2): About a kilogram of any kind of edible food (very common)

The multiplying food invocation is performed on an amount of existing food equal to a decent meal for one normal person.
For each success level gained, double the amount of food.
Any food not eaten within 10 minutes of its production rots or turns to dust.
(As with enhance food, the food needs to be within the body for at least four hours to give the body enough time to break it down and get nourishment from it.)

==== Ritual of Purification

Skill Used: Favor

Difficulty: 12

Effect: 20 (compare to miracle or curse difficulty)

Range: 2.5 meters (+2)

Speed: +2

Duration: 30 minutes (+16)

Casting Time: 30 minutes (-16)

Other Aspects:

None required

The purification ceremony heightens awareness of one’s religion and removes the impurities of the mundane and the material from the spirit.
With a minimal or average success, it allows the target to invoke one miracle he failed or it removes one curse (either magical or miraculous). For any level above average, the target either receives the miracle success bonus to any miracle he attempts within the duration of the ritual or may add the miracle success bonus to the effect’s value to allow invocation of one failed miracle or remove any one curse.
The difficulty of the curse or failed miracle must be equal to or less than the effect’s value (plus the miracle success bonus, if applicable) in order for the ritual to work.

==== Spiritual Shield

Skill Used: Favor

Difficulty: 13

Effect: 16 (Armor Value of 5D+1)

Range: 1.5 meters (+1)

Speed: +1

Duration: 5 rounds (+7)

Casting Time: 1.5 seconds (-1)

Other Aspects:

Area effect (+2): 1-meter radius

If successfully invoked, a shield of spiritual energy, about two meters in diameter, appears up to 1.5 meters in front of the cleric.
It offers an Armor Value of 5D+1 against all types of physical (not mental) attacks.

=== Divination

==== Detect the Living

Skill Used: Divination

Difficulty: 20

Effect: 24 (search of 8D to locate a single type of creature)

Range: Self (0)

Speed: 0

Duration: 10 seconds (+5)

Casting Time: 1 minute (-9)

Other Aspects:

Area effect (+20): 10-meter radius circle

Other Condition (-1): Limited to one type of creature

Before invoking, the devotee decides what sort of being he seeks.
Should the cleric successfully invoke the miracle, he can detect the presence of any such being within a 10-meter radius for two rounds, whether he can see it or not.
The higher the search skill total is above the difficulty, the more information the caster knows about the beings he seeks (such as location, number, gender, etc.). The difficulty starts at 10 for a Human-sized creature, and goes down for larger creatures, up for smaller ones, and up for the number of other types of creatures in the area.
Add the miracle success bonus to the search total.

==== Foresight

Skill Used: Divination

Difficulty: 19

Effect: 34 (2.5 months)

Range: Self (0)

Speed: 0

Duration: 1 minute (+9)

Casting Time: 2 rounds (-5)

Other Aspects:

None required

When the cleric invokes this miracle, he chooses to look for a con- dition that could occur up to two and a half months into the future.
He can see one minute’s worth of the future.
Use the success level to determine the information received: Minimal reveals confusing images.
Average allows one useful fact to be gleaned from the vision.

Good provides the cleric with a few useful facts, including the time of the occurrence.
Superior allows the cleric to note more details, including time and location.
Spectacular lets the cleric see the scene as if he were present, though in shades of gray.

=== Strife

==== Banish

Skill Used: Strife

Difficulty: 15

Effect: 12 (compare to 2 times the target’s Charisma or mettle)

Range: 20 meters (+7)

Speed: +7

Duration: 1 minute (+9)

Casting Time: 1 rounds (-4)

Other Aspects:

Other Condition (-1): Limited to humanoids (including undead) devoted to a different religion/god/power or undead controlled by a character devoted to a different religion/god/power.

The miracle can only be used against opponents of a different religion.
If successfully invoked, compare the effect total to a value equal to 2 times the target’s Charisma or mettle (including any spe- cialization related to religion). If the target has not taken an action yet this round, she may actively defend by generating a mettle total (including her faith specialization), but this is considered her action for the round.
For undead without a mettle or Charisma score, use the die code of the creatures’ controller.

If the target has a lower total, she flees the area (if possible).

==== Bless Weapon

Skill Used: Strife

Difficulty: 13

Effect: 9 (+2D damage bonus)

Range: 10 meters (+5)

Speed: +5

Duration: 8 rounds (+8)

Casting Time: 2 seconds (-1)

Other Aspects:

None required

Bless weapon infuses spiritual energy into any one weapon, as long as the item remains within 10 meters of the blessing cleric.
The invocation applies the miracle success bonus to the damage of the blessed item.

A character may enjoy the effects of only one bless at any given time.
The cleric may use bless weapon on an item he’s holding.

==== Curse

Skill Used: Strife

Difficulty: 14

Effect: 6 (Bad Luck (R2) Disadvantage)

Range: 10 meters (+5)

Speed: +5

Duration: 10 minutes (+14)

Casting Time: 1 round (-4)

Other Aspects:

Focused (+4): On target

Other Condition (-2): Limited to humanoids

The cleric curses a single humanoid target with 10 minutes of Bad Luck (R2), which doesn’t leave the target even if he moves out of range.
See the description of this Disadvantage in the “Character Options” chapter for details.
Each success level doubles the amount of time that the target has the curse.

==== Disrupt Spell

Skill Used: Strife

Difficulty: 25

Effect: 29 (compare to skill total of spell countering)

Range: 60 meters (+9)

Speed: +9

Duration: 1 round (+4)

Casting Time: 2 seconds (-1)

Other Aspects:

None required

The cleric concentrates on the spell he wishes to counter.
The effect’s value plus the miracle’s miracle success bonus are compared to the skill total used to create the targeted spell.
If the disrupt spell number equals or exceeds the target spell’s skill total, the spell is broken.

==== Fighting Tree

Skill Used: Strife

Difficulty: 23

Effect: 24 (4D in fighting and 4D in damage)

Range: 5 meters (+4)

Speed: +4

Duration: 1 hours (+18)

Casting Time: 2 seconds (-1)

Other Aspects:

Components (-3): A long supple tree or one with long branches (common)

Through this prayer, the cleric can animate the branches of a tree to strike at anyone within range.
Branches that hit the target inflict 4D of damage.
The tree can strike at no more than Short range — less if it’s small.

==== Spiritual Bolt

Skill Used: Strife

Difficulty: 12

Effect: 12 (4D in damage)

Range: 10 meters (+5)

Speed: +5

Duration: 3.5 seconds (+3)

Casting Time: 1.5 seconds (-1)

Other Aspects:

None required

The cleric gathers spiritual energy to throw in a bolt at a target.
It does 4D in damage at a range of up to 10 meters.
She must make a marksmanship roll to hit the target.
The bolt must be fired in the same round that the cleric invokes the invocation.

==== Undead Warrior

Skill Used: Strife

Range: 25 meters (+7)

Speed: +7

Duration: 1.5 hours (+19)

Casting Time: 2 seconds (-1)

Other Aspects:

Components (-5): Intact dead body or skeleton (very rare). This rite causes any one dead creature to rise in its present state to serve as a soldier bonded to the cleric.
As this is a basic miracle, it imbues the creature with select skills; the cleric may add more and increase the difficulty.
The reanimated being cannot think for itself, so it ignores all Wound level and hit location penalties.
It does whatever the cleric demands, until the invoker tells it to stop or the duration ends.
At the end of the duration or if the cleric sends it out of range, the creature falls down in a heap.
The invocation’s miracle success bonus may either add to the range or to the amount of damage the creature does (it has a base Strength Damage of 2D); which applica- tion must be decided before invoking the miracle.
