= Combat

== What’s in this Section

This chapter provides an extended description of one of the most rules-intensive aspects of role playing: combat.

When resolving a situation calls for force, time becomes broken into rounds, which were discussed in the last chapter.
Within these rounds, three steps occur: (1) generating initiative; (2) attacking and defending; (3) determining damage; (4) repeating the steps, if necessary.
Discover herein what happens in each of those steps.

== Step 1: Generating Initiative

As discussed in the “Game Basics” chapter, determine initiative based on the first significant action or on initiative rolls.
Then go on to Step 2.

== Step 2: Attacking and Defending

This is where the interesting stuff happens.
The person whose turn it is gets to decide what type of action her character is going to do.
Once she chooses, she makes a skill roll.
Note that a character need not attempt to engage in combat, but this chapter only discusses what to do if the player decides to attack, defend, or (typically with a multi-action penalty), do both.

=== Base Combat Difficulty

The base difficulty to attack someone is 10 (called the target’s passive defense value) or the target’s active defense value, modified by range and other factors.

=== Active Defense

The target character can opt to use an “active defense,” which affects all attacks that occur after the defender’s turn in the current round but before the defender’s turn the next round.
Active defenses are defensive maneuvers that the target consciously exercises, such as dodging, blocking, or parrying.
Each of these is represented by a skill and counts as an action.

A character may make an active defenses only when his turn comes up in the initiative line, but the total for the roll is effective for all relevant attacks made against the character that occur after the character’s current turn but before his turn in the next round.

Remember: if a character acts later in a round than the character attempting to hit him, he cannot take his turn sooner and use an active defense to replace the passive defense value — his reactions just weren’t fast enough.

If the roll is lower than the passive defense value, the character has succeeded in making himself easier to hit — by miscalculating where the attack would be placed and actually getting in its way.
The active defense total is modified as the situation dictates.

*Dodge:* The character attempts to anticipate the final location of an attack from any source and be in another place when it comes.
This is done by rolling the dodge skill.

*Block/Parry:* The character attempts to stop his opponent’s attack by intercepting it and either stopping it with a block or deﬂecting it with a parry.
The character may roll his brawling or melee combat (if he has something in his hands) to block it.
If the character uses a sharp or energized weapon (sword or dagger, for example) to parry an unarmed blow and is successful at the block, the attacker takes damage from the weapon.
However, do not add the defender’s Physique to the listed weapon damage score when determining injuries inﬂicted this way.

If the opponent strikes at the character with a bladed or energized hand weapon and the character uses any part of his body to intercept the attack, the defender always takes the weapon’s damage total.
If the block was successful, then the attacker’s Strength Damage is not added to the listed score.
If the block was unsuccessful, then the target character takes damage as normal.
The character may avoid this aspect by having armor, a special ability, or a suitable close combat specialization in melee parry.

=== Full Defense

A character who foregoes all of her actions for a round to completely protect herself from attacks makes a full defense.
The total rolled by the skill plus 10 takes the place of the base combat difficulty from the time the character makes the full defense on her turn to her turn in the next round.

Full active defense value = any active defense skill roll + 10

=== Partial Defense

A character who chooses to do something else in addition to guarding against attacks may take a partial defense.
In this case, the active defense roll replaces the base combat difficulty from the time the character takes his turn in one round to his turn in the next round.

Partial active defense value = any active defense skill roll.
Since the character is taking multiple actions, the multi-action penalty applies.

The Game Master may call for a partial defense roll (as a free action) if he decides that the character might have a little awareness of an impending attack, yet not enough foresight to prepare for it.

=== Optional Defense Modifier

For every 2D in Reﬂexes or dodge above 4D (round up), a character receives a +1 to her passive defense value.
This modifier does not affect the character’s active defense total.
For every 2D in acrobatics above 4D (round up), a character receives a +1 to her active or passive defense value for attacks at Short range or greater.
Every six ranks in a Skill Bonus or Increased Attribute special ability that affects Reﬂexes, dodge, or acrobatics provides a +1 bonus, as specified for the skill in question.

Example: A character with 4D in Reﬂexes gets no bonus, while a character with 7D in acrobatics has a +2 bonus.

=== Combat Difficulty Modifiers

Here are a few of the most frequently used modifiers to the combat difficulty.
Others are discussed in “Combat Options” chapter.
Regardless of the number of modifiers used, the total combat difficulty may never go below 3.

The Game Master rolls the indicated modifier and adds it to the combat situation.
A standard modifier is included in parentheses after the die modifier, should the Game Master prefer not to roll.

*Range:* The effectiveness of a punch, weapon, special ability, or any other attack made at a distance depends on its range.
All range modifiers are added or subtracted from the combat difficulty.
Note that, unless a special maneuver allows otherwise, characters may use unarmed close combat attacks at Point Blank range only.
In most cases, this is true for using various melee weapons as well, though the distance can be increased to Short range if the weapon is longer than two meters.
For instance, a character with a support beam can whack an opponent at Point Blank or Short range.

*Cover:* When a target is protected by something — poor lighting, smoke, fog, a table — it makes her harder to hit.
This is represented by a cover modifier, which is added to the combat difficulty.

*Aiming:* Aiming involves careful tracking of the target.
Characters may perform it against moving targets, but they cannot themselves do anything else in the round in which they aim.
Each consecutive round of uninterrupted aiming adds 1D to the characters’s marksmanship, missile weapons, or throwing skill, up to a maximum bonus of +3D.

=== Combat Difficulty Modifiers

==== Range

Point Blank 0–3 meters -5

Short 3 meters to first value* 0

Medium First to second value* +5

Long Second to third value* +10

*Values refer to values given in the weapon’s range listing.

==== Estimating Ranges

Game Masters who aren’t interested in looking up weapon ranges and figuring out the distance to the target can estimate what modifiers to use with these guidelines.

• A target within a few steps of the attacker is a Point Blank range.

• An attacker firing a riﬂe at a target across a rather large chamber shoots at Short range, while an attacker with a handgun shoots the same target at Medium range.

• Most projectile combat taking place outdoors is at Medium to Long range.

==== Cover

The Game Master rolls the indicated modifier and adds it to the combat situation.
A standard modifier is included in parentheses after the die modifier, should the Game Master prefer not to roll.

Light smoke/fog +1D (+3)

Thick smoke/fog +2D (+6)

Very thick smoke/fog +4D (+12)

Poor light, twilight +1D (+3)

Moonlit night +2D (+6)

Complete darkness +4D (+12)

Object hides 25% of target +1D (+3)

Object hides 50% of target +2D (+6)

Object hides 75% of target +4D (+12)

Object hides 100% of target *

*If cover provides protection, the attacker cannot hit the target directly, but damage done to the cover might exceed the Armor Value it gives the target, and, indirectly, the target receives damage.
Most of the time, the attacker must eliminate the cover before having a chance to hit the target.

=== Determining Success

Once the combat difficulty has been determined, the attacker rolls the die code in his character’s combat skill and compares the total to the combat difficulty.
If it equals or exceeds the combat difficulty, the attack hit, probably doing damage or having another effect that the attacker intended.
If it was less than the combat difficulty, then the attack missed.

=== Vehicle Combat

When characters use vehicles, the basic combat rules are the same; the difference exists in which skill to use.
Vehicles cannot block or parry.
The driver may only make defensive maneuvers (“dodge”); he uses his piloting plus the vehicle’s Maneuverability rating to determine the new combat difficulty.
Ramming or sideswiping with a vehicle requires the driver to make a piloting roll (see the “Vehicles and Aerial Characters” section of the “Movement” chapter for details).

== Step 3: Determining Damage

If a character successfully hits his target, he may have done damage to it.
To determine the amount of injury caused, roll the damage die code for the weapon, including any modifiers from a special combat action, such as a sweep attack or hit location.
Some weapons list their score as a die code with a plus sign (“+”) in front of it; in this case, add the damage die code to the attacker’s Strength Damage die code, add modifiers, and roll.
If the Game Master chooses to use the optional damage bonus, this is added to the total at this time.

After the player or the Game Master has figured out how much damage is done, go to the “Damage” chapter to determine how much of that damage the target sustained.

=== Determining Strength Damage

To figure the Strength Damage die code, drop the pips from the character’s Physique or lifting die code (but include any relevant disadvantages or special abilities), divide the number by 2, and round up.
The Increased Attribute: Physique special ability affects the total.

Example: A character with 3D in Physique has a Strength Damage of 2D.
A character with 6D+2 in lifting has a Strength Damage of 3D.

=== Optional Damage Bonus

The combat skill roll is supposed to reﬂect the accuracy of an attack.
Therefore, Game Masters may reward high rolls for players’ characters and significant Game Master characters with a bonus to damage.
Subtract the difficulty of the successful attack from the skill total and divide this number by 5, rounding up.
Add this damage bonus to the damage total before comparing it to the resistance total.
If the Game Master uses the damage bonus in combination with a called-shot hit location, the bonus is in addition to the damage modifier except for attempts on an arm, leg, or hand.
In those cases, ignore the damage bonus.

For special abilities and Extranormal skills that require a combat roll to target them, the Game Master may allow the combat roll’s damage bonus to apply to the ability’s roll.

== Step 4: Repeat

If the fight isn’t finished after one round, then return to Step 1 in the “Combat” chapter and do it all over again.
Repeat these steps until the fight is resolved in favor of one side or the other.

=== Combat Summary

You can find a summary of the information in this chapter on the Reference Sheet included in the back of this book.

=== Combat Example

To give you an idea of how all this works, here’s a typical exchange between a player’s character and one of her opponents.

*Game Master:* Okay, we’re in combat rounds now.
Everyone make a Perception roll.
(All players and the Game Master roll their dice.) Anyone roll higher than 20?

*Rachelle:* Yeah, I rolled a 23!

*Game Master:* All right, what do you want to do?

*Rachelle:* Ah, that depends.
What’re the mercs doing?

*Game Master:* As one runs across the warehouse toward you, the other two set up some kind of large, tripod-mounted weapon near the entrance, which is about 15 meters away from you.

*Rachelle:* I’m going to take two actions.
First, I’ll shoot at one of the mercs with my rifle, and them I’m going to dodge out of the way.

*Game Master:* Okay, you lose 1D from each action and you don’t get the full defense bonus, since you’re taking two actions.

*Rachelle:* (Rolls her character’s marksmanship dice.) I rolled a 6 on the Wild Die! (Rolls the Wild Die again.) All right: that’s a total of 21!

*Game Master*: Let’s see… he’s at Short range, which doesn’t modify the base combat difficulty of 10.
So, you nailed him! Roll damage.

*Rachelle*: (Rolls her rifle’s damage dice.) I rolled an 18.

*Game Master*: (Using the Wounds system, he rolls the merc’s Physique to resist the damage.) Whoops! I rolled a 1 on the Wild Die.
That leaves a total of 2.
Well, that’s 16 points over the resistance total, putting him at the Dead level! Your rifle shot catches him right in the chest and he’s thrown backward into the wall.
Okay, now make your dodge roll.
(Note that if the Game Master had decided to use the Body Points system, the merc would not have made a resistance roll, instead taking the full 18 points of damage.)

*Rachelle:* (Rolls her character’s dodge dice.) Well, I rolled a 13, but something tell’s me that’s not going to be high enough, so I’m going to spend a Character Point.

*Game Master*: Okay, roll another die and add it.

*Rachelle*: (Rolls one more die.) I rolled a 5, so that’s a total of 18.
I’ll stick with that.

*Game Master:* Okay, the mercs get to go now.
The one rushing toward you fires his handgun.
(Checks range and then rolls the merc’s marksmanship dice.) That’s a 17.

*Rachelle:* I rolled an 18 for my dodge this round.
Good thing I spent that Character Point!

*Game Master:* That’s right.
As the bullet heads straight toward you, you just barely manage to jump out of the way.
On to the next one…

:leveloffset: +1

include::combat_options.adoc[]

include::damage.adoc[]

include::healing.adoc[]

:leveloffset: -1
