= Combat Options

== What’s in this Chapter

Players sometimes want their characters to do some pretty fancy maneuvers during combat. This chapter offer guidance with several common ones.

== Using the Modifiers

All modifiers listed in this chapter and in the “Combat” chapter are cumulative, though the Game Master doesn’t need to include all of them. Modifiers may never adjust the total combat difficulty below 3.

The Game Master rolls the indicated modifier and adds it to the combat situation. A standard modifier is included in parentheses after the die modifier, should the Game Master prefer not to roll.

=== Combat Difficulty Modifiers

==== Marksmanship

Burst fire as single; Difficulty modifier 0; Damage modifier -2D

Full auto; Difficulty modifier -2D (-6); Damage modifier +2D

Single fire as multi; Difficulty modifier -1D (-3)*; Damage modifier +1D*

Sweep; Difficulty modifier -2D (-6); Damage modifier -3D

*Modifiers are per additional round of ammunition, up to maximum that the weapon holds.

==== Brawling, Melee Combat

All-out; Difficulty modifier -2D (-6); Damage modifier +1D

Grab; Difficulty modifier +2D (+6) *

Lunge; Difficulty modifier +1D (+3); Damage modifier -1D

Knockdown, trip; Difficulty modifier +2D (+6) *

Push; Difficulty modifier +1D (+3) *

Sweep; Difficulty modifier -2D (-6); Damage modifier -3D

Tackle; Difficulty modifier +1D (+3) *

==== All Attacks

Low gravity; Difficulty modifier -1D (-3); Damage modifier 0

No gravity; Difficulty modifier -2D (-6); Damage modifier 0

Heavy gravity; Difficulty modifier +3D (+10); Damage modifier 0

==== Called Shot

Target is…

10 to 50 centimeters long; Difficulty modifier +1D (+3) *

1 to 10 centimeters long; Difficulty modifier +4D (+12) *

Less than a centimeter long; Difficulty modifier +8D (+24) *

*See text for options.

==== Other Modifiers

• The attacker is blind or blinded: +4D (+12) to the combat difficulty

• The target is blind or blinded: -4D (-12) to the combat

== Marksmanship Options

*Burst fire as Single:* A character may perform this attack only with a weapon capable of burst fire (like an assault rifle) and switching to single fire. The firer fires only one shot instead of a burst; it is primarily used to conserve ammunition.

*Full Auto:* This attack is only possible with weapons that can fire at fully automatic settings (such as assault rifles, sub-machine guns, and machine guns). Since the character is taking quite a bit of time to “hold down the trigger” and pump ammo into the air, the extra “to hit” and “damage” bonuses are somewhat compensated for by the modifier to the character’s defensive value during the round he is performing a full auto attack.

*Single fire as Multi:* The character fires a weapon (such as a pistol) several times in a round at the same target. Characters may use this option only when a weapon automatically reloads itself after firing a single shot or when it is fairly easy to ready it for firing again (such as a .45 automatic, which puts a new cartridge in the slide as soon as the first one clears the barrel). It increases the character’s chance to hit a target, as well as the damage. It does not count as a multi-action as long as the shot is taken at the same target. One target, one die roll, one damage total.

*Sweep (Ranged):* The character wants to “spray an area” with ammo. Only characters with weapons that go full auto, burst, or single fire as multi (in general, just about any automatic weapon) can perform this maneuver. The gun uses the amount of ammunition needed by whichever setting is used. They gain a positive modifier to hit (because of the sheer volume of shots), but this “non-targeted” attack results in a lower damage total.

== Brawling and Melee Combat Options

*Acrobatic Tricks:* Acrobatics can also enhance brawling and melee combat attacks. The character must perform the acrobatics trick and the attack on the same turn. The Game Master determines the exact difficulty of the acrobatics attempt. The player may add one-half of the difference (rounded up) between the difficulty and the successful acrobatics roll to the amount of damage done (not to the combat skill roll). One acrobatics trick roll can affect one attack only.

*All-out Attack:* The character attacks with no thought to the consequences. This maneuver increases the chance of the character striking the target, but, in that round, the attacker cannot perform any other action at all — not even to actively defend.

*Lunge:* The character takes a step forward to jab at an opponent, usually with an edged weapon. This adds about a half-meter (more or less depending on the stride) to the range of the attack, but it lowers the effectiveness of the attack.

*Knockdown/Push/Trip:* Using brawling or a blunt melee weapon in the usual way, the attacker causes his target to stumble and, instead of taking damage, the opponent loses 2D from her next Reflexes or Reflexes-based skill roll. If this is a knockdown or trip attempt, she must also spend one action to stand up again. Generally, unless the character has special training, he may only knockdown or push a character whose Physique (including Special Abilities or Disadvantage modifiers) is equal to or less than his own.

*Sweep* *(Close* *Combat):* These attacks, usually foot sweeps or roundhouses, are used when the character wants to make certain she hits the target, regardless of how much injury is caused.

*Tackle:* Tackling is much like grabbing, except that the attacker seeks to overcome the target entirely. Characters may perform this with brawling only. If successful or the target chooses not to struggle, the character captures the target and may, if desired, do normal damage. The target, meanwhile, may make no other actions than attempt to escape (see the escape rules herein). On subsequent rounds, the attacker may choose to do her Strength Damage only (no modifiers).

*Grab:* The attacker physically grasps a target. Few melee weapons allow this option, so it is used generally only in brawling attacks. What effect this has on the target depends on the type of grab. (The ones listed here are choke, flip, hold, slam/throw, and arm pin.) See the escape rules in this chapter for details on getting out of grabs. On subsequent rounds of a grab, attackers who defeat an escape attempt or against a defender who chooses not to resist may do their Strength Damage only (no modifiers except those from Special Abilities or equipment). Some grab variations may offer other options.

*Choke:* Ropes and hands can cut off the target’s source of air. Damage on the first round equals the character’s Strength Damage plus any modifiers. See the general grab rules for damage on subsequent rounds.

*flip:* The character reaches out, grabs his opponent’s wrist, arm, leg, or similar body part, and jerks violently, causing the opponent to fall to the ground. The opponent takes 3D in damage from slamming into the ground and must spend the next round getting to her feet (if she can).Hold: The character does less damage (-3D or more, at the player’s option, to the damage total), but she has hold of the target with a successful attack.

*Slam/Throw:* The character grabs or picks up his opponent and hurls him into the ground, a wall, a bus, or another obstacle. Lifting the opponent counts as an action (using the lifting skill), as does slamming or throwing the target (which uses the throwing skill). The character must be strong enough to pick his opponent up to use this maneuver. Once slammed into an object, the target takes the damage score of the object (usually determined by its Toughness, but the Game Master may adjust this) plus the attacker’s Strength Damage. The object being slammed into takes the Strength Damage of the opponent.

*Arm* *Pin:* The hero grabs his target’s arm and forces it around behind her, pinning it there. After the first round, the player has three choices as to what his character can do. Each option counts as a separate action.

Option 1. The character does his Strength Damage only for each round he has the arm pinned.

Option 2. The character tries to break the opponent’s arm. The attacker must make a successful Physique or lifting roll versus a breaking difficulty

If the opponent does not resist, the difficulty equals two times the target’s Physique or lifting die code plus the pips plus any relevant protection. Failing to beat the breaking difficulty in this case means the target takes damage as in option 1.

If the target chooses to resist, she may make no other action in the round, but she may move her turn up. Instead, the player rolls her character’s Physique or lifting and adds 5 and any relevant protection to the total to generate the breaking difficulty Failure by the attacker to beat the breaking difficulty in this case means that the target wrenches free and may freely take action on the next round.

Option 3. The character may attempt to force the target to the ground while maintaining his hold on the arm. The attacker rolls his brawling against a submission difficulty

If the opponent does not resist, the submission difficulty equals two times her Reflexes die code plus the pips. Failing to beat the breaking difficulty in this case means the target takes damage as in option 1.

If the target chooses to resist, the opponent may make no other action in the round, though she may move her turn up. Instead, the player rolls her character’s Reflexes and adds 5 and any relevant modifiers to the total to generate the submission difficulty Failure by the attacker to beat the difficulty in this case means that the target wrenches free and may freely take action on the next round.

== Options for Various Combat Skills

=== Breaking Things

Use the demolitions skill guidelines in the “Example Skill Difficulties” chapter for determining the effect of damage on items.

=== Called Shot

The character chooses a specific target, like a gun in a thug’s hand, and aims for that. This is represented by a called-shot modifier, which is added to the combat difficulty On a successful attack, he knocks the item out of the target’s hand, grabs the limb, pins the target to a wall, or does +1D (or more, at the Game Master’s discretion) to the damage. The exact result depends on the situation and the player’s intent.

=== Disarm

If the disarm attempt is successful and the target character has not made an action yet, she may move up her action to try and keep a grip on the item she’s holding. The defending character makes a Physique or Lifting roll against the amount of damage done. If the defender’s roll is greater than the damage, the target character retains the item. If it is less than or equal to the damage, she drops it.

=== Entangle

A hero throws an entangling weapon at her opponent. On a successful marksmanship, missile weapons, or throwing roll (as appropriate), the end of the weapon wraps itself around the target. Unless the weapon is spiked, electrified, or enhanced in some other way, it does no damage, but it prevents the target from doing any action except for trying to break free. The target may escape by snapping the bonds or slipping free, each of which counts as an action. To break the weapon, he must make a Physique or lifting roll that meets or beats the damage total of the weapon. To slip free, he needs to roll a Reflexes total equal to or higher than the weapon’s damage total.

=== Escape

To break free from any hold, the character must make a successful opposed Physique or lifting roll versus the holder’s Physique or lifting. This counts as an action.

=== Group Attack

This is a coordinated action. See the description of the command skill in the next chapter for details.

=== Hit Locations

Hit locations are a special kind of called shot that allows a character to shoot or strike a specific point on his target’s body. The table is used to determine the modifiers for hitting a target of Human proportions in different areas of his body. Note that aiming at an arm or leg actually causes less damage — this is because the character took extra care to shoot an area that is “less vital.”

==== Hit Locations

Head; Difficulty modifier +1D (+3); Damage modifier +12

Heart; Difficulty modifier +4D (+12); Damage modifier +12

Chest, abdomen; Difficulty modifier 0; Damage modifier 0

Left or right arm; Difficulty modifier +1D (+3); Damage modifier -2

Left or right leg; Difficulty modifier +1D (+3); Damage modifier -1

Left or right hand; Difficulty modifier +4D (+12); Damage modifier -2

==== Effects

At the Game Master’s discretion, sufficient damage to a particular hit location can affect the target’s ability to use that part. Except for blows to the chest, the modifier lasts until the character heals that portion (which typically takes a few days, as Body Points or Wounds are recovered for the body as a whole, not just a specific part). When the medicine skill or a healing spell is applied, it can be specified to repair one particular location.

Hit location modifiers are in addition to Wound level modifiers. If you are using them instead of the Wound level modifiers, then all -1 modifiers increase to -1D modifiers.

*Chest:* The character can do no more than passively defend in the next round.

*Foot* *or* *leg:* -1 to all acrobatics, sneak, movement, and initiative totals.

*Hand* *or* *arm:* -1 to all acrobatics, brawling, climbing, melee combat, missile weapons, sleight of hand, throwing, lifting, and any other rolls involving the hand or arm.

*Head:* -1 to all Knowledge, Perception, and initiative totals.

=== Knockout

This option does only half of the normal damage, but it can render the target immediately unconscious with a successful attack. It requires a successful called shot to the head. If, after the resistance total has been subtracted, the target sustains at least two Wound levels or 50% of his maximum Body Points in damage, then he falls unconscious for a number of hours equal to difference between the combat skill total and the combat difficulty or until he’s awoken by some external force, whichever comes first. The target receives only half the Wound levels or Body Point damage inflicted (round down).

=== Multiple Weapons

Weapons that characters can use with one hand and in either hand, such as knives or most guns, may be employed at the same time in the same round. The character incurs a multi-action penalty.

=== Prone and Crouching

Attacking a target that is crouched on the ground adds 1D (3) to the combat difficulty If the target is moving while crouching, then the combat difficulty increases by 2D (6), but the defending character’s normal Move, free Move, or running result is halved.

For prone targets, subtract 2D (6) from the combat difficulty when attacking at Point Blank or Short range, but add 2D (6) to combat difficulty when attacking at Medium or Long range.

Characters who willingly get low to the ground or make themselves small may get into and out of the position as a free action. However, character forced into that position, such as a result of being thrown, need to make an effort to stand, which counts as an action.

=== Quick Draw

This option allows the character to act rapidly or draw and fire a weapon in the same round as one action. The character may use any combat skill or appropriate specialization. If she is also using a weapon, it must be suitable for quick drawing (a bow and arrow, a loaded pistol, a dagger, a shuriken).

Before initiative is rolled, the player must announce that she intends for her character to draw her weapon quickly. The player may then take some of the skill dice and add them to the Perception die code for purposes of increasing initiative for that round only. The player must leave at least 1D in her skill. If the character wants to make multiple attacks, she subtracts 1D for each attack beyond the first from the number of dice in the skill she’s using before the player moves dice around. She does not take a penalty for the draw.

All attacks by the hero in the same round must be made with the same skill, though the results are determined differently and they all occur at the same die code because the multi-action penalty was already figured in.

Example: A crime fighter wants to smack her arch-nemesis with her shuriken before the villain can draw his weapon. The crime fighter has 4D in Perception and 8D in throwing. She may take up to 7D and add it to her Perception die code to determine initiative. The crime fighter, however, wants to throw two shuriken. After subtracting 1D for the extra attack, she now has 7D in the skill, which allows her to add up to 6D to the initiative roll. She decides to move only 3D. This gives her 7D in Perception to determine initiative and 4D in throwing. Now both the hero and the villain make their initiative rolls.

Once initiative is determined, at the character’s turn in the round, she uses the remaining dice in the skill to determine her accuracy.

=== Ready a Weapon

It takes one action per item to draw a gun, unsheathe a knife, reload a rifle, or something similar. Although this generally does not require a skill roll, the Game Master may require one related to the weapon in question for particularly stressful situations. Additionally, drawing and using the weapon in the same round incurs a multi-action penalty. The Game Master may add further modifiers for attempting to get out an item from a restrictive location or ready an unwieldy weapon.

=== Scale

Occasionally, objects of vastly different sizes get involved in fights. The scale modifier accounts for the fact that bigger items are easier to hit, and usually can take more damage, than smaller ones. Use the accompanying chart as a guide for determining the appropriate value for the two combat participants. Game Masters may further subdivide between levels.

If both opponents are either larger than or equal to a Human or smaller than or equal to a Human, subtract the larger number from the smaller one to calculate the scale modifier. If one opponent is smaller than a Human while the other is larger, then add together the two values.

For most cases, use these rules: If the attacker is larger than the defender, then the scale modifier is added to the combat difficulty and the damage total. If the attacker is smaller than the defender, then the scale modifier is added to the attacker’s combat skill total and the defender’s damage resistance total.

Example: A thief has snuck into a laboratory defended by toy tanks with working weapons. The tanks have a scale value of 6. With the thief ’s scale value of the zero, the scale modifier is 6 (6 – 0). Because the tank is smaller than the thief, the tank gets a +6 to its marksmanship roll, while the thief gets a +6 to his damage resistance total. When the thief attacks the tank, the scale modifier is added to the thief ’s combat difficulty and to his damage total, if he manages to step on it.

In some cases, the object may be large but lightly constructed (such as a parade balloon). At these times, the Game Master should not add the scale modifier to the damage resistance total.

Typically, a weapon’s scale when determining how much damage it does is the same as the person holding it or the thing it’s mounted on. So, a rifle has a scale value of 0, while a full-size tank’s gun has a scale of 10. These would differ if someone targeted just the weapon.

==== Scale

_Example Participant; Size Value_

Small moon 96

Aircraft carrier, star freighter 50

Jumbo jet, space yacht 46

Eight-story building 24

War galley 21

Four-story building 20

Two-story house 14

Longship 12

City bus, tank 10

Elephant 8

Average car 6

Motorcycle, horse 3

Average Human 0

Human child, guard dog -3

Small keg, bread box, house cat, briefcase -6

Fashion doll, rat, laser pistol -9

Action figure, mouse, palm computer -12

Plastic army figure, coin, cred key -15

Ant, computer chip -21

=== Surprise

A hero who surprises her opponent may either act first in the round (if initiative hasn’t already been determined) or gain a +1D or more to her action. Attacks from behind, an ambush, or unexpected sources (such as a companion) make up the most common sources of surprise.

=== Unwieldy Weapon

Melee weapons longer than 60 centimeters, objects that are hard to throw or grasp, ones relying on technology with which the user is unfamiliar, or any weapons otherwise difficult to wield may incur a +5 or more modifier to the combat difficulty The Game Master may decide that such factors as experience, strength, and features of the weapon (such as a well-balanced sword) lower this modifier.
