= Healing

== What’s in this Section

There are many different ways that characters can regain their health. Characters may never get back more than their maximum number of Body Points or Wounds.

== Body Points

=== Natural Healing

The body heals naturally during the course of the day. The more rest characters get, the faster their wounds heal. Using the “Body Points Healing” chart, the character rolls her Physique plus a modifier based on how much rest she’s had that day. A character gets a modifier of +1D on each full day of rest (sleeping, reading, or other sedentary activities). If she is involved in light activity, such as walking or singing, the modifier is zero. However, if most of the day is spent fighting and running, the modifier is -1D. The character receives the Body Points back at the beginning of the next day.

Optionally, the Game Master may require an injured character to complete a period of rest before making the natural healing roll. Use the “Rest Period” chart and the character’s Wound level to determine how long the character needs to wait before attempting the natural healing roll. The Game Master then multiplies the result by 3 to figure out how many Body Points were healed.

=== Skill

Characters can heal others or themselves with some basic field procedures for treating wounds. Such attempts don’t require a medical kit. Simply roll medicine to help an injured comrade, and find the results on the “Body Points Healing” chart. A successful roll heals the character the listed amount. A character using a medical kit may add its bonus to the roll. A character may only attempt to heal a patient once per day. Other characters may also try to help the patient, adding their expertise to the first healer’s.

=== Body Points Healing

==== Medicine or Physique Total: Body Points Recovered

0: 0

1–5: 2

6–10: 1D

11–15: 2D

16–20: 3D

21–25: 4D

26–30: 5D

30+: 6D

== Wounds

=== Natural Healing

A character can heal naturally, but this process is slow. The character must rest a specified amount of time and then can make a natural healing roll: roll the character’s full Physique and find the result on the chart related to the character’s current Wound Level to see if the character heals.

=== Rest Period

==== Level of Wound: Rest Period

Stunned*: 1 minute

Wounded: 3 days

Severely Wounded: 3 days

Incapacitated: 2 weeks

Mortally Wounded: 5 weeks

*Those using Body Points should use this level for characters who have no Wound level.

=== Wounds Healing

==== Natural Healing: Stunned

A stunned wound is automatically recovered after one minute (12 rounds) of complete rest.

==== Natural Healing: Wounded

Critical Failure: Character worsens to Severely Wounded.

2–5: Character remains Wounded.

6+: Character is fully healed.

==== Natural Healing: Severely Wounded

Critical Failure: Character worsens to Incapacitated.

2–5: Character remains Severely Wounded.

6+: Character improves to Wounded.

==== Natural Healing: Incapacitated

Critical Failure: Character worsens to Mortally Wounded.

2–7: Character remains Incapacitated.

8+: Character improves to Severely Wounded.

==== Natural Healing: Mortally Wounded

Critical Failure: Character dies.

2–7: Character remains Mortally Wounded.

8+: Character improves to Incapacitated.

Healing characters can do virtually nothing but rest. Characters who try to work, exercise, or adventure must subtract 1D from their Physique when they makes their natural healing roll. Any character who opts to take it easy and do virtually nothing for twice the necessary time may add 1D to the Physique roll to heal.

=== Skill

Characters can heal others or themselves with some basic field procedures for treating wounds. Such attempts don’t require a medical kit. Simply roll medicine to treat wounds in the field, and find the results on the Assisted Healing chart. A successful roll heals the character up one level: for instance, a successful medicine roll on someone who’s Wounded would bring him back to Stunned. A character using a medical kit may add its bonus to the roll.

==== Assisted Healing

Stunned, unconscious: Easy (10)

Wounded, Severely Wounded: Moderate (15)

Incapacitated: Difficult (20)

Mortally Wounded: Very Difficult (30)

== Medicine Modifier Option

Before the beginning of the technological and pharmaceutical boom, which started in the 1940s, medicine was handled in a crude fashion and ideas such as sterilizing were only beginning to catch on. To reflect this, Game Masters may wish to impose a -5 penalty to the total when attempting to use the medicine skill before the 1940s or in primitive conditions.
