= Fantasy Skill Examples

The “Character Basics” chapter provided brief descriptions of each skill (and you will need to return to that chapter if you need a refresher). When the generic difficulties aren’t enough, look up various skills in this chapter to get even more ideas on the challenge level for using those skills in common situations. Of course, not every possibility has been covered, but this provides a terrific foundation.

== Using the Difficulties & Modifiers

Unless otherwise stated, the listed modifiers are to the difficulty. The minimum difficulty is 1. Modifiers may be cumulative, depending on the situation — the tenser they are, the more important the minutia become.

The associated attributed is listed after the skill name.

=== Extranormal Skills

Descriptions and difficulties for Extranormal skills are found in their own chapters.

=== Combat Skills (Agility, Coordination)

Skills covered: fighting, dodge, marksmanship, melee combat, throwing

Difficulties for these skills are included in the “Combat” chapter. For throwing, see also that skill’s entry in this chapter.

=== Information Skills (Intellect)

Skills covered: cultures, devices, scholar, trading

The Intellect attribute assists characters in finding out how much they know about a certain field, modified depending on the situation. For this reason, one chart of general difficulties can serve most uses of Intellect, trading, and scholar, some uses of devices, and investigation attempts involving researching a topic.

Game Masters can employ the “Information Difficulties” chart in one of two ways: by picking a difficulty based on what the character seeks or wants to recall, or by comparing the skill total rolled to the difficulties (whichever level the character meets or beats is the amount and type of information collected or recollected). Realize that the less well-defined the skill is, the less information the character knows or finds.

One high roll in any of these skills does not necessarily make the character an expert in that field. The roll represents only what the character recalls at the time. A high roll could reveal a specific detail of the information sought, as well as some hints for discovering more of what the character seeks.

Characters may be assumed to have a general knowledge of their home country, culture, and era, including basic geography, famous people, and common etiquette.

*Information Difficulties*

Amount of Information Difficulty

Basic or common information; unconfirmed rumors 5

Theories; generalities 10

Complex concepts; moderately detailed information 15

Professional level; extensive (though not complete) information 20

Cutting-edge topics; extensive information, including peripheral details and extrapolations 30

*Condition Modifier*

Age of information (per century in the past) +5

Closely guarded secret +15

=== Interaction Skills (Charisma)

Skills covered: bluff, charm, intimidation, persuasion

Characters use one of several Charisma-based skills to influence other people that they meet. The typical difficulty is 10, modified based on the dispositions of the characters involved, but a Game Master may base it on a skill roll. See the “Mental Defenses” section for more information on this; suggested difficulty modifiers are listed below.

Die rolls alone should not determine interactions between player and Game Master characters. Game Masters should have their players detail what their characters say and do to before rolling the dice. The better the player acts the role of his character, the greater his chance of success should be, which Game Masters can reflect by allowing up to a +1D modifier to the skill roll.

See also the individual entries in this chapter for bluff, charm (listed with bluff), intimidation (also listed with bluff), and persuasion.

*Using in Combat*

Con, persuasion, and intimidation can enhance a character’s attacks and defenses. The player adds one-half of the difference (positive or negative) between the difficulty and the con, intimidation, or persuasion roll to any one attack or defense attempt (not both) made at Point Blank or Short range. The character must use the benefit from scaring (intimidation), tricking (con), or seducing (persuasion) the target on the same turn as or on the round after the interaction endeavor. The user’s appearance and demeanor can also affect persuasion, con, or intimidation attempts. The more threatening the character looks or seems, the less effective con and persuasion actions are, while intimidation attempts are more effective. Use the “Generic Modifiers” table in the “Game Basics” chapter to decide how much the appearance and demeanor affect the target, if a Disadvantage or Special Ability doesn’t already provide one.

*Interrogation Attempts*

Characters may use intimidation or persuasion to get information out of someone. Use the rules for mental defenses to determine the difficulty and base interaction modifiers. Further modify the number by how important the information is to the target. (See the accompanying chart for suggestions.) A separate intimidation roll to scare the target can complement an interrogation session.

*Mental Defenses*

In general, the resistance difficulty for any interaction skill equals 10. The target cannot actively resist unless he knows that a psychic or interaction skill is being used on him by another character. If the Game Master decides that the target suspects but does not know for certain that someone is attempting to influence him, the Game Master may allow the character to take an action earlier than his turn in the round and roll his mettle or Charisma to generate a new resistance difficulty. Should the character decide to actively defend against mental intrusion or personal interaction, he may devote all of his actions for the round to that task and roll his mettle or Charisma, adding +10 to the score to get the new resistance difficulty. However the interaction resistance difficulty is determined, Game Masters may further modify the number as the situation warrants (such as stress, surprise, or character relationship).

*Interaction Modifiers*

Situation Modifier

Target is friendly or trusting -5

Target is neutral toward character or of equal standing 0 Target is hostile or has superior standing +5

Target is an enemy +10

Target is in weakened position -10

Request is something target would do anyway or target feels is of minor importance 0

Request is illegal or highly dangerous +10

Target is on guard or actively resisting* +10

*Do not include this modifier if you are using the active mental defense described in the “Mental Defenses” section.

*Interrogation Modifiers*

Target … Modifier

Feels information is unimportant -10

Feels information is of minor importance 0

Feels information is important +5

Feels information is very important +10

Would rather die than reveal information +10 or more

=== Observation Skills (Acumen)

Skills covered: search, tracking

Game Masters can rely on these difficulties for situations involving the gathering of information. They can be used as difficulties to beat or as a means of reading the results of a dice toss.

To see if a character notices details of a scene or situation, the Game Master may have the player make a Acumen roll. Unless the characters are actively eavesdropping, searching, tracking, or performing a similar activity (and thus using the search or tracking skills), this passive observance of a scene does not count as an action. Use this chart as a guideline for how much the character notices. If the skill total meets or beats the difficulty, the character gains that much information.

*Observation Difficulties*

Situation Difficulty

Noticing obvious, generic facts; casual glance 5

Noticing obvious details (ex. number of people) 10

Noticing a few less obvious details (ex., gist of conversation) 15

Spotting a few specific details (ex., identities of individuals) 20

Spotting a few obscure details (ex., specifics of conversation) 25

Noticing many obscure details 30 or more

=== Charioteering, Pilotry (Coordination)

See the “Movement” chapter for details on using these skills.

=== Bluff, Charm, Intimidation (Charisma)

Bluff, charm, and intimidation can enhance a character’s attacks and defenses. The player adds one-half of the difference (positive or negative) between the difficulty and the bluff, charm, or intimidation roll to any one attack or defense attempt (not both) made at Point Blank or Short range. The character must use the benefit from scaring (intimidation), tricking (bluff), or seducing (charm) the target on the same turn as or on the round after the interaction endeavor.

The user’s appearance and demeanor can also affect bluff, charm, or intimidation attempts. The more threatening the character looks or seems, the less effective charm and bluff actions are, while intimidation attempts are more effective. Use the “Generic Modifiers” table in the “Game Basics” chapter to decide how much the appearance and demeanor affect the target, if a Disadvantage or Special Ability doesn’t already provide one.

See also “Interaction Skills” for other difficulties and modifiers for these skills.

=== Flying (Agility), Running, Swimming (Physique)

Difficulties for these skills are included in the “Movement” chapter.

=== Hide (Acumen), Stealth (Agility)

The difficulty for a hide or stealth attempt is usually the opponent’s Acumen, search (for hide), or tracking (for stealth), either as a die roll (if the opponent is actively trying to find the object or person) or as a derived value equal to the number in front of the “D” in the opponent’s attribute or skill times 2 and add the pips. For a straight value, use 6.

Game Masters may also opt to add a small creature or item’s scale value to the difficulty, or subtract a large creature or item’s scale value to it.

*Difficulty Condition Modifier*

Heavy rain or snow -3

Dawn, dusk, fog, many trees, large crowd, etc. -2

Night -5

Inattentive observer -5

Dense concealment (thick jungle, crowd of people in costume) -5

Many distractions (party, parade, combat) -5

Attentive observer +6

Open terrain +6

Good lighting +6

Several observers +9

=== Reading/Writing, Speaking (Intellect)

Because the ability to read in the typical fantasy setting is so uncommon, the ability to communicate falls under two skills: reading/writing and speaking. They both use the same charts, but they relate to two different methods of communicating.

First, determine what the character wants to express or understand and how closely the language in which she wants to express it is to her native tongue. Then, compare the difference between the skill roll and the difficulty to decide how close she came. Characters with a specialization in the language they are using who succeed at the skill roll receive a +3 bonus to determining the comprehension level.

Game Masters may provide a small bonus to characters with a specialization of a particular language in one skill when they attempt to use the other skill for that language. For instance, a character with a reading/writing specialization +1D in Elvish and no experience in speaking could gain a bonus of +1 to attempting to say something in Elvish.

The character must have the appropriate skill to use a translation aid. For example, a book cannot help a character attempting to speak a language unless that character happens to also have the reading/writing skill.

*Idea is … Difficulty*

Very simple, consisting of a short phrase 3

Simple; no slang; children’s story 7

Of average complexity; common bard’s tales 12

Complex; slang involved; epic sagas 18

Very complex; technical jargon involved; academic writing 24

*Situation Modifier*

One or two common, basic words -5

Has a translating aid (book, hand signals)* -5

Different dialect of own language 0

Language is derived from common root language (speech or alphabet) (ex., two Humans from different parts of the same world understanding each other) +5

Completely foreign language (speech or alphabet) (ex., Dwarvish has nothing to do with Elvish) +10

Obscure language; reading lips +15

Language is unique to an uncontacted culture, from a dead culture, or unpronounceable by the character trying to understand +20

Language includes many concepts nearly beyond the character’s understanding or experience +25

*Translation aids might provide their own bonuses, which are used instead of this.

*Roll > Difficulty Comprehension Level*

0–2 Gist of idea; most words understood or conveyed properly; word usage seems stilted

3–6 Literal translation; slang expressed/translated incorrectly

7+ Subtle connotations

A character can also use the reading/writing skill to create forgeries. The artist skill might act as a complementary skill in such instances as reproducing illuminated manuscripts. Reduce the amount of time spent on making a particular forgery if the character has repeatedly succeeded at making similar items in the past.

*Forger*

*Item Forged Difficulty*

Unofficial note or correspondence 6

Time required: 10 minutes or more

Signature 12

Time required: 5 minutes

Official document (decree from a king with seal) 18

Time required: 20 minutes or more

Familiarity with Item Modifier

Intimately familiar or has sample -10

Somewhat familiar; has seen it quite often -5

Slightly familiar 0

Have only had it described +5

Guessing blindly +15

Forgery Inspector

Familiarity with Item Forged Difficulty

Intimately familiar 6

Moderately familiar 12

Unfamiliar 18

Completely unfamiliar 24

Situation Modifier

Have sample -5

Item poorly forged* 0

Item well forged* +5

Item superiorly forged* +10

*The Game Master may add the number of points above the forging diffculty to the inspector’s difficulty instead of using one of these modifiers.

=== Scholar, Trading (Intellect)

See the “Information Skills” for difficulties and modifiers related to using this skill.

=== Acrobatics (Agility)

Using acrobatics can also improve many of a character’s climbing, jumping, and running attempts. The Game Master determines the difficulty of the acrobatics stunt. One-half of the difference (rounded up) between the difficulty and the acrobatics roll is added to the complementary skill. The acrobatics attempt and the climbing, jumping, or running try must be done on the same turn.

Instead of adding a modifier to the running or swimming difficulty for particularly challenging obstacle courses, the Game Master may have the hero make an acrobatics roll in addition to a running or swimming roll.

Acrobatics can make a character appear more intimidating. The player may add one-half of the difference (rounded up) between the difficulty and the successful acrobatics roll to her intimidation attempt. The intimidating attempt may be made on the same turn as the acrobatics roll or on the next round.

During a fall, acrobatics may be used to reduce bodily harm. If the character has not already used his turn for the round, he may rely on acrobatics in an attempt to land properly. The character generates an acrobatics total. For every five points over the base difficulty number of 10, the hero reduces the damage total by one point, in addition to a base reduction of one point. The damage total, however, cannot be lower than zero.

*Maneuver Difficulty*

Somersault; pirouette 5

Handspring; cartwheel; handstand 10

Swing over a obstacle 10

Round-off; backflip 15

Vaulting over an obstacle 15

Bouncing off a surface to reach a specific destination 20

Walking up a wall* 30

*The character may “walk” a maximum of her Move in one round; she must have a flat surface to stop on at the end of her turn or she falls and takes damage from the fall.

*Condition Modifier*

flat surface to flat surface 0

Unlimited landing area -3

Limited landing area +3

Almost no landing area +6

Rough or unsteady landing area +3 or more

High surface to low surface +3

Low surface to high surface +6

Slippery surface +3

Strong wind +3

Add a twist of the body (per twist) +3

Performing the maneuver underwater or backwards +3

Performing the maneuver in the air (such as on a trapeze or bars) +9

Performing the maneuver on a narrow surface +6

Note: Characters may combine one or more maneuvers in the same action. In this case, use the difficulty of the most challenging maneuver, add 3 for each additional maneuver (up to five additional maneuvers), and include modifiers as if the complex stunt was one maneuver.

=== Animal Handling (Charisma)

When attempting to get an animal to do a trick, the character must also roll against its mettle roll (the Game Master generates this). Examples of tricks include rolling over, getting into a cage, jumping up, and obeying commands. The character’s animal handling total may be modified by the attitude of the animal toward the character. The success of tricks are determined by a roll of the animal’s attributes or skills.

*Animal’s Attitude toward Character Skill Modifier*

Friendly or trusting +5

Neutral 0

Hostile -5

Mettle >

Animal Handling Result

1–2 Animal looks at the handler in a confused way.

3–6 Animal lies down for one round.

7–11 Animal lies down for two rounds.

12+ Animal snaps at the handler; if hit, the beast will attack the handler until subdued.

=== Artist (Acumen)

The time needed to create a work of art depends on the quality and complexity of a piece. A simple amateur piece may only take a few minutes, while a complex, prize-winning endeavor could require weeks or months. Characters may also use this skill to judge works of art created by others and detect fake artistic pieces. The higher the total is above the creation total for the piece, the more information the judge knows about it (such as flaws, alterations, its creator, and the like).

*Quality of Piece Difficulty*

Amateur 9

Professional 15

Emotionally moving 18

Prize-winning 24

Complexity of Piece Modifier

Simple; has one or two parts -5

Moderate; has a few parts 0

Complex; has many parts +10

Climbing (Agility)

Difficulties for this skill are included in the “Movement” chapter. Note that taking care in climbing and carrying 50% or more of the character’s body weight slows the character down by two meters or more per round.

*Condition Modifier*

Taking care in climbing -5

Less than a 90-degree angle -3

Less than a 60-degree angle -6

Less than a 45-degree angle -9

Prepared for climbing -6

Carrying 25% of body weight +3

Carrying 50% of body weight +6

Carrying 100% of body weight +15

Many handholds -10

=== Command (Charisma)

The command skill governs the act of convincing individuals to comply with specific directions, as well as maintaining morale during group undertakings (such as combat or building large pieces of equipment). This skill is typically used only with the Game Master’s characters, though it can be sometimes attempted with the players’ characters (such situations should be roleplayed first, with a bonus or penalty to the command roll based on how well the group participated in the activity together). A high command roll can complement individual participants’ rolls in a group activity, while a low command roll can impose negative modifiers. It generally requires at least one round of planning to perform effectively.

Characters can use this skill to combine their attacks. One person is designated the leader and makes the command roll. If successful, everyone goes on the leader’s initiative. Participants make their attacks with the hit location modifier (to reflect that they’re aiming for a designated location), but the target resists the combined total of all damage done it. If the command roll fails, determine initiative and actions individually.

*Complexity Difficulty*

Uncomplicated; imprecise 3

Easy; minimal precision required 7

Requires effort or precision 12

Diffcult; requires high degree of precision 17

Requires much effort or extreme precision 22

Requires care and thoughtfulness, or exacting precision 28

*Team Modifier*

All members willing to follow leader’s orders no matter what -20

All members willing to sacrifice life for others -15

Trained together frequently to work as unit -10

Trained together briefly to work as unit -5

Work together regularly, or willing to work together 0

Worked together on a few occasions +5

Seldom work together +10

Never worked together before, or more than half of the members hate each other +15

No interest in working together; all members despise each other; or members can’t communicate with each other +20

=== Contortion (Agility)

The chart below contains sample difficulty numbers for escaping from various kinds of restraints. Modify the difficulty based on the circumstances of the escape, such as the conditions the character works under or specially designed restraints. The character may not use this skill if completely immobilized. If in multiple restraints, the character must make a separate roll for each one. A Critical Failure indicates that the character has pulled a muscle (and he does his Strength Damage to himself). The Game Master decides whether he may try again.

Note that this skill does not substitute for the lockpicking skill. The character may be able to pull his arms over his head to use his hands, but he may not be able to slip out of the shackles unless they are improperly secured.

*Sample Restraints Difficulty*

Ropes 13

Wires, chain 15

Shackles 16

=== Crafting and Repair (Acumen)

Though there are many different kinds of repair skills, they all follow the same principles. The base difficulty to fix or modify any weapon, armor, other equipment, or vehicle is 10. The amount of damage sustained, the character’s familiarity with the item, availability of parts, and complexity of the task can modify the difficulty. The Game Master may require a separate devices roll to determine whether the character can figure out how to repair an unknown item. Destroyed parts must be replaced, which raises the difficulty. Additionally, if a character rushes the job, not only is there an increased chance of failure, but the item could also break again soon after its next use.

A Game Master may allow a complementary use of artist to improve the quality of the item.

*Situation Modifier*

Light repairs/modifications 0

Heavy repairs/modifications +5

Extensive repairs/modifications +10 or more

Previously built or modified the item; intimately familiar with item -10

Has item’s designs -5

Common item 0

Has seen but not used item +5

Has never seen item +10

All parts available 0

Some parts available +10

No parts available +20

Correct tools* 0

Makeshift tools +15

*Tool kits might provide their own bonuses, which are used instead of this.

=== Devices (Intellect)

The devices skill allows the character how to use a strange new piece of equipment. In some cases, no matter how familiar the item is to a character, the item may be of such complexity (such as some gnomish works) that the Game Master always requires a roll.

Characters who want to create new items must first makes blueprints or design instructions for them, using this skill. The more complex the piece, the higher the difficulty and the longer it takes to determine the correct design.

The base difficulty is 10.

*Complexity of Device Modifier*

Simple 0

Average +4

Complex +7

Prototype +10

From a culture with a lower technological level -5

From a culture with a much higher technological level +10

Consists of many complex parts +5

Consists of hundreds of complex parts +10

Has a manual for the device in a language the character can understand -3

*Roll > Difficulty Result*

0–2 Basic idea of what the device can do, but not how to operate it.

3–6 Basic idea of what the device can do and how to operate it; may add the result points bonus to using the device on the next round if the character does not have an appropriate skill to use the device.

7–11 Previous result and may add the result points bonus to a crafting attempt on the device, if proper tools and materials are available.

12+ Previous two results and can design a similar device, if proper resources are available.

=== Disguise (Acumen)

A character’s skill total in creating the disguise serves two related purposes. First, the higher the roll, the less likely an observer will be to question the disguise. Second, the total becomes the difficulty number for Acumen or investigation efforts to see through it. If the investigation check is higher than the disguise total, the disguise has been penetrated.

If at any time while the character is disguised she performs an action inconsistent with the disguise, any observer has a chance to see through it.

Although one character may use disguise on another character, the disguised character must actively work at keeping up the disguise using her own disguise skill or Acumen.

*Condition Modifier*

Specific person +15

Other sex +6

Different race or species +3

Great age difference +3

Much larger build +5

Much smaller build +10

Resembles the disguise already -5

Using skill on another character +6

Using skill unaided +3

=== Gambling (Acumen)

Gambling doesn’t affect games that are purely random, but does influence games with an element of strategy, like poker. All characters make opposed gambling rolls, without spending Character or Fate Points, and the highest roll wins. A character may cheat by using Character or Fate Points on the roll, and the Game Master may give bonuses to rolls for people looking for a cheater or helping the cheater. The Game Master should consider as many “angles” as possible when using the gambling skill, and add these as modifiers to one or more participants’ rolls.

=== Healing (Intellect)

For game mechanics on using healing to treat damage, see the “Healing” chapter. Remember that the typical fantasy setting doesn’t have the same access to medical procedures as they do in modern times. However, folk lore remedies seemed to work much better than in other genres.

*Medical Diagnosing*

*Action Difficulty*

Determine existence of disease or injury 7

Time required: 1 round

Determine toxicity of substance 7

Time required: 1 minute

Determine type of disease, toxin, or injury 12

Time required: 1 minute

Determine medicine, procedure, or antidote required 18

Time required: 1 round to 1 hour

Determine cause 24

Time required: 1 day to 1 week

=== Investigation (Acumen)

When used to research a topic, a separate roll must be made for each source checked.

*Situation Difficulty*

Common knowledge 7

Requires searching through several sources; introductory theories 12

Sources are of varying reliability; cutting-edge information; specific information about harmless individual or event 18

Esoteric information; specific information about dangerous individual or event 24

*Condition Modifier*

Information closely guarded +5

Character unsure of information sought +5

Character knows exactly what information is sought -5

When used to figure out clues from a scene, the base difficulty is 10. The character must use search first to find the clues or evidence (or have them pointed out); investigation helps the character figure out what they mean.

*Situation Modifier*

Information about subject/event is sketchy +15

Information about subject/event is extensive -15

Evidence is fairly clear; many clues; familiar objects with expected use -6 or more

Evidence is only partly clear; several clues; familiar objects with uncommon use, or unfamiliar objects with common use 0

Evidence is obscure; few clues +3

Evidence is unusual or with no apparent significance; uncommon objects with uncommon use +6

Repeatedly commits similar crimes -3 per crime

Distance between crimes (per 80 kilometers) +3

Time between crimes (per 6 months*) +3

*While the crimes may have been committed over a greater time interval, the maximum value for this modifier is +30.

*Roll > Difficulty Result*

0–2 Basic information about the situation (a rope was used, type of weapon).

3–6 Precise information about situation (probable manufacturing origin of evidence, small details about items in room).

7–11 Previous results plus how all items in an area were put to use.

12+ Reconstruction of events from the evidence.

=== Jumping (Agility)

Difficulties for this skill are included in the “Movement” chapter.

*Condition Modifier*

flat surface to flat surface 0

Unlimited landing area -5

Limited landing area +5

Almost no landing area +10

Rough, slick, or unsteady landing area +3 or more

Uphill (more than 30 degrees) +6

Carrying 50% of own weight +6

Carrying 75% of own weight +9

Carrying 100% of own weight +12

=== Know-how (Acumen)

To use this skill to help with an activity covered by another skill (which the character does not have), the character spends the round before examining the situation, performing no other actions, and making a roll of this skill versus the difficulty set for the action. The character gets neither the unskilled modifier nor the preparing modifier. Within the next 30 seconds (six rounds), the character may add the difference between the difficulty and the know-how skill roll to total roll for the attribute dictated by the actual skill required. The character may not use this skill in place of a skill she already has. The Game Master may limit the number of times per hour this skill may be used on the same action.

=== Lifting (Physique)

At the Game Master’s discretion, a player may make a lifting check when his character first picks up an object. (Generally, if the object’s weight would give it a difficulty equal to or greater than one-half of the character’s lifting, rounded up, or the object is being lifted hastily or under stress, the Game Master should require a lifting roll.)

For each round the object is carried, the character makes another check to see if he can continue to carry the object. If he fails the roll, he is too exhausted and must put the object down. If the character is doing anything else at the time (other than walking slowly or talking), continuing to carry the object counts as a multi-action.

*Abridged Lifting Table*

*Weight Difficulty*

1 kg 1

10 kg 3

50 kg 7

100 kg 12

120 kg 13

200 kg 17

250 kg 18

500 kg 23

750 kg 28

1,000 kg (1 ton) 33

1,100–2,000 kg 34-43 (+1 to base of 33 per 100 kg over 1,000 kg)

2,500–10,000 kg 44-59 (+1 to base of 43 per 500 kg over 2,000 kg)

15,000–100,000 kg 60-77 (+1 per to base of 59 per 5,000 kg over 10,000 kg)

The Game Master may further subdivide the lifting chart if desired to include the weights for the difficulties not listed here.

*Lifting Fatigue Modifier*

*Time Skill Modifier*

1–6 rounds 0

7 rounds to 3 minutes +5

3–10 minutes +10

10–30 minutes +15

30–60 minutes +20

Note: After the first hour, the character must make a check once per hour at the same difficulty as one hour. If the character fails the roll, then he must rest for twice as long as he was lifting the weight.

=== Lockpicking (Coordination)

Characters may not attempt to pick locks without some kind of tools (hairpins, wire coat hanger, telekinesis, etc.). Improvised tools do not add to character’s skill roll, but specialized tools will.

*Type of Lock Difficulty*

Simple key lock 6

Complex key lock 12

Combination lock 18

Lock Condition Modifier

Poorly constructed -6

Well constructed +2

Lock diagrams -4

=== Mettle (Charisma)

Mettle is generally used to resist interaction attempts and mentally damaging attacks. See the “Mental Defenses” section earlier in this chapter for details. Characters with this skill may generally use it instead of stamina to resist fatigue, sleep, and unconsciousness, though there may be some situations the Game Master restricts its substitution. See the stamina entry in this chapter for information on difficulties.

Game Master can also use mettle (or Charisma) to determine the reactions of players’ and Game Master’s characters to each other and to their surroundings. The more the Game Master believes that the character should be at ease or frightened, the greater the difficulty. Use the descriptions of standard difficulties to determine the level. This passive application of mettle is not an action.

=== Navigation (Intellect)

The base difficulty is 10.

*Condition Modifier*

No idea which way is north +10

General idea which way is north 0

Familiar with terrain 0

Terrain completely foreign +5

Completely lost +10

Have a compass or similar navigational tools -5

Plotting a way through a simple course 0

Plotting a way through a complex course +6

Plotting a way through a dangerous course +9

Determine exact location +15

*Condition Skill Modifier*

Have a poorly drawn map +1D

Have a sketchy but accurate map +2D

Have a well-drawn map +3D

Have a misleading or purposely inaccurate map

(and don’t know it) -1D

=== Persuasion (Charisma)

Persuasion can also be employed to “pay” another person to behave dishonorably, such as through ignoring duty, looking the other way, or divulging secret information. Success depends greatly on the target. A target who is loyal or wealthy or fears being caught is less likely to accept bribes. Use the difficulties listed under “Interaction Skills” and further modified by such factors as the value of the money, goods, or information offered, the extent of favors given and received, and the target’s attitude toward the bribe.

See also “Interaction Skills” for other difficulties and modifiers for this skill.

*Value of Bribe Modifier*

Less than 50% of what is reasonable +10

50% to 90% of what is reasonable +5

Larger than expected -5

Significantly larger than expected -10

=== Riding (Agility)

When a character first mounts a ridable animal, she must make a riding roll against the creature’s mettle roll (the Game Master generates this). The character’s riding total may be modified by the attitude of the animal toward the character. The character stays in control if she ties or beats the beast’s roll. If she fails, consult the table below for what occurs.

When attempting to get the beast to perform a special maneuver or during events that might frighten it, the character must also roll against the animal’s Charisma or mettle. Examples of special maneuvers include jumping a fence, crossing a raging river, moving faster, or slowing down quickly. (The success of special maneuvers are determined with the animal’s attributes or skills.)

A character attacking from the back of a beast takes a multiaction penalty for having to both control the mount and use their weapon.

*Animal’s Attitude toward Character Skill Modifier*

Friendly or trusting +5

Neutral 0

Hostile or wounded -5

*Mettle > Riding Result*

1–2 Beast stops and refuses to move for 1 round.

3–6 Beast stops and refuses to move for 2 rounds.

7–11 Beast bolts in a random direction for 1D rounds.

12+ Beast bucks rider; rider must make a Moderate riding roll to avoid being thrown off.

=== Search (Acumen)

When used to eavesdrop on or secretly watch an event or another character, the skill total indicates the amount of information gained from the surveillance. Use the “Observation Difficulties” table. A Critical Failure could mean anything from no information obtained to being immediately spotted by the character being observed, depending on the situation.

When searching for a hidden object or person, the difficulty is generally the hide roll used to conceal the target. Otherwise, the base difficulty is 5, modified by the table below.

See also “Observation Skills” for more difficulties and modifiers for this skill.

*Situation Modifier*

Character knows target’s exact location 0

Character knows target’s approximate location +5

Character has vague information about the target or its location +15

Character has only general idea of what she’s looking for; searching for small objects +20

Character has no idea what she’s looking for; searching for obscure or tiny objects +25

Searching for microscopic objects* +30

*Might not be possible without special equipment or abilities.

=== Sleight of Hand (Coordination)

The difficulty for a sleight of hand attempt is usually the opponent’s Acumen or search, either as a die roll (if the opponent is actively watching for tricks) or as a derived value equal to the number in front of the “D” in the opponent’s attribute or skill times 2 and add the pips.

*Situation Modifier*

Watchful target; few distractions +9

Observant target; light crowd +6

Suspicious target +3

Challenging act (such as palming an apple) +6 or more

Unobservant target; target constantly jostled; major distractions -9

Confused or distracted target; crowded conditions; minor distractions -6

Simple act (such as palming a tiny object or sliding a hand into one’s own pocket unnoticed) -6 or more

=== Stamina (Physique)

Game Masters may allow a character to make a multi-action stamina roll to complement a strenuous activity, such as lifting or running. The difficulty equals 5 times the current fatigue modifier. The character may add one-half (rounded up) of the difference between the successful stamina roll and the difficulty. The strenuous activity still receives the fatigue modifier.

Whenever a character fails a stamina roll, she is fatigued; all actions are at -1D for every stamina check failed until the character rests for as long as she exerted herself.

Characters can still continue if they are fatigued, until they fail a third stamina check. At this point, the character is completely exhausted and must rest for twice the amount of time that she exerted herself to remove the penalty.

To avoid the effects of a toxin (inhaled, ingested, or absorbed) or disease (encountered in any manner), a character makes a stamina roll. Several factors figure into the difficulty of the attempt, including the deadliness and dosage of the poison in question. For example, a fatal bout of botulism has a difficulty of 9, while a killing dose of deadly nightshade has a difficulty of 42. Characters may attempt to counter toxins once per day.

Game Masters might also call for stamina rolls against falling asleep or unconscious. This generally does not count as an action, though the Game Master should award a bonus to the skill total when the character devotes her action to keeping awake. Resisting sleep is a difficulty of 5 per hour beyond the normal awake time, modified by environmental factors (too warm or too cold, noise level, etc.). For unconsciousness caused by wounds, see the “Wound Levels” table in the “Damage” chapter.

=== Streetwise (Acumen)

Streetwise helps characters get around urban environments. Some situations call for seeking out those living outside the local law, while others can be handled through upstanding citizens. Generally, the modifiers are the same for each situation, but the Game Master should adjust them depending on the circumstances. It is possible, though generally unlikely, that a character would be well-liked by both upstanding residents and local criminals.

Example: In a village, a character would find it easier to gather information about a particular person (and thus the city-size modifier would be -15 instead of +15), but he might have a harder time getting someone to trust him enough to tell him about it (making the tolerance modifier +15).

*Seeking … Difficulty*

Things that are usually easy to find

(ex., directions to the nearest police station) 4

Things that require discretion or careful investigation (ex., asking if the local law is straight or crooked) 7

Risky services; finding illegal and well-regulated items (ex., finding out an appropriate bribe for the local law) 14

Services of unusual skills; finding dangerous or carefully controlled items 18 (ex., seeking a fence or a safecracker)

A specific criminal in hiding; finding items whose possession means immediate imprisonment 28

*Size of City Modifier*

Large city (a few hundred thousand citizens) 0

Small city (several thousand citizens) +5

Town (several hundred citizens) +10

Village (a few hundred citizens) +15

Amount of Law Enforcement or Tolerance of Residents Modifier

Martial law or no tolerance for criminals or outsiders +15

Criminal activity overlooked as long as it’s discreet; slight tolerance of outsiders +10

Criminal activity overlooked as long as it’s not dangerous to the general public; tolerance of outsiders +5

Criminal activity overlooked as long as it’s not dangerous to the local government; outsiders welcome 0

Anarchy; outsiders given same respect as residents -10

*Reputation of Seeker Modifier*

Never been to the location; no contacts; not trusted by local underworld or residents +10 or more

Rarely visited; only passing knowledge of how the local underworld operates +1-9

Minor contacts; knows what to avoid; criminals or residents have no reason not to trust character 0

Somewhat favorably known by local underworld or residents; several contacts -1–9

Well-known and liked by underworld or residents -10 or more

=== Survival (Acumen)

Character can rely on survival to figure what to eat, where to sleep, how best to deal with native dangers, and other information needed to get out of wilderness situation alive. The character can also use survival to locate herbs, plants, and animals of special healing or mystical value. (Use streetwise for help in urban situations.)

*Situation Difficulty*

Woods 4

High mountains, ocean (near floor) 12

Desert, ocean (near surface) 15

Polar region 18

Different, non-Earth-like dimension 25

Situation Skill Modifier

Has been to this location frequently +1D

Has been to this location within the past 10 years 0

Has never been to this location -1D

=== Throwing (Coordination)

A character’s ability to grab projectiles out of the air is enhanced by the throwing skill. The difficulty of catching an object is typically the thrower’s throwing roll. If the thrower wants the catcher to get the object, and thus takes care to throw well, reduce the thrower’s skill total by 9.

Combat difficulties for this skill are included in the “Combat” chapter.

=== Tracking (Acumen)

The base difficulty is 10 or the target’s stealth roll, if the target is actively trying to hide her trail. Characters can also use tracking to shadow a target. A shadowed character can attempt to spot the shadow with a search roll versus the shadowing character’s tracking roll. Game Masters may opt to include relevant hide modifiers to the tracking roll, if the shadow is being cautious.

*Condition Modifier*

Trail is a day old +3

Trail is a few days old +6

Trail is a week old +9

Tracking during inclement weather +6

Soft dirt, mud, snow -3

Grassland 0

Forest, thin crowd +3

Rain forest, dense crowd +6

Desert, arctic wasteland, hard surface +9

Number of people being tracked (for every 2 people) -3

Tracking a wheeled vehicle -6

Per additional vehicle -3

=== Traps (Intellect)

To install a trap, use the chart to modify the base difficulty of zero. The Game Master may award one-half of the points above the difficulty as a modifier to future disarm rolls. This represents the character adding a few extra improvements to the base design.

A pressure plate trigger releases the trap when a small piece of metal or wood (about a quarter-meter square) is stepped on or pushed. Pressure plates may be on the floor or wall. A tripwire trigger releases the trap when a wire, cord, or other material attached to the tripwire is walked through or broken. A switch could be a cord yanked, an outcropping pulled, a lock turned, or something similar. A hand-triggered trap requires that someone watch for the victim to come within the range of the trap’s effect and, once that happens, activate the trap.

When a character triggers a trap, use its speed total and compare it the initiative total of those affected by the trap. Those who have a higher total than the trap are allowed to generate a full-defense dodge total, if they so desire.

Once it’s the trap’s turn in the initiative, compare the trap’s combat attack total to the defense totals of its intended target or targets. (The combat attack total takes into account range.) The trap affects those whose defense totals it meets or beats, up to the number of targets it can affect.

To disarm a trap, the character first needs to find an access to it, which means applying the search skill if the trap’s concealed. Once found, the character rolls her traps against this chart, modified by how well it was originally installed. Traps enhanced by spells must have their spells negated first before the character can disarm the trap. Concealing a trap (including disguising wires, covering a pit or pressure plate, or placing a false trap) requires using the hide skill on it (or selecting an appropriate difficulty for a Game Master-created trap).

*Trap Modifier*

Pressure plate trigger (per plate) +2

Tripwire or switch trigger (per tripwire or switch) +1

Hand triggered 0

Speed (initiative total; per 5 points) +1

Combat attack total versus target (per 5 points) +2

Single part (open pit, poison on a handle) 0

Multiple release portals for gas, arrows, etc. (per additional portal) +2

Multiple targets (per additional target; increases pit opening by 1 meter-square area) +2

Additional damage (spikes in pit, more push behind arrows, per additional 1.5 meter drop) (per additional 1D*) +3

Use existing structure (door and frame, nearby saplings) 0

Add to structure (clockwork mechanism, false walls) +3 or more *This represents falling damage for pits.

*Disarm Situation Modifier*

Have blueprint or map -5

Have an idea about the kind of trap -5

Have no idea about the kind of trap 0

No special trap set-up* 0

Good trap set-up* +5

Superior trap set-up* +10

*The Game Master may add one-half (rounded up) of the number of points above the trap setting difficulty to the disarmer’s difficulty instead of using one of these modifiers.

*Sample Traps*

_Dart Trap:_ Triggered by stepping on one of three plates placed across a hallway, this traps shoots four darts (two each; damage 1D each; speed 10; combat difficulty 15) at the first two adventurers in the area. Trap difficulty: 21.

_Lock Trap:_ When a character attempts to pick the lock and is successful, a large poisoned needle (damage 5D; speed 15; combat difficulty 10) shoots out and stabs the thief. Trap difficulty: 20.

_Pit Trap:_ The floor falls away from beneath the characters, dropping them into a large dug-out area about 4.5 meters high (damage of 3D from fall). The pit opening is about two meters on a side. Trap difficulty: 13.
