= Psionics

This chapter covers the ability to manipulate the forces of the mind for extraordinary effects. The Psionics skills are available only to characters with the Psionics Extranormal attribute.

An extensive, though finite, list of individual psychic skills is provided herein. While many psychics have only one strong psychic talent, and most will have no more than a few such talents, characters may select and develop as many of these skills as they desire and the gamemaster will allow. Remember that the list herein is not all-inclusive. Game Masters should feel free to develop other psychic skills for use in their campaigns.

=== Obtaining Access to Psionics

There are only two ways for a player’s character to get psionic abilities. The first is to put dice in the Psionics attribute and skills at character creation, which costs the same as obtaining other attributes.

The other way is to obtain the Game Master’s permission after play has begun. If the player can come up with a “reason” for the character to learn or gain psionic abilities (such as they were latent or were acquired through a strange accident) and the Game Master agrees, then the player’s character may get them. The cost to get the initial 1D in Psionics is 20 Character Points. After that, it is 10 times the number in front of the “D” to improve this attribute by one pip. Players must still purchase Psionics skill pips separately. If appropriate for the reason that the character got the ability (such as having a teacher open latent talents), a character may learn one pip in one skill (or more, with the Game Master’s permission) when the character first purchases Psionics after character creation.

Game Masters are discouraged from allowing characters to have multiple Extranormal abilities, but it is possible, especially if the character has several Disadvantages that show up frequently in each session.

=== Learning and Improving Psionics Skills

Psionics skills may be learned between adventures, like regular skills. It is even possible to specialize in a certain area of an Psionics skill, if the concept is well-explained and the Game Master approves.

The cost for a Psionics skill, in Character Points, equals twice the normal cost for gaining or improving a normal skill. This cost is doubled again if a teacher — simply another psionic with the skill at a higher level — is not available to instruct the character. A character may learn or improve one Psionics skill after each adventure.

=== Using and Resisting Psionics

The character rolls a skill attempt (the activation roll) and if she beats the difficulty set by the Game Master, she succeeds with all the concomitant benefits. To continue using the skill, some skills allow a maintenance roll, at a lower difficulty than the activation roll, while others require that the psychic to re-activate the ability.

Psionicists can push their Psionics attempts when times are rough, using Character Points and Fate Points; perform Psionics actions while multitasking (unless they have to go into a trance); and anything else one might expect for any standard skill.

A target can actively resist a Psionics skill attempt, assuming the target is aware of it. See the “Mental Defenses” sidebar in the “Example Skill Difficulties” chapter for more details.

=== Backlash Option

At the Game Master’s option, characters who roll a Critical Failure with an abysmally small total become disoriented and lose all of their actions in the next round.

=== Delay

Few characters can use their psychic abilities repeatedly in a short period. Should the character fail an attempt, the difference between the difficulty and the skill roll becomes the time in minutes before the psionicist can use that skill again. Delay is always a minimum of one minute, and it’s measured from the moment a psionicist quits using his talent to the time he can try once more. If it involved a Critical Failure, that is the number of minutes before the character may employ that Psionics skill at all. This makes it difficult for a character to give someone the evil eye more than once during a combat, or to read the minds of everyone in a meeting over the course of a few minutes.

Game Masters may opt to ignore this rule, but there should be some penalty for overusing the psychic ability, such as automatic feedback or increasing difficulties.

=== Psionics Modifiers

Difficulties and modifiers specific to each psychic skill are included in each description. These generic and optional modifiers can further affect the difficulty, generally trading a negative effect on the character for a lower difficulty or a higher skill total. Note that none of these modifiers are required to use any Psionics skill, but they can help.

Community: Unless the Game Master rules otherwise, psychic characters may help each other, using the game mechanics in the “Related Skills” section in the “Game Basics” chapter as guidelines.

Components, Incantations, and Gestures: Psychic talents only require the power of the brain, although a person can have a psychological dependency on a certain sort of item to use his gift more effectively. A dowser, for example, could require a dowsing rod to do his work. Someone else might feel a need to have a crystal ball or read tea leaves or rub a lucky rabbit’s foot. This is a psychological crutch, which can be reflected in the character concept as the Advantage Flaw (R3): Minor Stigma Disadvantage, but it has no bearing on the difficulty of the psychic attempt. Nonetheless, Game Masters may allow a modifier to the Psionics skill total modifier per type of additional part. There is a limit of one component, one incantation, and one gesture per skill attempt. See the accompanying charts for the skill modifiers. This can be combined with a concentration modifier.

*Components*

*Component is…*

*Skill Modifier*

Ordinary, easily obtained (rock, dirt, tree branch)

1

Very common, easily purchased or traded for (match, wooden board, candle)

2

Common, but must be purchased for reasonable cost (lighter, inexpensive clothing, oil, incense)

3

Uncommon (rare in some places, common in others) (gun, computer chip, prescription medicine)

4

Very rare (rare in most places or expensive) (valuable gem, precious metal, rare drug, exotic herb)

5

Extremely rare (near-priceless gem, uranium, plutonium)

6

Unique (King Tut’s burial mask, a prototype weapon)

7

*Gestures*

*Complexity*

*Skill Modifier*

Simple (point finger, toss herbs, flip switch, etc.)

1

Fairly simple (make circles with finger, etc.)

2

Complex (action difficulty 11)

3

Very complex (action difficulty 15)

4

Extremely complex (action difficulty 19)

5

Challenging and extremely complex (action difficulty 23)

6

Also will offend most seeing it

1

*Incantations*

*Complexity*

*Skill Modifier*

A few words or sounds

1

A complete sentence

2

A complex incantation (artist difficulty 11)

3

Litany (artist difficulty 15)

4

Complex formula (artist difficulty 19)

5

Extensive, complex elements (artist difficulty 23)

6

Also in a foreign tongue and character must have one pip in that language specialization

1

Also must say it very loudly

1

Also will offend most hearing it

1

Concentration: The character spends time preparing herself before releasing her psionic ability. For each round in which the character concentrates strictly on her upcoming action (with or without performing related incantations or gestures), the player may add a bonus of +1 to the activation total or the first maintenance total, or split between both (the bonus must be split as whole numbers). Additionally, add the number of rounds in concentration to 6 to get the willpower difficulty, modified by the distractions listed in the chart on the next page, which the character rolls at the end of the concentration time. If the character fails the willpower roll, the psychic attempt fails. A Critical Failure on the willpower roll indicates that the psionicist takes any feedback associated with the skill use, even though it didn’t work.

Example: Four rounds of concentration gives a +4 bonus with a willpower difficulty of 10.

The player must specify, before having her character concentrate, which Psionics skill the bonus will affect and how it will affect that skill. The bonus cannot be transferred to another skill.

*Concentration Distractions*

*Level of Distraction*

*Modifier**

Completely isolated chamber

-2

Isolated, but some distractions (trees, birds chirping, pictures, white noise)

0

On a park bench, with a few passers-by

4

In a room with a few other people who are being quiet

6

Alone in a booth at a sparsely filled restaurant

8

Alone at a table in the middle of a sparsely filled restaurant

12

Alone at a booth in at a busy hour, in a telephone booth, with many people passing by

14

At a restaurant booth with a few other people who are being quiet

16

Packed ballroom

18

*Modifier to willpower difficulty.

Countenance: Psionicists’ bodies can undergo changes due to side effects of their psionic talents. Some go pale or even blue with a lack of blood flow to their skin, others shake uncontrollably or foam at the mouth, still others get bulging eyes or swollen lolling tongues. The physical shell can react in unpredictable ways to the effects of extrasensory perception. The corresponding chart lists modifiers to the Psionics skill difficulty.

Nothing unreal can happen here: eyes can’t glow red, or flames billow forth from someone’s nostrils, except as a psychic illusion that only the victim can see. The drawback to an illusion is that, no matter what the victim’s perceptions and predispositions were before the fact, after the image is seen, the victim is forever firmly convinced that the psychic is an inhuman monster. Only those already endowed with a psychic or magic ability can accept that image for what it truly is.

*Countenance*

*Change in Appearance*

*Difficulty Modifier*

Noticeable (gray pallor, foaming)

-1

Extreme (convulsions, psychic image)

-2

Feedback: For every -2 to her damage resistance total, the character receives a +1 to the Psionics skill total. Neither protective gear nor any type of Special Ability may defend against feedback. The damage resistance modifier drops at a rate of one-half of a roll of the character’s Physique per day, with the decrease occurring at the beginning of a new day.

Link to Target: When an astral form, empath, or telepath wishes to seek out a specific person, the relationship to that person can affect how easy it is to get in touch with the person. Include the Link to Target Psionics skill total modifier when using the relevant skill (see accompanying table). Note that this is different than an astral anchor in that the character and her target need not have been in recent contact. The Game Master can also use these modifiers for honing in on specific items (as with far-sensing) or extending the range of certain skills that otherwise have a limited range (such as strike or healing).

*Link to Target*

*Relationship Years Known*

*Skill Modifier*

Constant influence (parents, grandparents, spouse, old friends) 10+ years

5

Recent influence (friends, roommates, old enemies) 5–10 years

3

Newer influence (friends, acquaintances) 1–5 years

2

Sporadic influence (on-and-off relationships) variable

2

New acquaintances 2–6 months

0

New faces/only just met, but have talked for a while (like at a party)

-2

Personal sight and name recognition (have met in person briefly)

-3

Distant sight and name recognition (like celebrities never met in person)

-5

Only a name or only a face

-8

Complete strangers and not of the same species

-12

Physical Contact: Close proximity to the target can enhance the Psionics use. Physical contact requires a successful grab attempt for an unwilling or moving target and no special action for a willing or inanimate target. Physical contact with living beings adds 2 to the Psionics skill total and +1 to the skill total for nonliving things.

Range: Unless otherwise noted in the skill’s description, use this chart to determine the maximum distance to which the ability can reach. Ranges are given in kilometers. For every +1 added to the skill difficulty, the range may be increased by one kilometer.

*Skill Adds**

*Max Range*

0-2 pips

4

1D

10

2D

15

2D+1

25

2D+2

40

3D

60

For every +1 pip beyond +3D, add another 60 kilometers to the range.
