= Special Abilities

Before allowing players to create characters with special abilities, the Game Master may decide that certain special abilities require speciﬁc limitations on them or disadvantages on the character.

Any special ability that gives a bonus to the die roll or the skill total also allows the character to use that skill as if trained.
Bonuses received from taking multiple ranks of the same special ability are added together.

Skills gained with a special ability are not improved when that special ability is improved.
Instead, they are increased as a normal skill.

Unless stated otherwise in the special ability, it does not count as an action for the character to get the bonus from a special ability.
However, except for such automatic abilities as Natural Armor or Combat Sense, the character must state that she is relying on the special ability or she does not receive the bonus.

== Special Abilities

=== Accelerated Healing (3)

The character gains a +1D per rank to his Strength for all natural healing attempts, and a Critical Failure is treated as 1, rather than having a negative effect on the die roll.

=== Ambidextrous (2)

The character is equally adept with her right or left hand.
She may perform an action with each hand in the same round, and, though she takes the multi-action penalty, she receives a +1 per rank to each skill total.
The actions must involve the hands and each action must require only one hand.
If the character performs only one hand-related action in a round, she does not get the bonus.
Some skills that characters could employ with either hand include brawling, sleight of hand, firearms, throwing, lift, artist, forgery, and the map-making aspect of navigation, though, of course, not every task covered by each skill is relevant.
A character may take multiple ranks of this Special Ability for two pairs of hands and multiple ranks for each additional manipulative limb.

=== Animal Control (3)

This gives the character the ability to control one particular species of animal, bird, or insect.
The character gets a +10 bonus to her survival: animal handling total for that species.
She must generate a survival: animal handling versus the Knowledge or willpower of the animal (more than one animal can be targeted, although this is a multi-action). If the character gets a high enough success (Game Master’s decision), the animal is controlled for a number of minutes equal to the survival: animal handling skill total times 10.
A controlled animal serves its master faithfully, even sacrificing itself on her behalf.
The Special Ability has a range of sight or voice.
The character may gain one more species for each rank.

_Note_: A swarm of insects counts as one animal, as does a school of small fish.
Any creature with a Knowledge die code of less than 2D could be considered an animal, unless the Game Master says otherwise.

=== Armor-Defeating Attack (2)

When a character with natural weapons (the character’s fists, claws, teeth, etc.) attacks someone protected by armor, this ability negates the Armor Value, up to +1D per rank.
The character must specify how the attack negates the armor: an acidic mist slips through any openings, nanotech claws reach directly to the flesh, and the like.
There should be at least one type of armor that is unaffected by this.

=== Atmospheric Tolerance (2)

The character can breathe one form of atmosphere (gas or liquid) that would be lethal to most other characters.
A character may not have more than one rank in this ability, but he may have different versions for different atmospheres.

=== Attack Resistance (2)

The character is highly resistant to a certain type of attack.
She gains +1D per rank to her damage resistance total against this type of attack.

*Energy Attacks:* Resistant to blasts of heat, fire, electricity, radiation, light, cold, and so on, but not the ability to survive in extremes of such environments.

*Extranormal Attack:* Resistant to damage from any Extranormal based (such as Metaphysics) attack.

*Mental Attacks:* Resistant to mental harm from any source.
It does not provide protection against interaction attempts.

=== Attribute Scramble (4)

The character can adjust an opponent’s (or a friend’s) attributes temporarily.
She gains the scramble skill at +1 per rank in a single version of this Special Ability (it is a Perception skill, described only here), which she also can increase as a normal skill.
The scrambler must pick as her focus either physical or mental attributes, though never Extranormal, Funds, or Special Abilities.
(Physical attributes encompass Agility, Strength, and Mechanical.
Mental attributes include Knowledge, Perception, and Technical.) She only may do both by taking this Special Ability once for each version.

When she goes after a target with an brawling roll, she may choose (as a multi-action) to also perform a scramble attack versus a roll of her target’s willpower or Knowledge.
(This is not an action for the target.) No close combat attack is necessary for a willing target, though the willpower or Knowledge must still be made.
However, the act of scrambling still counts as an action.

If the scrambler’s total is higher (not equal to), she may shift her target’s attribute points around, within certain limits.
The close combat attack does no damage.

She may increase one or more related attributes by a number equal to the amount she takes away from other related attributes — but she may not decrease or increase any one attribute by more than 2D (6 pips). The change lasts for a number of rounds equal to the difference between the scramble attack and the target’s willpower or Knowledge.
A character who has been adjusted cannot be scrambled again until the original adjustment wears off.

=== Blur (3)

The character can appear indistinct to the naked eye or most visual aids (binoculars, cameras, etc.). Commonly, a character with this Special Ability will only be spotted out of the corner of the eye.
This adds 1 to the character’s dodge, sneak, and hide totals, as well as +1 to all default search, investigation, and attack diﬃculties against the character that the blurring character is not actively trying to defeat.
(These modifiers are per rank in this Special Ability.) On the character’s turn, she may automatically become blurry, without taking an action, and remain so until she chooses otherwise.
Blurring also makes it diﬃcult for the character to hold a conversation with others.

=== Combat Sense (3)

The character can sense danger.
She is never surprised.
Rather, she and her attacker must determine initiative as normal.
Even if the attacker still goes before the character does, any combat modifier from the surprise is reduced by 2.
A character may not have this ability more than once.

=== Confusion (4)

The character can hamper the thoughts of those he comes into physical contact with, at will.
He gains the confuse skill at +1 per rank (it is a Perception skill, described only here), which he can increase as normal.
As a multi-action with a brawling attack, he may also perform a confusion attack versus his target’s willpower or Knowledge.
(This is not an action for the target.) If his total is higher (not equal to), the target is confused.
Characters may not play cards (if the Game Master is using game-enhancing cards with the adventures) or spend points, and they receive a +5 diﬃculty modifier to even simple actions for a number of rounds equal to two times the rank of this Special Ability.

=== Darkness (3)

The character can project a field of darkness around himself, adding +5 per rank to the diﬃculty of any sight-based skill totals.
The field extends in a half-sphere around the character with a radius equal to one meter per rank.
The field can be maintained for a maximum of one minute per rank before dispersing.

=== Elasticity (1)

The character can stretch, elongate, and compress his body, allowing him to expand his height or become so narrow he can pass through keyholes, cracks, or any other opening he could normally see through.
It takes one round or more to slip through small openings, depending on their depth.
The character gains +1 per rank to acrobatics, dodge, or sleight of hand totals, in addition to con totals when using that skill to disguise his own appearance.

=== Endurance (1)

The character has great endurance, and gains a +3D per rank to Strength or stamina checks when performing taxing physical tasks (such as holding one’s breath underwater for a long period or running a long distance).

=== Enhanced Sense (3)

One of the character’s five senses is heightened to abnormal levels.
The bonus to the skill total received depends on the sense: sight is +1; hearing is +2; touch, taste, or smell are +3.
The bonus is per rank and applies to all skills related to the sense.
To have multiple enhanced senses, this Special Ability must be taken at least once for each sense.

=== Environmental Resistance (1)

The character is resistant to extremes of heat, cold, and pressure and gains a +3D per rank to Strength or stamina checks to resist ill effects from these environmental conditions.
The character is not resistant to heat or cold attacks, as these come and go too quickly for the Special Ability to provide protection.

=== Extra Body Part (0)

The character has an extra limb or organ.
If external, these may be secondary arms or legs, a tail, or some more exotic bodily addition, such as fins, tentacles, or antennae.
If internal, the parts are organs such as extra eyes, hearts, or mysterious glands.
Unless specified by a Disadvantage or Limitation, the extra parts are included in the hero’s body tastefully.
Additionally, except in cases where the character has an Enhancement or another Special Ability that uses this one (for example, Extra Body Part: Tail and Natural Hand-to-Hand Weapon: Tail), the extra part is nonfunctional.
A character may have only one rank in this Special Ability, but she may have multiple versions to represent multiple additional organs or limbs.

=== Extra Sense (1)

The character can detect something that a normal Human cannot, such as changes in pressure, seismic activity, radiation fluctuations, and so on.
She gains a +1D to her search rolls in attempting to detect the specific energy or environmental change and +1D to her investigation rolls in figuring out source or other relevant information.
The Game Master may also allow a +1 skill total bonus to other activities that would benefit from whatever the extra sense can detect.
All modifiers are per rank in this Special Ability.

=== Fast Reactions (3)

The character gains +1D per rank to his Perception when determining initiative, and, for up to three times during the adventure, he may receive one additional action for one round.

=== Fear (2)

The character can provoke fear in those who can see or hear him.
He gains a +1 per rank to all intimidation totals and combat defense diﬃculties against those so affected.
The willpower or Knowledge difficulty to resist a Fear attack is 15.

=== Flight (6)

The character can fly, either by nature or by virtue of having wings.
The character’s flying rate equals his base Move times 2 times the number of ranks.
The flying/0-G skill is required to maneuver.

=== Glider Wings (3)

The character can fly by drifting with air currents, provided there is suﬃcient wind.
The Game Master decides how much wind there is available and how fast it moves the glider.
Characters with this Special Ability need the flying/0-G skill to control their passage.
A character may not have this ability more than once.

=== Hardiness (1)

The character can take damage better than normal.
She add 1 per rank to her damage resistance total against any type of damage.

=== Hypermovement (1)

The character is extremely fast, adding +2 meters per round per rank to her base Move rate, which in turn affects all other types of movement.

=== Immortality (7)

The character is immortal, though she will grow older, at a decreased pace compared to the rest of her species.
If she is reduced to zero Body Points, she doesn’t die.
She will not go unconscious or bleed to death (as mortally wounded characters do), but she will not heal without psionic or similar special aid or the Accelerated Healing Special Ability — her arms could be blown off, her abdomen eviscerated, or whatever.
She may perform only the most minimal of physical actions, such as squirming, and some actions may be impossible.
She may rely on her Agility for initiative purposes only.

There should be one particular set of circumstances whereby the character will die forever.
These sets of circumstances should not be too unusual — killed directly by an Extranormal blast, drowning decapitation, and so on are all good examples.

A character may not have this ability more than once.

=== Immunity (1)

The character is highly resistant to disease and poisons and receives a +1D per rank to Strength or stamina checks when determining whether he has contracted an illness or suffering from ingested poisons.

=== Increased Attribute (2)

Some extraordinary training or physiological trait allows the character to gain +1 bonus per rank to all rolled totals related to that attribute.
(For Strength, this also includes the damage resistance total and Strength Damage.) A character may have multiple ranks of this Special Ability, as well as multiple versions of it.

_Note_: To get another rank in this Special Ability after character creation costs 4 times the number in front of the “D” of the attribute that it affects plus the number of ranks currently in the Special Ability.
(This is instead of the normal cost to increase Special Abilities.)

=== Infravision/ Ultravision (1)

The character gains the ability to see in the dark using either infravision or ultravision.
Infravision allows the character to see changes in heat, while ultra-vision enables the character to make the most of the available light.
Each provides a +2 per rank in a single version of this Special Ability to sight-based rolls while in dim or dark conditions.
Obviously, extreme heat or bright light (including daylight) prevent this Special Ability from working.

=== Intangibility (5)

The character can reduce his physical density to virtually zero for one minute per rank.
During that time, his damage resistance score against physical and energy attacks is +3D per rank, but his movement rate is halved.
An intangible character can pass through solid objects, providing they do not contain wards or other spells of protection designed to repel passage of this nature.
He may not pass through energy or electrified barriers.
While intangible, the character cannot carry any object along (including clothing), nor can he attempt any physical attack.
It takes a full round for a character to become intangible or solid, during which he can do nothing else.
The character must spend at least one minute solid before attempting intangibility again.

=== Invisibility (3)

The character can become transparent.
This adds 1 per rank to the character’s dodge, sneak, and hide totals, as well as +1 per rank to all default search, investigation, and attack diﬃculties against the character that the invisible character is not actively trying to defeat.
Additionally, no character may take an action to “spot” the character unless the Game Master feels there is suﬃcient provocation, such as brushing against others or removing something in a crowded area.
The invisibility covers the character’s basic clothes only — not any gear she’s carrying, or anything she picks up.
Also, remember that the character is transparent when invisible — she can’t hide things behind her back.

=== Iron Will (2)

The character is highly resistant to all interaction attempts and mental attacks.
The character gains a +1D per rank to all willpower rolls and +2 to the standard diﬃculty of any such attempts against this character.

=== Life Drain (5)

This ability allows the character to drain attribute pips, Body Points, or Wounds from his target.
The character must choose one set of attributes to target, either physical (Agility, Mechanical, Strength), mental (Knowledge, Perception, Technical), Wounds, or Body Points.
For example, most vampires drink blood, and thus lower Body Points, while succubi target the soul and so weaken mental attributes.
The player must specify in what manner the character drains these attributes (biting the neck, hypnosis, or another means). It should involve some sort of successful attack result (either physical or mental).

When the character wishes to employ Life Drain, he makes an attack on his target using the relevant skill.
For every four points over the target’s defense roll, the character drains one pip per rank off each of the target’s relevant attributes or three points per rank from the character’s Body Points or one Wound for every two ranks.
(Remember that there are three pips in each die.)

If any of the target’s attributes or Body Points ever go to zero (or the character reaches the Dead Wound level), the target goes into a coma.
She may try once per day to wake up by making a successful Moderate stamina or Strength roll.
She regains one attribute point (to each attribute affected) every hour after the attack.
Body Points and Wound levels return at the normal rate.

For each attribute pip the character drains, he may add one pip to any attribute in his chosen category.
He would get one Body Point for each Body Point drained or one Wound for each Wound drained.
Life-Drained attributes and unused Body Points or Wounds disappear at a rate of one pip or point per hour.

A character may have multiple ranks of this Special Ability, as well as multiple versions of it.

=== Longevity (3)

The character lives longer than the average Human.
Often, this Special Ability has a Flaw attached that governs what the character must do to maintain his life.
The character should gain peripheral bonuses during game play because of his “longer outlook.” A character may not have this ability more than once.

=== Luck, Good (2)

The character is blessed with unusually good luck.
Once per adventure, a character with Good Luck can receive one of the following benefits just by asking for it: action, breakthrough, haste, or second chance.
See the “Luck Benefits” sidebar for details on each of these options.
Calling upon one’s luck does not count as an action.

Good Luck can only be declared once per rank during a particular adventure, but it may be declared at any time, and it cannot be cancelled by any other effect.
A character may have up to two ranks of this Special Ability.

=== Luck, Great (3)

A character with Great Luck can call on one of the following benefits once per adventure per rank: action, alertness, breakthrough, haste, hero, opponent fails, or second chance.
See the “Luck Benefits” sidebar for details on each of these options.
Calling upon one’s luck does not count as an action.

If the character has not used his Great Luck during an adventure and something really disastrous happens, the Game Master may choose to counteract the effects and temporarily “burn out” the character’s Special Ability — that is, the character’s Great Luck has been used up for the adventure.
Usually, this is used when the character does something stupid or the player is the victim of incredibly bad luck — die rolling, not the Disadvantage — and something “stops” the effect.
This is a “last ditch,” Game Master-controlled effort when circumstances get out of control.
It is also a nice thing for inexperienced roleplayers to have — just in case they do something they really shouldn’t have, they get another chance.
Example: The character’s mission is to turn off the power at a nuclear plant or it will explode and destroy the city that’s conveniently downwind.
Unfortunately, the character takes too long fighting the minions of the bad guy who set the plant to overload, and, according to the rules, the whole city should go up in a radioactive fireball.
The character is too late.
The Game Master might choose to have the character be really lucky — the villain was bluﬃng, and there’s really more time on the clock than anyone thought, or the power plant begins a long meltdown procedure instead of exploding.
In any case, the character’s Good Luck is gone for this adventure (his luck ran out), but he has a chance of averting disaster.

As with Good Luck, the character may have up to two ranks of this Special Ability.

=== Luck Benefits

*action:* Add 2 to all of the character’s skill or attribute totals for the round.

*alertness:* When the character calls upon this benefit, he gains a special “sixth sense” outside of all other rules and roleplaying situations that will help him to spot a previously unseen item, character, or clue selected by the Game Master.
The benefit does not confer omniscience, however — and the Game Master can select her own time for having it come into effect.
It is normally used to allow a character to spot something he missed in a previous search, something that is important to the adventure.

*breakthrough:* Add 1D to any one skill die code in which the character has no additional pips or dice (in other words, a skill in which the character is untrained). The benefit also eliminates the unskilled modifier for using that skill.

*haste:* Gain one additional action for one round.

*hero:* Receive one bonus Fate Point, which must be used on an action immediately after requesting it.

*opponent fails:* After an opponent or enemy has completed an action against the character, this benefit may be called upon to cancel the effects entirely.
The opponent’s action is then wasted, and play continues.
This benefit may not be used to cancel an action that is not directed at least partially at the lucky character.

*second chance:* Using this benefit allows the character to attempt any action she has just tried again, from the very beginning.
Relying on this benefit, however, may not be used to negate “bad choices” — the action performed must be performed again — nor does it allow the character to “get back” Fate Points, Character Points, or cards (if used) spent on the original action.
The character merely gets another chance, immediately following the first attempt, to perform the action again.
All effects from the first attempt are negated.

_Luck Notes_

A character may have up to two ranks each in Good Luck and Great Luck.
This Special Ability can be taken with the Bad Luck Disadvantage — sometimes really good things happen, sometimes really bad things happen.

=== Master of Disguise (3)

The character has a natural talent for disguise.
She gains a +5 per rank bonus to con totals when using that skill to disguise herself and a +1D bonus per rank to any con, intimidation, or persuasion actions while in that disguise.

=== Multiple Abilities (1)

The character has multiple minor abilities that improve a few different tasks.
All bonuses are added to the skill or attribute total, not to the die code.
The bonuses should be fairly limited in their applications, pertaining to specific uses of particular skills (like specializations do), but there can be several of them for each selection of this Special Ability.
The maximum total bonus for each rank is +4.

Example: A character could have “eyestalks” that give him a +1 bonus to Perception or search totals that would negate surprise, the ability to focus his ears on particular types of noises (+1 bonus when listening for particular sounds), and fingers that are sensitive to subdermal motion (+1 bonus to sleight of hand against safes with moving tumblers).

=== Natural Armor (3)

The character has plates, toughened skin, scales, or something similar.
His own surface adds 1D per rank to his damage resistance total to physical (not mental) attacks and contact poisons, corrosives, or similar materials.

=== Natural Hand-to-Hand Weapon (2)

The character has some sort of natural weapon — such as claws, pincers, bone spikes, or stinger — that add 1D per rank to his Strength Damage when determining his damage with the natural weapon.
The character uses brawling to attack, unless he can detach the weapon from himself or (in the case of a super-scientific weapon) its exists separately.
In these latter cases, the character employs melee combat to wield it.

=== Natural Ranged Weapon (3)

The character has some sort of natural ranged weapon, using missile weapons (for solid objects) or firearms (for energy, gas, or chemical projection or for solid projectiles in cybernetics or super-science weapons) to target it.
Long range equals 20 times the number of ranks in this Special Ability times the character’s Strength, lift, or firearms (as appropriate) in meters.
The damage for physically enhanced projections is the character’s Strength Damage plus 1D per rank, while the damage for all other types of blasts is 3D per rank.
The projection must have a visible effect (such as bone shards or a glowing ray) and it may not do mental damage.
Note that, regardless of the nature of the projection, there are no additional effects from this type of Special Ability unless an Enhancement allows otherwise.

=== Omnivorous (2)

The character can gain nourishment from any organic substance (though she is not immune to poisons). She can also chew through just about any organic substance with no adverse effects to her teeth or jaws.
A character may not have this ability more than once.

=== Paralyzing Touch (4)

The character can freeze her target with the merest touch.
When she makes a brawling attack, she may, instead of doing damage, paralyze her victim, who remains that way until he makes a successful Knowledge or willpower roll against the brawling skill total.
He may attempt to do so once per round; the only other actions he may take are mental-based ones and Extranormal (such as Metaphysics) or Special Ability ones that do not require movement.

_Note_: Characters who are heavily armored or covered will be harder to hit.
The Game Master needs to decide how much skin is exposed and adjust the attack diﬃculty accordingly.

A character may not have this ability more than once.

=== Possession, Limited (8)

The character can possess the body of a living creature or a corpse.
The character must be within three times the rank of this Special Ability in meters of the target in order to take possession.

Possessing a corpse doesn’t require a roll, but it does take an action.
Possessing a living being involves making a Knowledge or willpower check by the possessor versus a standard interaction diﬃculty (see the “Mental Defenses” sidebar on page 85 for details). Exceeding (but not equalling) the diﬃculty means the target has been possessed.
The target can actively defend if she is aware of the potential danger.

To gather knowledge about his host body’s life, the possessing character must generate a successful investigation total against the target’s Knowledge roll (this does not count as an action for the target). Information the possessor gains depends upon the level of success achieved; see the accompanying chart for details.

With Limited Possession, the character does not gain control of the new form.
Instead, he must use persuasion, intimidation, or other interaction skills to convince his host to do what he wishes.
Exiting a host body is commonly a simple action.
As long as the possessing character exits before the host dies, he simply moves on to his own or another form.
Killing a possessing spirit usually involves taking it completely by surprise with a killing blow to the host form or using a spell to force it to remain in the body until it can be slain.

=== Possession, Full (10)

The character can possess the body of a living creature or a corpse.
This works in the same way as Limited Possession, save that the possessing character gains her new form’s physical attributes (Agility, Mechanical, Strength), retains her own Extranormal and mental attributes (Knowledge, Perception, and Technical), and gains complete control over the new form.

> Possession Knowledge Chart

Result Points* Needed Knowledge Attained

0 Basic information: target’s name, age, base of operations

1-4 More personal information: target’s job, financial status, any current schedule

5-8 More in-depth personal information: identities and backgrounds of family, friends, lovers

9-12 Very personal information: secrets, private likes and dislikes, and so on

13 Everything there is to know

*Result points equal the difference between the investigation total and the target’s Knowledge roll.

=== Quick Study (3)

The character has an uncanny ability to learn new skills and improve old ones, limited to one attribute.
He always learns new skills as if he had a teacher (even if he doesn’t), and he can improve skills he already knows at a cost of one Character Point less than normal.
This Special Ability applies to specializations as well as combines very well with the Age Disadvantage, if the character is young — he is a prodigy, and that’s why he’s learned his starting skills so quickly.
This Special Ability can be taken once for each attribute.

=== Sense of Direction (2)

The character has a good sense of direction.
He gains +1D per rank to navigation and search rolls.

=== Shapeshifting (3)

The character can manipulate the shape, color, and overall appearance of her body, though mass and body compositions remain the same.
The character must chose a specific creature to emulate, gaining one form for every three additional points spent on this Special Ability.
At six ranks in this ability, the Game Master may allow shifting among one class of creatures (such as birds or furniture) as long as all forms chosen for previous ranks were within the same class.

Body Points, Wounds, and the Knowledge attribute remain unaffected by this Special Ability, but the dice in the Agility, Mechanical, Strength, Perception, and Technical are redistributed to match the new form.
The minimum Mechanical and Technical for non-humanoid forms is 1D, because the shapeshifter retains some memory of these attributes.
Additional dice in skills above the base attribute score remain the same, though the total dice in each skill changes to reflect the adjustments in the base attribute.
Likewise, not all skills will be usable in the new form.

Attribute dice can also be used to include Special Abilities in the new form.
One attribute die can be spent to gain one rank in one Special Ability or to get a +2 skill total bonus (split among up to two skills). The Game Master may allow a larger skill total bonus or more skills to fall under the bonus if the desired effect is particularly narrow (such as a bonus for a single sense).

For an example of how Shapeshifting can work, see the accompanying sidebar.

Shapeshifting may be done at will, though a Limitation may force it to be triggered by stress or environmental factors.

If shifting voluntarily, the character must generate a willpower total of 11 to bring about the change, and a second total to turn back again.
Each change takes one full round in which the character may do nothing else.
Failure at the check means the transformation does not occur, and the character cannot try again for at least an hour.

It is highly recommended that the hero comes up with some typical forms and their game characteristics before beginning play.
The new form need not exactly resemble a “typical” version of the emulated creature or object.

> Shapeshifting Example

Mark is playing a wereleopard.
He chooses Shapeshifting, specifying that he will only change from Human to leopard and back again.
The Game Master decides he’ll gain one rank of the Hypermovement Special Ability (+2 to the movement rate) and +2 to all search totals that require smell when in his wereleopard form.

Mark’s character has 18 attribute dice arranged thusly:

AGILITY 2D+2

STRENGTH 3D

KNOWLEDGE 2D+2

PERCEPTION 2D+2

MECHANICAL 3D+1

TECHNICAL 3D+2

When he changes into wereleopard form, Mark’s character has the following attribute values, the total of which has been lowered by 2D because of the bonuses:

AGILITY 4D

STRENGTH 3D+2

KNOWLEDGE 2D+2

PERCEPTION 3D+2

MECHANICAL 1D

TECHNICAL 1D

=== Silence (3)

The character can move in complete silence.
He gains +2D per rank to all sneak checks and a +1D per rank when attacking from behind.

=== Skill Bonus (1)

Skill Bonus represents a natural talent (a character with the Charismatic group might be “friendly and outgoing”), a particular knack (a character with the Ranged Combat group has a “keen eye”), years of devotion to a profession prior to beginning adventure, or the result of an extended life.

The character chooses a group of three related skills in which he gains +1 to the skill total of any action performed with those skills (or specializations of that skill). The skills need not be under the same attribute.
The character may or may not actually have adds in those skills, and the Game Master must approve the fact that they are “related.”

Some examples of skill groups include: Acting: bargain, con, persuasion Acute Balance: acrobatics, climb/jump, sneak Athletics: lift, running, throwing Charismatic: command, con, persuasion Close Combat: brawling, melee combat, dodge Investigative: investigation, search, streetwise Leadership: command, intimidation, persuasion Photographic Memory: languages, scholar, investigation Observant: gambling, investigation, search Ranged Combat: firearms, missile weapons, throwing

Players may substitute other related skills for the ones listed in the groups above, or create their own groups as long as there is a common thread and the Game Master approves the grouping.

Three specializations may replace one general skill, getting a +1 for three different specializations.

Example: In the Close Combat group, a character might replace melee combat with three specializations — melee combat: knives, melee combat: swords, and melee combat: clubs.
While this means the character gains no bonus for “general” melee combat activities (such as using an improvised weapon), he does have a more “detailed” group.
This may be done for up to all three skills in the group, choosing six specializations instead of two skills or nine specializations instead of three skills.
Additionally, the character acts as if trained in these skills even if he doesn’t have any additional pips in them, and so does not get the unskilled modifier.
This Special Ability does not affect the cost of improving the related skills.

Gamemasters may allow a higher bonus for fewer skills (such as a set of two skills where one gets a +1 bonus and the other gets a +2 bonus, or a +3 bonus to a set of three specializations). However, the bonus per rank may total no more than +3.

At each additional rank, the player may increase the bonus by +1 for three of the skills affected by this Special Ability.
A character may have different versions of this ability for different groups of skills, though the skills in each group may not overlap.

=== Skill Minimum (4)

The character can select three related skills unaffected by any other sort of Special Ability and the character will always gain a minimum total of 3 times the number before the “D,” even if she rolls a Critical Failure.

Example: If the player selects persuasion, con, and intimidation (all interaction skills) for her character, all of which she has at 4D, and she generates a less than 12, the total automatically becomes 12.
That is the character’s minimum total.

The player may not select Skill Minimum for any skill that has any other Advantage or Special Ability tied to it.
Also, the skills must be related in some way (see the Skill Bonus Special Ability for information on related skills). The character may only select general skills, but the specializations underneath that general skill are affected as well.
This Special Ability may be selected only once for each group of skills.

=== Teleportation (3)

The character can move instantly to another place up to 10 meters per rank away.
The character must see her destination clearly.
In combat, this action takes an entire round.
The character may take along whatever she can carry.

=== Transmutation (5)

The character can alter his substance to something else, while retaining his form (such as a man who turns to stone). Characters with this ability may only shift into one specific substance, which the player must specify when his character gets the Special Ability.
Generally, this substance gives the character distinct advantages.
The player may select up to 4 points (not ranks) in other Special Abilities that relate to the chosen form, per rank in this Special Ability.
(Thus, two Transmutation ranks means 8 points in other Special Abilities.) Natural Armor, Hardiness, and Environmental Resistance are common ones.

=== Uncanny Aptitude (3)

This Special Ability is similar to the Skill Bonus Special Ability in that some sort of bizarre ability gives the character added bonuses to certain actions.
However, instead of selecting a group of skills that the character gains a bonus to, the player and the Game Master work out circumstances where these abilities come into play.
For instance, a character might gain a +1 bonus to all Agility-related skill totals when in sunlight.

A character may have several variations of this ability, reflecting different bonuses.
Each variation could have several ranks, with the bonuses adding to each other.

=== Ventriloquism (3)

The character can throw her voice up to three meters away per rank.
No skill roll is required to do this, but if it is part of a trick attempt, she receives a +2D bonus per rank to con and persuasion rolls.

=== Water Breathing (2)

The character can breathe water and will not drown under water.
She gains +1D per rank to all swim rolls because she doesn’t need to worry about drowning.

=== Youthful Appearance (1)

The character looks much younger than she actually is and receives a +1D per rank to persuasion or con.
In general, characters should not look more than 10 to 20 years younger than they are, regardless of the number of ranks, though Game Master discretion and common sense should rule here.

=== Special Ability Enhancements

Enhancements allow special abilities to be somehow more than the typical version.
Each enhancement may be taken more than once for each special ability, either altering the ability in similar though distinct ways or, for some, through stacking the effects.
The cost of the enhancement adds to the associated special ability’s total cost (base cost plus the cost for additional ranks).

*Additional Effect (1):* The special ability produces a useful, though minor, side effect that is a natural extension of the power.
The more useful the side effect, the greater the number of ranks.
Some examples include a skill bonus when using the ability, doing residual damage (such as reﬂection with Natural Armor or radiation with Natural Ranged Weapon), or adding functionality to an Extra Body Part.

*Bestow (see description):* The character may share her special ability with a certain type of target: sentient living, non-sentient living, or nonliving.
The player must chose which group when including this enhancement.
The cost of this enhancement equals one-half (rounded up) of the special ability total (base cost plus additional ranks cost plus enhancement costs). She may only use her special ability on herself and on members of her target group with a multi-action penalty.
Some special abilities will require better stories concerning how the character can manage sharing them than others (such as Youthful Appearance or Ambidextrous), while others may not have this enhancement (such as Longevity or Immortality). The target has control over the use of the Bestowed special ability for as long as the Bestowing character allows.
A character may only have one rank in this enhancement, but she may have multiple versions of it.

*Extended Range (3):* The factor used to determine the range of the character’s special ability is increased.
Every rank of this enhancement allows the player to add one half of the ranks in the special ability (rounded up) to the factor when determining the range.
Thus, to increase the range factor by half the ranks costs three, by the ranks in the ability costs six, by 1.5 times the ranks costs eight, and so on.

_Example:_ The range for Natural Ranged Weapon is 20 times the number of ranks in the special ability times the character’s Physique or lifting in meters.
With two ranks of Extended range, the range would now be 20 times twice the number of ranks in the special ability times the character’s Physique or lifting.

*Magically Empowered (4 for 1 rank; 5 for 2 ranks):* The special ability comes from a magical source — a feature of the character’s species, a result of the character’s parentage, a means of explaining a mysterious ancient artifact, and so on.
A special ability provided by a spell does not need this enhancement, nor does Natural Magic require it.
An item created for a character because of the Equipment Advantage would.

Two ranks exist for this enhancement.
At Rank 1, with a cost of four, the power with this enhancement has a magical power source, but it is not truly magical in nature.
If it does damage, protecting special abilities or magical spells of any defensive nature can defend against it as normal.
It can act on characters in astral form, spirits, and other magical creatures or magical items not affected by normal harm.
It does harm to those beings and items at one-half of its damage total, before modiﬁers and rounded down.

If it provides protection, it defends at one-half its total, before modiﬁers and rounded down, against magical blasts or special abilities possessed by demons, ghosts, and other magical or spiritual beings.

In both cases, these bonuses are in addition to the normal applications of the special ability.

At Rank 2, with a cost of ﬁve, the power with this enhancement is magical in nature.
If it does damage, protecting special abilities only defend at one-half their die code (rounded down) against its attacks, but the Enhanced special ability can be completely protected against by other magical special abilities (protecting special abilities with this enhancement; spells that protect against magical attacks; and protective versions of Natural Magick). It can be used against characters in astral form, spirits, and other magical or spiritual creatures or magical items not affected by normal harm.
For both cases, this is in addition to the regular manifestations of the special ability.

If the special ability with this level of enhancement provides protection to the character, it can defend against normal and magical powers (attacking special abilities with this enhancement; damage-dealing spells; and attack versions of Natural Magick; special abilities magical in nature possessed by demons, ghosts, and the like).

To include this enhancement with a special ability in an item, the item’s special ability should also have the limitation Burn-out (R1), item can be lost or stolen.

*Multiple Targets (2):* The character may use the special ability more than once per round without incurring a multi-action penalty.
For each rank in this enhancement, the character gains one additional use of the special ability.
This adds to any other bonus actions provided by a power; it does not multiply it.

=== Special Ability Limitations

These limitations can be associated with special abilities, restricting their functionality and reducing their total cost (base cost plus the cost for additional ranks plus any enhancements — not the per rank cost). For example, the total cost of two ranks of Iron Will in a game where special abilities are uncommon is four, and in a game where they are common, the cost is three.

Limitations may not lower a special ability’s total cost below one, and all limitations must have some sort of effect on play — just like disadvantages.
Each of a character’s special abilities may have more than one of each limitation, as they can either describe similar but distinct negative situations or, in some cases, stack the effects.

*Ability Loss (3 for 1 rank; 4 for 2 ranks):* The character temporarily loses his special ability at regular intervals or, when the special ability is used, he loses the ability to use a common skill in which he has experience (that is, additional pips or dice). Examples include: a character who cannot shapeshift when the sun is out; a character who cannot use his natural weapons on a particular day of the month or during a certain phase of the moon.
The character is aware of what the circumstances are that will cause this.
For an additional point and additional rank, the character must undergo some sort of (fairly simple) procedure to regain his ability or skill use.
A special ability may only have a maximum of two ranks in a single variation of this limitation, but a character may have it multiple times for different special abilities, circumstances, or combinations of special abilities and skills.

*Allergy (3 for 1 rank; 4 for 2 ranks):* The character has a fairly minor allergy.
Exposure to a fairly common substance (smoke, sunlight, particular food, etc.) causes the character to lose all critical success rerolls until the condition is removed.
For an additional point and additional rank, the effects are worse, and the character loses all actions due to coughing ﬁts, watering eyes, or similar discomfort until she can get away from the allergen.
A special ability may only have one rank in this limitation, though it may have several different Allergies.

*Cybernetics (0):* An artiﬁcial limb or organ provides the character’s special ability.
As a cybernetic improvement is impossible to accidentally drop or remove, this limitation has no cost.
Characters may have only one rank in it.

*Burn-out (1):* See the Disadvantage by this name for suggestions that could also be applied to a special ability.
The more likely the burn-out, the greater the number of ranks in this limitation.
A special ability may have multiple variations of this limitation, representing different triggers for the Burn-out.

*Debt (3):* Someone (or, more likely, some entity) gave the character the special ability.
See the Debt (R3) disadvantage for suggestions.
A special ability may only have one rank in this limitation.

*Flaw (1):* All difficulties associated with using the special ability are increased by +2 per rank.
The greater the rank associated with this Flaw, the greater the difficulty modiﬁer.

*Minor Stigma (3):* The character cannot use the special ability without performing the “proper rituals” before or after (someone with a natural weapon who must sketch an image of his intended victim before hunting him down; a shapeshifter who must be puriﬁed by his cult after killing someone). A special ability may only have one rank in this limitation.

*Others Only (2 for 1 rank; 3 for 2 ranks; 4 for 3 ranks):* The character may not use the special ability himself; he may only allow others to use it.
The value of this limitation depends on how many groups of “others” he can use it on: For two points and one rank, the character may affect sentient living, non-sentient living, or nonliving targets.
For three points and two ranks, the character can affect only two of the three groups.
For four points and three ranks, the character can affect only one of the three groups.
This limitation may not be taken more than once per special ability.
Additionally, like the Bestow enhancement, some special abilities may require valid reasons before the Game Master will allow the limitation’s inclusion.
Some abilities, such as Immortality and Longevity, may not have this limitation.
The target who gets the special ability has control over its use as if she actually had the ability, for as long as the giving character allows.

*Price (1):* The character must fulﬁll certain obligations in order to use the special ability.
Perhaps when using Water Breathing, the character must remain in the water for at least 24 hours for every 24 hours out of it or suffer -4 modiﬁer per rank in this limitation to his damage resistance total for changing environments so quickly.
Alternatively, there could be a Character or Fate Point fee of three Character Points per rank or one Fate Point per rank in the limitation.

*Restricted (1):* The special ability is hindered in a way not covered by any other limitation.
The more restrictive the situation, the greater the number of ranks in this limitation.
For instance, a Natural Weapon (either kind) may only be useful against certain items.
A special ability may have multiple variations of this limitation, each representing a different restraint.

*Side Effect (2):* One of the character’s special abilities has some sort of annoying side effect that appears with its use, such as constant whistling, a continuous glow, or a terrible stench.
Add 4 per rank to the difficulty of all stealth attempts when the special ability is in use, as everyone can ﬁgure out she’s coming.
This will also affect interaction attempts, adding at least a +1 per rank to the difficulty.

*Singularity (1 per special ability):* The character may use only one of a group of two or more special abilities each round.
It does not take an action to switch special abilities.
He may change the special ability in use at the beginning of his turn in a round, and he may rely on the chosen special ability until the next time he changes it.
For a second rank (and an additional one point per special ability), it does take an action to switch special abilities.
A special ability may not have more than two ranks in this limitation and all special abilities in the same group must have this limitation at the same rank.
Not all of a character’s special abilities need be in the same Singularity group.

*Super-science (2):* The special ability is contained in a piece of equipment — such as a gun, a staff, or a ring — developed through a technological means not readily available and certainly experimental.
The item could be lent to another character or taken away with a successful grab and used by someone else, though at a +5 to the difficulty.
On a critical failure, the item malfunctions and requires repair.
Unless combined with the Burn-out limitation, a destroyed item may be recreated in a number of days equal to the total cost of the special ability (including all ranks, enhancements, and limitations). Characters who wish to have special abilities in their cybernetic implants may not take this limitation, as cybernetic implants are impossible to remove without serious and extended effort.
(See the Cybernetic limitation, described herein.)
