= Spells

This chapter offers a sampling of spells created with the spelldesign system in the previous chapter. Use them as is, or be inspired by them in making new spells. See “Characteristics of a Spell” for details on how to read the spell listings.

All spells were designed with a starting Spell Total of zero, so basic and additional aspects were added to the effect’s value.

=== Cantrips

==== Aid

Skill Used: Conjuration

Difficulty: 5

Effect: 16 (medicine skill of 5D+2)

Range: Touch (0)

Speed: 0

Duration: 1.5 seconds (+1)

Casting Time: 1 round (-4)

Other Aspects:

Other Conditions (-3): Physical contact with creature; may only be used on living creatures

By touching an injured being, the magic user can use this cantrip to heal harm as if he had 5D+2 in the medicine skill.

==== Charm

Skill Used: Alteration

Difficulty: 5

Effect: 18 (charm skill bonus of +4D)

Range: Self (0)

Speed: 0

Duration: 1 minute (+9)

Casting Time: 1 round (-4)

Other Aspects:

Gesture (-2): Smile and make a gesture of welcome or admiration

Unreal Effect (-9): Difficulty to disbelieve is 13

Other Conditions (-2): May only be used on humanoids who understand the caster’s language and can hear the caster

With a smile and a friendly gesture, the caster improves his charm skill by for one minute. (If he no charm skill, add the bonus to the character’s Charisma attribute.) As this is an illusory spell, if the intended target of the charm disbelieves it, any effect the charm attempt had wears off immediately.

==== Heighten Attribute (Template)

Skill Used: Alteration

Difficulty: 3

Effect: 6 (+1D bonus to one non-Extranormal attribute)

Range: 1 meter (0)

Speed: 0

Duration: 5 rounds (+7)

Casting Time: 1 round (-4)

Other Aspects:

Gesture (-3): Mime an activity using a skill that falls under the attribute to be heightened (complex, action difficulty of 11; examples: sleight of hand for Coordination, lifting for Physique)

This cantrip gives the target a bonus of +1D to one of his attributes for 25 seconds, or five rounds — as long as he doesn’t move more than a meter from the spot on which he received the bonus.

Note that this is only a template for a spell and not an actual spell, because it does not indicate in the description which attribute is affected. The caster must specify which attribute and skill to mime before learning the spell (which takes one round).

==== Meal

Skill Used: Conjuration

Difficulty: 4

Effect: 1 (1 kilogram of bread and water)

Range: 0

Speed: 0

Duration: 4 hours (+21)

Casting Time: 1 round (-4)

Other Aspects:

Components (-6): A plain, cloth napkin (common), a small metal cup (common)

Gestures (-2): Wave hands several times over napkin and cup (fairly simple)

Incantation (-2): “Fill these with food and drink.” (sentence)

With this cantrip, the mage creates a simple meal of bread and water, which sticks around in the system long enough to be digested and actually provide nourishment.

==== Open Lock

Skill Used: Apportation

Difficulty: 5

Effect: 18 (compare to difficulty to open lock)

Range: 1 meter (0)

Speed: 0

Duration: 1 round (+4)

Casting Time: 1 round (-4)

Other Aspects:

Components (-3): Large metal key (common)

Gesture (-2): Mime opening the lock with the key (fairly simple)

Incantation (-2): “Open, Lock, and reveal your secrets.” (sentence)

Other Conditions (-1): Physical contact with lock

To cast this cantrip, the mage touches the lock with one hand while, with the key held in it, miming opening the lock with the other hand. After reciting the incantation, he touches the lock with the key and turns the key. If the spell effect’s value is equal to or greater than the difficulty of the lock, it opens. If there are any traps or wards on the lock, they are not circumvented by this spell! Note that this spell works on any kind of mechanical lock.

=== Alteration Spells

==== Countermagic

Skill Used: Alteration

Difficulty: 19

Effect: 29 (compare to skill total of spell countering)

Range: 60 meters (+9)

Speed: +9

Duration: 1 round (+4)

Casting Time: 1 round (-4)

Other Aspects:

Concentration (-1): 3 seconds with mettle difficulty of 7

Gesture (-1): Wave hand through air as if wiping away something (simple)

Incantation (-3): “Your hold is broken!” (sentence, said loudly)

Other Conditions (-4): One spell, which the caster must specify when casting this spell

The caster concentrates on the spell he wishes to counter, waving his hand and shouting the required incantation. The effect’s value plus the result points bonus are compared to the skill total used to create the targeted spell. If the countermagic number is equal to or higher than the target spell’s skill total, the spell is broken.

==== Countermagic Ward

Skill Used: Alteration

Difficulty: 11

Effect: 29 (compare to skill total of spell countering)

Range: Self or a target within 1 meter (0)

Speed: 0

Duration: 1 round (+4)

Casting Time: 25 minutes (-16)

Other Aspects:

Charges (+6): 6 charges, with a ward to go off when a spell “hits” the target

Concentration (-4): 10 minutes with mettle difficulty of 10

Focused (+6): On target

Gesture (-1): Wave hand through air as if wiping away something (simple)

Incantation (-3): “Let no spell touch me!” (sentence, said loudly)

Similar to the countermagic spell, this spell gives the target a general protection against spells. It is triggered by a spell “hitting” the target. Up to six spells can be countered in this fashion. The effect’s value plus result points bonus are compared to the skill total used to create the targeted spell. If the countermagic ward number is equal to or higher than the target spell’s skill total, the spell is broken. Regardless of the success of the ward, one charge is lost.

==== Deadly Bullet

Skill Used: Alteration

Difficulty: 10

Effect: 18 (+4D in damage)

Range: 100 meters (+10)

Speed: +10

Duration: 5 rounds (+7)

Casting Time: 1 hour (-18)

Other Aspects:

Component (-11): Black obsidian (uncommon, destroyed), dart (common)

Feedback (-3): -3 to damage resistance total

Focused (+5)

Gesture (-1): Rub the tip of the bullet on the stone (simple)

Incantation (-1): “Darkness of death.” (a few words)

Variable Movement (+4): +2 accuracy bonus

This spell uses a piece of black obsidian to increase the deadliness of a bullet. The mage utters a short, dark phrase while gently stroking the tip of the bullet across the stone. The darkness travels into the bullet, draining the stone of its pigment.

To release the spell, the caster inserts it into an appropriate gun within five rounds of casting the spell. The gun’s user must generate an marksmanship total, adding a +2 bonus for the increased accuracy of the spell, against the combat difficulty for the target. The target must be within range of the spell, or the bullet merely does its normal effect. The target takes an additional 4D in damage in the round the bullet hits and for the next four rounds. The spell ends if the target moves beyond the spell’s range.

==== Deadly Dart

Skill Used: Alteration

Difficulty: 11

Effect: 18 (+4D in damage)

Range: 100 meters (+10)

Speed: +10

Duration: 5 rounds (+7)

Casting Time: 40 minutes (-17)

Other Aspects:

Charges (+1): 1 charge

Components (-11): Black obsidian (uncommon, destroyed), dart (common)

Feedback (-3): -3 to damage resistance total

Focused (+5)

Gesture (-1): Rub the tip of the bullet on the stone (simple)

Incantation (-1): “Darkness of death.” (a few words)

Variable Movement (+4): +2 accuracy bonus

This spell uses a piece of black obsidian to increase the deadliness of a dart. The mage utters a short, dark phrase while gently stroking the tip of the dart across the stone. The darkness travels into the dart, draining the stone of its pigment.

To release the spell, the caster throws the dart within five rounds of casting the spell. He generate an marksmanship total, adding a +2 bonus for the increased accuracy of the spell, against the combat difficulty for the target. The target must be within range of the spell, or the dart merely does its normal effect. The target takes an additional 4D in damage in the round the dart hits and for the next four rounds. The spell ends if the target moves beyond the spell’s range.

==== Drain Toughness

Skill Used: Alteration

Difficulty: 12

Effect: 24

Range: 40 meters (+8)

Speed: +8

Duration: 1 minute (+9)

Casting Time: 15 seconds/3 rounds (-6)

Other Aspects:

Components (-16): Blood of a great cat (very rare, destroyed), funnel (common, destroyed)

Gesture (-1): Pick up an item and pull it closer (simple)

Incantation (-2): “Weaken and perish before my hand.” (sentence)

Caster focuses magical energies into a funnel, with the large end facing the target. When activated, the funnel pulls energy from the target, and sends it to the source of the spell. The spell itself is not visible, but it can be felt. It requires a marksmanship roll to focus on a target.

Compare the spell effect’s value to a roll of the target’s Physique. Multiply the difference by 3. This is the target’s negative damage resistance total modifier. If this number is greater than 3 times the die code in the target’s Physique (ignore the pips), the target is unconscious for eight hours. The negative modifier vanishes after one minute.

The caster receives one-half (rounded up) of the negative damage resistance total modifier as a positive modifier to her damage resistance. When the spell wears off after one minute, the resistance total bonus goes with it.

==== Fear

Skill Used: Alteration

Difficulty: 19

Effect: 30 (intimidation skill bonus at +6D+2)

Range: 100 meters (+10)

Speed: +10

Duration: 2.5 minute (+11)

Casting Time: 1 minute (-9)

Other Aspects:

Components (-5): An item owned for at least a month by the target (very rare)

Gesture (-1): Point item at target (simple)

Incantation (-1): Frightening words (a few words)

Unreal Effect (-8): Difficulty to disbelieve is 13

To cast the spell, the mage first needs something belonging to her target — his comb, his watch, a lock of his hair. Mutter a few words of power, point the item at the target, and watch the fun. This spell gives the caster an intimidation skill bonus of +6D+2, but only towards that target. The target may disbelieve it with a Charisma or mettle roll of 13.

==== Water Spray

Skill Used: Alteration

Difficulty: 10

Effect: 12 (4D damage)

Range: 15 meters (+6)

Speed: +6

Duration: 3 rounds (+6)

Cast Time: 5 seconds (-4)

Other Aspects:

Components (-6): Liter of water (ordinary, destroyed), squeezable container (uncommon)

The mage needs a liter of water in a container that she can squeeze to produce a spray. As she casts the spell, the mage squirts the water onto her hand, letting it run off in the direction of her target. The volume and force behind the water spray increases dramatically. The spray lasts for three rounds of combat. The spell does 4D in damage per round and requires a marksmanship roll each round to hit the target. The caster may only select one target per spell duration.

=== Apportation Spells

==== Alter Movement

Skill Used: Apportation

Difficulty: 15

Effect: 4 (1 meter per round)

Range: 25 meters (+7)

Speed: +7

Duration: 4 minutes/50 rounds (+12)

Casting Time: 1 round (-4)

Other Aspects:

Focused (+2): On target

Gesture (-2): Point at target, then make running motion with fingers (fairly simple)

Incantation (-2): First say, “I command your speed,” followed by whether the target should slow or quicken (sentence)

Variable Effect (+5): Caster may increase effect’s value by up to 5 points on the “Spell Measures” chart

Other Alterant (+1): At time of casting, mage may choose to speed up or slow down target (small)

The caster makes her target either hurry up or slow down, depending on how she words her command. The target’s movement is altered by the measure of the spell effect’s value plus any result points bonus (as read on the “Spell Measures” chart).

Example: A magic user casts the alter movement spell to slow down a charging bull. At casting time, he decided to use the spell effect’s value plus the full variable amount, for a minimum change value of 9, or 60 meters per second (12 meters per round). If his skill total was one point over the difficulty, the new change value would be 10, or 100 meters per second (10 meters per round). This rate would then be subtracted from the bull’s current movement rate, causing the raging animal to come to a complete and shockingly sudden stop.

==== Carrying Wind

Skill Used: Apportation

Difficulty: 13

Effect: 15 (wind with a lifting of 5D)

Range: Self (0)

Speed: 0

Duration: 1 hour (+18)

Cast Time: 1 hour (-18)

Other Aspects:

Area Effect (+15): 3-meter sphere

Charges (+4): 6 charges

Component (-4): May only be cast outdoors, in a clear area (ordinary), mage wears loose clothes (common)

Feedback (-8): points of damage

Gesture (-2): Mimic a fight (fairly simple)

Incantation (-2): “I subdue you and I command you, O wind!” (sentence)

Variable Movement (+7): 25 meters per second

This is a charged spell. To cast it, the mage goes outside and starts running, jumping, and mimicking flight. The mage should be wearing something loose that can catch the wind. One cast garners the mage six charges of the spell.

When released, the spell causes a wind to rise and lifts the mage into the air. The mage can control the direction of the wind and its speed (up to 25 meters a round). The spell can carry as if it had a lifting of 5D.

The wind forms a three-meter sphere around the mage’s body, and nothing can be carried that won’t fit in that sphere.

==== Doorway Home

Skill Used: Apportation

Difficulty: 18

Effect: 11 (passage can handle up to 150 kg.)

Range: 100 kilometers (+25)

Speed: +25

Duration: 2 rounds (+5)

Casting Time: 2 hours 45 minutes (-20)

Other Aspects:

Charge (+2): 3 charges

Components (-2): Something from the location (ordinary, destroyed)

Concentration (-6): 40 minutes with willpower difficulty of 12 Incantations (-2): A statement describing the place (sentence)

Gestures (-3): Pantomime building a doorway (complex; artist roll with difficulty of 11)

After the mage casts the spell, she has firmly fixed in her mind three uses of it. When she releases the spell, she opens a doorway in front of her through which she may step through and instantly be transported somewhere else. The points the skill total is above the difficulty may be added to the effect’s value (thus increasing the amount that can travel through the doorway). An unbreakable barrier over the doorway resists weight of a greater amount than what the spell can handle to go through the doorway. The doorway remains open for two rounds, allowing up to two passages of material weighing no more than 150 kilograms.

==== Relocate Person

Skill Used: Apportation

Difficulty: 14

Effect: 11 (teleport up to 150 kilograms)

Range: 100 meters (+10)

Speed: +10

Duration: 1.5 rounds (+1)

Casting Time: 1 round (-4)

Other Aspects:

Charge (+2): 3 charges

Gesture (-2): Point to target then point in direction of new location (fairly simple)

Incantation (-1): “Go there.” (one or two words)

After the mage casts the spell, she has firmly fixed in her mind three uses of it. When she releases the spell, she points at her intended target, which will be instantly teleported to the range of the spell. The result points bonus may be added either to the value of the weight transported or the distance traveled; read the new value on the “Spell Measures” chart. The spell will not allow anything to appear inside a solid object. Remember that a target who is aware of the potential relocation may roll her Physique or lifting and add it to her weight. The caster’s spell roll must then beat that difficulty as well as the spell’s difficulty.

Note: A similar spell, relocate item, is identical in every way except that the effect is to carry an item weighing no more than 10 kilograms, with a value of 5, and thus the difficulty is 11.

==== Retrieve

Skill Used: Apportation

Difficulty: 12

Effect: 5 (move an object of up to 10 kilograms)

Range: 1 kilometer (+15)

Speed: +15

Duration: 2.5 seconds (+2)

Casting Time: 1 round (-4)

Other Aspects:

Gesture (-2): Stand on tiptoes, point out to imaginary objects and then reach to pick them up. (fairly simple)

Incantation (-2): “I want to reach out beyond the boundaries of the time and space. I want that object to return with me.” (sentence)

Other Conditions (-5): May only be cast in conjunction with view (spell described herein)

Through the use of this spell, the caster can target something he’s seen through a view spell and bring it to his current location (assuming he’s no more than one kilometer from the object). The object can weigh no more than the effect’s value (including bonuses) as read on the “Spell Measures” table.

=== Conjuration Spells

==== Bad Luck Curse

Skill Used: Conjuration

Difficulty: 11

Effect: 6 (Bad Luck (R2) Disadvantage)

Range: 10 meters (+5)

Speed: +5

Duration: 10 minutes (+14)

Casting Time: 2 rounds (-5)

Other Aspects:

Focused (+4): On target

Feedback (-3): -3 to damage resistance total

Concentration (-2): 1 round with willpower difficulty of 8

Other Condition (-3): Limited to Humans

With a minimal amount of pain to himself, the caster curses a Human target with 10 minutes of Bad Luck (R2). See the description of this Disadvantage in the “Character Options” chapter for details.

==== Cage

Skill Used: Conjuration

Difficulty: 27

Effect: 25 (resistance total of bars)

Range: 25 meters (+7)

Speed: +7

Duration: 1 hour (+18)

Casting Time: 1 minute (-9)

Other Aspects:

Area Effect (+15): Sphere with a radius of 3 meters

Gesture (-3): Mime escaping from a cell, then point to target (complex; acrobatics roll with difficulty of 11)

Unreal Effect (-7): Disbelief difficulty of 13

Cage traps a target in a prison of magical energy. To cast it, the wizard mimics trying to escape from a cell, then points at her target. If a marksmanship total beats the combat difficulty for the target, the quarry is trapped. The cage is a sphere with a radius of three meters. Creatures larger than that can’t be confined by this spell.

The effect’s value plus the result points bonus serves as the damage resistance total of the bars. The target can disbelieve and thus free himself by generating a Acumen or investigation total of 13.

==== Communicate with Animals

Skill Used: Conjuration

Difficulty: 10

Effect: 15 (speaking skill with specialization in the animal’s “language” at 5D)

Range: 1 meter (0)

Speed: 0

Duration: 6 minutes (+13)

Casting Time: 1 round (-4)

Other Aspects:

Components (-2): Something from the type of animal with which she wants to communicate (very common)

Gesture (-2): Draw a line on the ground (fairly simple)

To communicate with an animal, the caster places on the ground the bit of something from that type of animal (lock of horse’s hair, bird’s feather, several strands of dog’s hair). Then she draws a line from it to her and from it in the direction of the animal or animals she wishes to speak to. For about six minutes, she receives the ability to communicate with any of that kind of animal as if she had a specialization in its language at 5D. She may add the result points bonus to her speaking roll total. The caster may not move more than one meter from the casting location.

==== Displacement

Skill Used: Conjuration

Difficulty: 12

Effect: 22 (search difficulty of 20 and image transfer of 2.5 meters)

Range: Self or touch (0)

Speed: 0

Duration: 1 minute 40 seconds (+10)

Casting Time: 1 round (-4)

Other Aspects:

Gesture (-3): Turn around and then start hopping from one location to another, while looking back at previous spot before jumping again (complex; acrobatics roll with difficulty of 11)

Incantation (-2): “Hide my true location from sight.” (sentence)

By bending the light around the target, an image of the person or thing is transferred up to 2.5 meters away from his actual location. He becomes invisible to normal sight at his true location, and his image appears and copies all of his movements and actions until the end of the duration. A character must beat a difficulty of 20 with a Perception or search roll or a location spell to find the displaced target.

Anyone touching the image recognizes it for what it really is. This does not give them the ability to see where the target is standing. Any area effect attacks and spells will hit the target should he be in the radius. Otherwise, only using items or other spells discloses the true location of the target.

==== Evil Eye Curse

Skill Used: Conjuration

Difficulty: 11

Effect: 6 (Bad Luck (R2) Disadvantage)

Range: 10 meters (+5)

Speed: +5

Duration: 10 minutes (+14)

Casting Time: 2 rounds (-5)

Other Aspects:

Focused (+4): On target

Feedback (-3): -3 to damage resistance total

Concentration (-2): 1 round with mettle difficulty of 8

Other Condition (-3): Limited to Humans

With a minimal amount of pain to himself, the caster curses a Human target that she can see with 10 minutes of Bad Luck (R2). See the description of this Disadvantage in the “Character Options” chapter for details.

==== Feast

Skill Used: Conjuration

Difficulty: 10

Effect: 4 (5 kilograms of food and water)

Range: 1 meter (0)

Speed: 0

Duration: 4 hours (+21)

Casting Time: 1 round (-4)

Other Aspects:

Components (-6): A plain, cloth napkin (common), a small metal cup (common)

Focused (+4), on people who eat food

Gesture (-2): Wave hand several times over napkin and cup (fairly simple)

Other Alterants (+3), clean water and hearty food

With this cantrip, the mage creates a meal for two of pure, clean water; flavorful, hearty bread; fresh vegetables and fruits; and, if desired, cheese wedges and smoked meat slices. The food must be consumed within 10 minutes of its appearance, so that it has a chance to stay in the body long enough to be digested and actually provide nourishment. The result points bonus increases the amount of food appearing or (at the gamemaster’s discretion) the quality of food.

==== Flight

Skill Used: Conjuration

Difficulty: 16

Effect: 23 (Flight (R1) Special Ability plus the flying skill at +1D)

Range: 0

Speed: 0

Duration: 10 minutes (+14)

Casting Time: 3 rounds (+6)

Other Aspects:

Concentration (-2): One round with willpower difficulty of 8

Component (-2): Bird’s feather (very common)

Focused (+7): On target

Gesture (-1): Point at target (simple)

Incantation (-1): “Fly!” (a few words)

This spell provides the target, who must be within one meter of the caster, the ability to fly and the knowledge to use it for 10 minutes. There is no visible means of convenience; the target can simply move through the air by force of will. The rate equals twice the target’s normal movement rate.

==== Glow Stone

Skill Used: Conjuration

Difficulty: 12

Effect: 12 (negates up to -4D of darkness modifier)

Range: Touch (0)

Speed: 0

Duration: 10 minutes (+14)

Casting Time: 2 rounds (-5)

Other Aspects:

Area Effect (+5): Sphere with radius of one meter

Components (-4): white pebble (common, destroyed)

Focused (+5): On pebble

Gesture (-1): Hold pebble between thumb and forefinger (simple)

Incantation (-2): “Stone of white, give us light.” (sentence)

The magic user casts this spell on a small, white stone, making it glow with a fierce radiance that extends for one meter in all directions around the pebble. The effect lasts for 10 minutes. Once the duration wears off, the pebble turns to dust.

==== Helping Hand

Skill Used: Conjuration

Difficulty: 18

Effect: 13 (telekinesis skill at 4D+1)

Range: 1 meter (0)

Speed: 0

Duration: 5 rounds (+7)

Casting Time: 1 round (-4)

Other Aspects:

Focused (+4): On the caster

The caster can move items without touching them, as if he had the Psionics telekinesis skill at 4D+1. See the description of the telekinesis skill in the “Psionics” chapter for difficulties and ranges.

==== Light

Skill Used: Conjuration

Difficulty: 12

Effect: 12 (negates up to 4D of darkness modifier)

Range: 0

Speed: 0

Duration: 10 minutes (+14)

Casting Time: 2 rounds (-5)

Other Aspects:

Area Effect (+5): Sphere with radius of one meter

Components (-4): white pebble (common, destroyed)

Focused (+5): On pebble

Gestures (-1): Hold pebble between thumb and forefinger (simple)

Incantations (-2): “Stone of white, give us light.” (sentence)

The magic user casts this spell on a small, white stone, making it glow with a fierce radiance that extends for one meter in all directions around the pebble. The effect lasts for 10 minutes. Once the duration wears off, the pebble turns to dust.

==== Mystic Bolt

Skill Used: Conjuration

Difficulty: 10

Effect: 12 (4D in damage)

Range: 10 meters (+5)

Speed: +5

Duration: 3.5 seconds (+3)

Casting Time: 1.5 seconds (-1)

Other Aspects:

Gesture (-2): Swirl hand in air as if gathering energy, then throw it at target (fairly simple)

Incantation (-2): “Ah!” (word, said loudly)

The mage gathers energy from his surroundings and throws the ball at a target. It does 4D in damage at a range of up to 10 meters. He must make a marksmanship roll to hit the target. The bolt must be fired in the same round that the mage casts the spell.

==== Mystical Shield

Skill Used: Conjuration

Difficulty: 10

Effect: 18 (Armor Value of 6D)

Range: 1.5 meters (+1)

Speed: +1

Duration: 5 rounds (+7)

Casting Time: 1.5 seconds (-1)

Other Aspects:

Area effect (+2): One-meter radius

Components (-10): A simple ring (uncommon), handful of colored sand (common, destroyed)

Focused (+5): On ring

Gesture (-2): Using colored sand, scribe an oval shape in the air (fairly simple)

Incantation (-1): “Protection!” (word)

By tossing some sand in a circle in front of her, the caster creates a semi-transparent oval shield of the same color as the sand. The shield, about two meters in diameter, appears up to 1.5 meters away. It is focused on the ring, which the mage must wear. It offers an Armor Value of 6D against all types of physical (not mental) attacks.

==== Stunned Senseless

Skill Used: Conjuration

Difficulty: 12

Effect: 15 (6D+2 stun damage)

Range: 10 meters (+5)

Speed: +5

Duration: 3.5 seconds (+3)

Casting Time: 1.5 seconds (-1)

Other Aspects:

Gesture (-2): Point finger and then palm at intended target (fairly simple)

Incantation (-1): “Stop!” (word)

With a gesture and a word, the magic user sends a bolt of mystical energy toward his intended target. However, the bolt isn’t intended to harm the target, instead only doing stun damage.

==== Voodoo Curse

Skill Used: Conjuration

Difficulty: 12

Effect: 6 (Hindrance (R2) Disadvantage)

Range: 1 kilometer (+10)

Speed: +10

Duration: 10 minutes (+14)

Casting Time: 2 rounds (+5)

Other Aspects:

Components (-11): Scrap from clothing target wore recently or lock of hair (very rare); doll in the shape of

Human (common); several large, thick pins (common)

Concentration (-2): 1 round with willpower difficulty of 8

Incantation (-2): Description of what caster wants the target to feel (complete sentence)

Focused (+4): On target

With a few simple items and a spell inspired by the rites of the vodun religion, the caster can cause great pain to his target. First the caster attaches the scrap of clothing or the lock of hair to the doll. Then, while placing pins in appropriate places, the caster describes the kind of pain he desires his target to feel. For 10 minutes after the completion of the spell, the target receives a +2 difficulty modifier to the caster’s choice of any three skills.

=== Divination Spells

==== Detect the Living

Skill Used: Divination

Difficulty: 14

Effect: 24 (search of 8D to locate a single type of creature)

Range: Self

Speed: 0

Duration: 10 seconds (+5)

Casting Time: 1 minute (-9)

Other Aspects:

Area effect (+20): 10-meter radius circle

Component (-12): Something from the type of creature being detected (uncommon, destroyed); fire, such as a match or lit coal (very common, destroyed)

Concentration (-3): 25 seconds with a mettle difficulty of 9

Gesture (-1): Inhale smoke (simple)

Variable Movement (+4): Bending (can’t see target)

Before throwing the spell, the caster should decide what sort of being she’s looking for, because she’ll need a piece of it for the spell to work (a lock of hair from a Human, fur or fangs from an animal, etc.).

The caster sets the object on fire and inhales the smoke while concentrating. Once the casting is done, the mage can detect the presence of any such being within a 10-meter radius for two rounds. The higher the search skill total is above the difficulty, the more information the caster knows about the beings she seeks (such as location, number, gender, etc.). The difficulty starts at 10 for a Human-sized creature, and goes down for larger creatures, up for smaller ones, and up for the number of other types of creatures in the area.

==== Scrying

Skill Used: Divination

Difficulty: 11

Effect: 34 (2.5 months)

Range: Scrying object (0)

Speed: 0

Duration: 1 minute (+9)

Casting Time: 2 rounds (-5)

Other Aspects:

Components (-9): Scrying tool with images or symbols (tarot cards, playing cards, runes, etc. ) (uncommon); item the person owned for at least a month or the person herself (very rare)

Gesture (-6): Randomize the tool and place parts of the tool in a set pattern (fairly simple); interpret the symbols (very complex, scholar difficulty of 15)

Other Conditions (-1): Physical contact with tool

By interpreting cards or runes, the diviner gains a sense of what the future holds for the person who the reading is about. The mage may choose to look for a condition that could occur up to two and a half months into the future. She can see one minute’s worth of the future. Use the result points of the divination roll to determine how much information she receives: Zero points reveals confusing images. One to four points allows one useful fact to be gleaned from the reading. Five to eight points tells the mage a few useful facts, including the time of the occurrence. Nine to 12 points allows the mage to note more details, including time and location. Thirteen or more points lets the mage see the scene as if she were present, though in shades of gray.

==== Sense Past

Skill Used: Divination

Difficulty: 25

Effect: 38 (66 weeks in past)

Range: Touch (0)

Speed: 0

Duration: 66 minutes (+18)

Casting Time: 25 minutes (-16)

Other Aspects:

Area effect (+25): Sphere with radius of 5 meters

Concentration (-5): 10 minutes with a mettle difficulty of 11

Components (-9): Magnifying glass (uncommon), expensive pocket watch (very rare)

Countenance (-1): Skin turns sickly gray color for duration of spell

Other Conditions (-1): Physical contact with object

The mage can learn about the past of a single object he touches. He’ll see visions of events that occurred in a five-meter radius around the object in the past. The mage can view events that took place in a past period of time whose value (as read on the “Spell Measures” table) is less than or equal to the effect’s value plus the result points bonus. The mage can scan back to that period at a rate of one week’s worth of images per minute of the spell.

==== View

Skill Used: Divination

Difficulty: 19

Effect: 9 (search skill of 3D)

Range: 1 kilometer (+15)

Speed: +15

Duration: 10 minutes (+14)

Casting Time: 1 minute (-9)

Other Aspects:

Feedback (-3): -3 to damage resistance total

Gesture (-2): Make swimming gestures with hands (fairly simple)

Incantation (-2): “Let me see beyond what I know to be.” (sentence)

The caster opens a tunnel of sorts in space. Nothing may pass through it, but the caster may look through it to the other end. The tunnel starts with a range of one kilometer. This range is determined by the range value of the spell, and can be much longer, depending on the success the caster has throwing the spell. Any bonus from casting goes to both range and speed, being split evenly between them. (To determine the bonus, subtract the skill total from the spell difficulty. Divide by 2, and round up. Add this number to the range and look up the new value on the “Spell Measures” table.)

The effect of the spell takes the place of the character’s search while using the spell, as it is hard to make out minute details.
