= Movement

== What’s in this Chapter

Getting from here to there by any means – running, swimming, ﬂying, using a vehicle, you name it – is what this chapter’s all about.

=== Running

The difficulty to cover rapidly a distance on foot is determined by the number of extra movements the character takes.
One movement equals the character’s Move value; two movements equals twice the Move value, and so on.
For each movement beyond the first, add 5 to the base difficulty of zero.

Example: A character with a Move of 10 meters per round who wants to move 20 meters in one round has a running difficulty of 5, while a character who wants to move 40 meters has a difficulty of 15.
A character who fails his running roll covers only his Move or may even trip.

=== Swimming

A hero’s swimming Move equals half his normal Move (rounded up). One movement while swimming equals the swimming Move, two movements equals twice the swimming Move, and so on.
Increasing this rate likewise increases the base difficulty of 5 by +5 for each movement beyond the first.
Thus, the difficulty for a character to move 2 times his swimming speed is 10 (5 for the base difficulty plus 5 for the additional movement).

Without preparation, a character may hold his breath for a number of seconds equal to 5 times a roll of his Physique or stamina.
Pre-oxygenating his lungs gives a character a bonus.
The maximum any character can hold his breath with preparation is a roll of his stamina in minutes, though this requires having the stamina skill.
The bonus should be much less for the average person.

==== Climbing

Characters who have the climbing skill can move up a surface at their normal Move (barring adverse environmental factors) with a base difficulty of 5.
Those without such a skill move at half their normal movement rate.
Increasing the rate increases the difficulty by +10 for each additional one-half of the base climbing Move (rounded up).

Example: A character with a running Move of 10 meters and without the climbing skill wants to move quickly up a tree.
His base climbing Move is 5.
To increase this to eight meters per round means a difficulty of 20 (10 to climb the tree plus 10 to increase the movement by one-half, or three meters, of his base climbing Move).

Additional modifiers can be found in the “Example Skill Difficulties” chapter.

=== Jumping

A character’s total leaping distance (vertically and horizontally) from a standing position equals one-quarter of his Move in meters (rounded up). The base difficulty is 5 to move this distance, and +10 for each additional two meters (vertically and horizontally) the character hopes to cover.
If there is enough room, the character may try running before jumping.
The character may add 5 to his skill total per round of the running start, up to a maximum of +10 (two rounds). The character must have beat the running difficulty in both rounds in order to get the full bonus.

Additional modifiers can be found in the “Example Skill Difficulties” chapter.

=== Short Distances

A character may move up to 50% of his movement rate (swimming, ﬂying, or base Move) without this counting as an action.
Thus, a character with a base Move of 10 could move five meters on land or 2.5 meters in the water with no action penalty.

=== Maximum Movement

Characters may perform only one movement action of each type per round, unless a special ability allows them to do otherwise.

Game Masters may choose to limit the speed at which characters may travel to 4 times the Move rate for each type of movement.

=== Accelerating and Decelerating

When it becomes important to the scenario, such as a race or a chase scene, the Game Master may choose to include acceleration and deceleration maximums.

A character may increase or decrease his current movement rate by up to 2 times that rate, regardless of whether his movement roll would allow him to travel a greater distance.
The minimum increase or decrease is 2 times the character’s base Move for that type of movement.

Example: A character with a base walking Move of 10 has minimum swimming change of 10 — 2 times his swimming Move of 5.

Example: A character with a Move of 10 is chasing a thief, who just swiped her pocketbook.
In the first round, she may move up to 20 meters, which has a running difficulty of 5.
In the second round, she can increase her speed to 40 meters, which has a running difficulty of 15.
If, in the second round, the player generates a running total of 20, by the acceleration rules, she may only move 40 meters, even though her running total meets the difficulty to move 50 meters.

Similarly, if a character does not make a movement roll that would allow him to move at the previous round’s rate, that character automatically slows by two times his base Move.
In other words, subtract two times the base Move from the current movement rate to get the new movement rate.
If this makes the current movement zero, then the character stops.
If it’s less than zero, the character trips.

Example: The character chasing the thief increased her speed to a rate of 40 meters per round.
To maintain this speed, her player needs to continue generating a total of 15 with the character’s running skill.
If the player gets less than 15, then her character’s speed drops to 20 meters per round (40 minus 2 times her base Move of 10).

=== Fatigue

Keep in mind that most characters cannot move rapidly for long periods of time.
Determine a suitable length of time depending on existing conditions, the Physique of the character, and any relevant special abilities she has.
Any additional fast movement beyond that predetermined length requires a fatigue modifier of +3 to the difficulty for each additional round that she continues running.
The modifier is cumulative.
Thus, one round beyond the maximum is +3, two rounds is +6, and so on.

The Game Master may use the fatigue modifier for any repetitive action performed for an extended period of time.
They can also use it as the modifier to a base difficulty of 5 when using the stamina or willpower skill in an attempt to overcome the fatigue.

=== Other Movement Options

The Game Master may include additional modifiers or require an additional related skill roll for any form of movement, depending on surrounding conditions, such as high winds, numerous obstacles, slick surfaces, sharp turns, and so on.

==== Movement Difficulty Modifiers

Base Difficulty for Characters: 5

Easy terrain (ﬂat surface, smooth water, using a ladder, light breeze, light rain or fog) 0

Moderate terrain (uneven surface, small obstacles, choppy water, climbing a tree, strong winds, heavy rain or fog) +5

Rough terrain (large but negotiable obstacles, strong undercurrent, climbing a rough wall, unyielding obstacles — pillars, trees — to ﬂight) +10

Very rough terrain (dense and large obstacles, stormy weather, a few airborne hazards, hail) +15

Hazardous terrain (minefield, narrow walkway, many airborne hazards, large waves, climbing a smooth surface, complete darkness) +20

Very hazardous terrain (corridor filled with falling debris and explosions, swimming or ﬂying in a hurricane) +25 or more

=== Vehicles and Aerial Characters

Vehicle actions work like normal character actions, with some additional game mechanics for special situations.

Much of the information found in this section applies equally well to ﬂying characters, particularly the details on stunts.

=== Vehicle Movement

Vehicles have five speeds of movement: stopped, cautious, cruising, high, and all-out.
They may make one movement action per round.

• Stopped: The vehicle is motionless.
This requires no roll.
Air vehicles should be on the ground when at this speed level.

• Cautious: The vehicle travels at half its Move.
This is generally a free action requiring no roll, but terrain conditions may increase it from its base difficulty of zero.
Air vehicles at this level must be attempting to reach a higher or lower altitude at this speed; they cannot maintain altitude at cautious.

• Cruising: The vehicle travels at its Move.
This requires an action, but since it has a base difficulty of zero, the character need only roll if movement conditions dictate otherwise.

• High: The vehicle travels at twice its Move.
This requires a piloting roll with a base difficulty of 5, modified by existing conditions.

• All-out: The vehicle travels at four times its Move.
This requires a piloting roll with a base difficulty of 10, modified by existing conditions.

Vehicles may travel anywhere between half their current speed and the full current speed at each level.
Rapid acceleration and deceleration are considered stunts and dealt with later in this section.

=== Character Flying Movement

Characters who ﬂy travel at the base rate designated in the Special Ability or equipment description.
To increase this rate, use the same rules as for running, except that the character relies on the ﬂying skill.
Characters may not use this skill unless they have a means of propelling themselves through the air or they are in a zero-gravity environment.

=== Stunts

For normal vehicle use or casual ﬂying under ideal conditions, a character need not make a skill roll.
When the conditions turn less than favorable or he decides to attempt a fancy maneuver, his piloting skill plus the vehicle’s Maneuverability code or his ﬂying skill determines his success.

Rapid acceleration and deceleration also warrant rolls, enhanced by the vehicle’s Maneuverability, to see if the operator maintains control.
These maneuvers have an initial difficulty of 10, adjusted based on existing conditions (see the “Stunt Difficulties and Modifiers” chart for some suggestions). A vehicle or ﬂying character may reduce or increase movement by two levels in one round.
Failing this roll means that the character has lost control for one round.
If some immovable force doesn’t stop the vehicle or character during that round, he may attempt to regain control (with a base difficulty of 15) on the following round.

If a character wishes to perform any other actions in addition to piloting or ﬂying, he must make the appropriate skill rolls for all actions, reduced by the multi-action penalty, regardless of the situation.
The base difficulty for normal operation becomes 5.
Stunts still have their established base difficulties.

==== Stunt Difficulties and Modifiers

Docking (water), parking (land) 6

Landing (air vehicles) 10

Moving on a straight way 0

Regaining control (in situations other than ramming or sideswiping) 15

Sideswiping 10

Easy turn (less than 45 deg.
from current direction) 5

Fast 45-degree turn 9

Fast 90-degree turn 15

Fast 180-degree turn 21

==== Condition Modifier For All Vehicles

Moving in reverse +6

Ramming +10

==== For Land and Water Vehicles

Moved or moving over curb or debris +3

Limited parking or docking area +3

==== For Land Vehicles Not Designed for Off-Road Conditions

Off-road +6

==== For Air Vehicles and Aerial Characters

Unlimited landing area -3

Limited landing area +3

Almost no landing area +6

Rough or unsteady landing area +3 or more

Climb or dive of 45 degrees or more from current direction +6 or more

==== Terrain Conditions

For modifiers due to various terrain conditions, use the “Movement Difficulty Modifiers” table.

==== Vehicle Familiarity

Use the following table when a character is not familiar with the vehicle she needs to operate.
If the character does not have the piloting skill at all, these difficulties are in addition to the untrained modifier.

Very common or simple (car, pickup, bicycle) +3

Common (farm tractor, motorcycle, motorboat, snowmobile) +6

Moderately common (speedboat, bus, semi tractor) +8

Uncommon (ultralight plane, tank, hang-glider, unicycle) +11

Unusual (prop plane, glider) +14

Rare (jet, submarine) +17

Exotic (fighter plane, space shuttle) +20

=== Ramming and Sideswiping Vehicles

Ramming is done with the nose of a vehicle, while sideswiping is done with its side.
The character makes the appropriate vehicle roll, including the vehicle’s Maneuverability.
If the character fails the roll, the vehicle misses and spins.
Land and vehicles turn up to 180 degrees and lose power, while space vehicles continuing spinning.
The character must then spend one round starting it or regaining control and another getting back in the right direction.
Should the character instead succeed, she keeps the vehicle reasonably straight and may try for another sideswipe or ram on the next turn.
The pilot of an air vehicle that rams or sideswipes another vehicle automatically loses control.
About the best she can hope for is to make a successful, but rough, landing.

Both vehicles take damage (the mechanics of this are explained later in this section) in a successful ram or sideswipe.

=== Vehicle Attacking and Dodging

The base difficulty to hit a vehicle 10, modified by distance and the sizes of the attacker and the defender (using the scale modifier listed in the “Combat Options” chapter). That means a person shooting a car has a +6 to his attack total, while a car sideswiping another car has no modifier.

If the driver wishes to fire a weapon, he must make both an Easy piloting roll (modified by the vehicle’s Maneuverability code) and a marksmanship roll.
Because he’s doing two actions, he also incurs a multi-action penalty to both rolls.
Passengers may shoot with few or no penalties.
(Note that these actions would not be possible in some vehicles.)

A character may also attempt to maneuver the vehicle out of the way of incoming projectiles or other vehicles.
Instead of the dodge skill, the character uses his piloting skill plus the vehicle’s Maneuverability code.
Use the active partial or full defense rules for characters to determine the new defense total.
The defense total becomes the new combat difficulty and is in effect until the character’s turn in the next round.

=== Vehicle Damage

When a vehicle takes damage from a weapon or another vehicle, it’s the level of destruction that matters.
Use the following guidelines and compare the result to the “Vehicle and Passenger Damage” chart.
Modify the damage total of the attacker or the damage resistance total of the target by the scale modifier, as appropriate for the situation.

A vehicle’s damage resistance total equals its Toughness plus the value of any armor.
Character Points or Fate Points may not be spent on this roll.

With weapons, compare the weapon’s damage total to the target’s damage resistance total.

When vehicle collides with something else, decide how fast it was going when it made the collision and modify it based on the circumstances of the collision.
Compare that to the damage resistance total.
Should two vehicles be involved, both take damage.

==== Speed Damage Modifier

Stopped 2D

Cautious 4D

Cruise 6D

High 8D

All-out 10D

==== Collision Damage Modifier

Head-on +3D

Rear-end, sideswipe -3D

Nose to side 0

Into something very hard 0

Into something yielding -1D or more

Note: Modifiers are cumulative.
Situation is the one in which the damaged vehicle is.

=== Crew and Passenger Injuries

Depending on how badly damaged the vehicle becomes, the crew and passengers may be harmed, too.
Adjust passenger damage based on how much of the passengers is exposed (for example, motorcycles and canoes offer little protection to their cargo).

==== Vehicle and Passenger Damage

Damage exceeds resistance by: 1–3; Vehicle damage is: Very Light; Passengers Suffer: No damage

Damage exceeds resistance by: 4–8; Vehicle damage is: Light; Passengers Suffer: 1/4 Damage Total

Damage exceeds resistance by: 9–12; Vehicle damage is: Heavy; Passengers Suffer: 1/2 Damage Total

Damage exceeds resistance by: 13–15; Vehicle damage is: Severe; Passengers Suffer: 3/4 Damage Total

Damage exceeds resistance by: 16+ ; Vehicle damage is: Destroyed; Passengers Suffer: All Damage Total

Note: All modifiers are cumulative.
A vehicle may take an unlimited number of Very Light and Light levels of damage.
At Heavy or above, any additional level of damage above Very Light bumps the damage to the next level.
Game Masters may include or substitute damage to other systems if the vehicle has them (ex., weapons, navigation, or sensors).

Very Light: Vehicle loses 1D from Maneuverability for this round and the next.

Light: Vehicle loses 1D from Maneuverability or, if at 0D in Maneuverability, top move speed is decreased by one level.
The loss or modifier remains until repaired.

Heavy: Vehicle loses 2D from Maneuverability or, if at 0D in Maneuverability, top move speed is decreased by two levels.
The loss or modifier remains until repaired.

Severe: Vehicle is out of control, decelerating by two levels each round until it comes to a stop or crashes into something.

Destroyed: The vehicle will never operate again.

=== Leaping Out of a Vehicle

Leaving a land or water vehicle moving at less than 5 miles per hour is a Very Easy acrobatics or Reﬂexes roll (or jumping if the character leaps from the vehicle). If the vehicle is moving faster than that, the base difficulty becomes 15, with +1 added to it for every 10 kilometers per hour the vehicle is traveling (rounded down). Additionally, the character takes damage from the fall, at a rate of 1 for every 15 kilometers per hour the vehicle is moving (rounded up) minus the result points from the roll.

Example: If the driver of a car traveling at 90 kilometers per hour decided to leave the vehicle before it hit the tree it was traveling toward, the difficulty would be 24 (90/10 = 9, plus the base difficulty of 15). She would also take 6 points of damage unless she sufficiently succeeded at her jump (90/15 = 6).

=== Repairing a Vehicle

The difficulty to repair a damaged vehicle depends on the amount of damage and availability of parts and tools.
See the repair skill description in the “Example Skill Difficulties” chapter for difficulty and modifier suggestions.
