[glossary]
= Key terms

These definitions provide you with a general idea of what each term means.
Terms italicized within each definition refer to another entry within this glossary.

[glossary]
action::
    A task that the character undertakes or something that the character does, like give a speech or climb a wall.
active defense value::
    A number the character gets when concentrating on getting out of the way of an attack.
Armor Value::
    A die code representing the amount of protection a defensive covering provides. It can help determine the _damage resistance total_. This term is sometimes abbreviated AV.
Body Points::
    The amount of injury a character can sustain, listed as a number. The _damage total_ is subtracted from the character’s current Body Point total.
Character Point::
    A bonus representing a surge of adrenaline or that extra luck the main characters of a story seem to have. Allows the user to roll an additional _Wild Die_.
combat difficulty::
    A number representing how challenging it is to attack someone or something. It equals the _active defense value_ or the _passive defense value_.
complementary skill::
    A skill whose results could benefit from the use of another skill.
creation points::
    Points used when designing a character to purchase die codes in game characteristics or other features that represent the character’s abilities, experience, and background.
Critical Failure::
    A result, represented by a 1, on the Wild Die that indicates something bad has occurred.
Critical Success::
    A result, represented by a 6, on the Wild Die that indicates something good has happened. Generally, the player adds the 6 to the current total and rolls again, adding and rerolling as long as a 6 comes up.
D (as in “1D”)::
    An abbreviation for “six-sided dice.” The number in front of the “D” lets you know how many six-sided dice to roll.
damage resistance total::A number that indicates how much injury a character or object can absorb, soak, or deﬂect.
damage total::
    A number representing how much injury or destruction something has caused.
defaulting to an attribute::
    Using the _die code_ for an attribute when the character doesn’t have a higher die code in the needed skill.
die code, score::
    The number of six-sided dice players roll (1D, 2D, 3D, 4D, 5D, etc.), and sometimes an amount (called pips) of “+1” or “+2” that is added to the total result that came up on the dice. “Die code” and “score” are used interchangeably.
difficulty::
    A number representing how challenging it is to perform an action.
Fate Point::
    A bonus representing that a character is using all of her concentration to try to succeed. Allows the player to, at least, double the number of dice on one roll. Sometimes the Game Master will provide other benefits.
free action::
    Any _action_ that takes only a few seconds to perform or do, such as take a few steps or a quick glance around a room.
modifier::
    A number or _die code_ that is added or subtracted from another number or die code to represent a change in the typical situation.
opposed difficulty, opposed roll::
    A difficulty that applies when one character resists another character’s action. In this case, both characters roll _die codes_ related to the activity and compare them.
passive defense value::
    A number representing a character’s innate ability to get out of the way of danger. It usually equals 10.
pip::
    An added bonus to the total result that came up on the dice. A “+1” means one is added to the total, while “+2” means two is added.
range(in combat)::
    The distance from the attacker to the target.
result points::
    The difference between the total rolled with an attribute’s or skill’s die code and the _difficulty_ of an action.
result point bonus::
    Usually, one-half (rounded up) of the result points figured for an action. It sometimes may be used to affect other rolls.
round::
    A unit of time equal to five seconds in the game world. Figuring out what happens in a round can take longer.
scale::
    A game mechanic representing that opponents of vastly different sizes can affect each other differently in combat.
standard difficulty::
    A number, generally selected from a chart, assigned to an action based on how challenging it is.
Strength Damage::
    A die code representing the amount of harm a character can do because of his or her physical prowess.
Toughness::
    A _die code_ representing the amount of damage an object can take, similar to a character’s Physique attribute.
unskilled modifier, untrained modifier::
    A modifier added to an action’s difficulty that represents the increased difficulty of doing something without the right training or experience. The terms are used interchangeably.
Wild Die::
    A six-sided die, of a different color or size from other dice used, that represents the randomness of life, with the 1 and the 6 indicating a special result (see _Critical Failure_ and _Critical Success_).
Wounds::
    The amount of injury a character can sustain, listed as a level. The level is determined by comparing the difference between the _damage total_ and the damage resistance total to a chart.
