= Adventure Skill Examples

The “Character Basics” chapter provided brief descriptions of each skill (and you will need to return to that chapter for a refresher). When the generic difficulties aren’t enough, look up various skills in this chapter to get even more ideas on the challenge level for using those skills in common situations.
Of course, not every possibility has been covered, but this provides a terrific foundation.

== Using the Example Difficulties and Modifiers

Unless otherwise stated, all listed modifiers are to the difficulty.
Modifiers may be cumulative, depending on the situation — the tenser they are, the more important the minutia become.
The associated attributed is listed after the skill name.

=== Extranormal Skills

Descriptions and difficulties for Extranormal skills are found in their own chapters.

=== Knowledge-Based Skills

Skills covered: business, scholar, tech

The Knowledge attribute assists characters in finding out how much they know about a certain field, modified depending on the situation.
For this reason, one chart of general difficulties can serve most uses of Knowledge, business, and scholar, some uses of tech, and investigation attempts involving researching a topic.

Game Masters can employ the “Information Difficulties” chart in one of two ways: by picking a difficulty based on what the character seeks or wants to recall, or by comparing the skill total rolled to the difficulties (whichever level the character meets or beats is the amount and type of information collected or recollected). Realize that the less well-defined the skill is, the less information the character knows or finds.

One high roll in any of these skills does not necessarily make the character an expert in that field.
The roll represents only what the character recalls at the time.
A high roll could reveal a specific detail of the information sought, as well as some hints for discovering more of what the character seeks.

Characters may be assumed to have a general knowledge of their home country, culture, and era, including basic geography, famous people, and common etiquette.

*Information Difficulties*

Amount of Information Difficulty

Basic or common information; unconfirmed rumors 5

Theories; generalities 10

Complex concepts; moderately detailed information 15

Professional level; extensive (though not complete) information 20

Cutting-edge topics; extensive information, including peripheral details and extrapolations 30

*Condition Modifier*

Age of information (per century in the past) +5

Closely guarded secret +15

=== Perception-Based Skills

Skills covered: search, tracking

Game Masters can rely on the “Observation Difficulties” chart for situations involving the gathering of information.
They can be used as difficulties to beat or as a means of reading the results of a dice toss.

To see if a character notices details of a scene or situation, the Game Master may have the player make a Perception roll.
Unless the characters are actively eavesdropping, searching, tracking, or performing a similar activity (and thus using the search or tracking skills), this passive observance of a scene does not count as an action.
Use this chart as a guideline for how much the character notices.
If the skill total meets or beats the difficulty, the character gains that much information.

*Observation Difficulties — Situation Difficulty*

Noticing obvious, generic facts; casual glance 5

Noticing obvious details (ex.
number of people) 10

Noticing a few less obvious details (ex.
gist of conversation) 15

Spotting a few specific details (ex.
identities of individuals) 20

Spotting a few obscure details (ex.
specifics of conversation) 25

Noticing many obscure details 30 or more

=== Presence-Based Skills

Skills covered: charm, con, intimidation, persuasion

Characters use one of several Presence-based skills to influence other people that they meet.
The typical difficulty is 10, modified based on the dispositions of the characters involved, but a Game Master may base it on a skill roll.
See the “Mental Defenses” sidebar for more information on this; suggested difficulty modifiers are listed below.

Die rolls alone should not determine interactions between players’ and Game Master’s characters.
Game Masters should have their players detail what their characters say and do to before rolling the dice.
The better the player acts the role of his character, the greater his chance of success should be, which Game Masters can reflect by allowing up to a +1D modifier to the skill roll.

See also the individual entries in this chapter for charm, con (listed with charm), intimidation (also listed with charm), and persuasion.

*Mental Defenses*

In general, the resistance difficulty for any Psionics or interaction skill equals 10.
The target cannot actively resist unless he knows that a psychic or interaction skill is being used on him by another character.
If the Game Master decides that the target suspects but does not know for certain that someone is attempting to influence him, the Game Master may allow the character to take an action earlier than his turn in the round and roll his willpower or Presence to generate a new resistance difficulty.
Should the character decide to actively defend against mental intrusion or personal interaction, he may devote all of his actions for the round to that task and roll his willpower or Presence, adding +10 to the score to get the new resistance difficulty.
However the interaction resistance difficulty is determined, Game Master may further modify the number as the situation warrants (such as stress, surprise, or character relationship).

*Interrogation Attempts*

Characters may use intimidation or persuasion to get information out of someone.
Use the rules for mental defenses to determine the difficulty and base interaction modifiers.
Further modify the number by how important the information is to the target.
(See the accompanying chart for suggestions.) A separate intimidation roll to scare the target can complement an interrogation session.

*Interaction Modifiers — Situation Modifier*

Target is friendly or trusting -5

Target is neutral toward character or of equal standing 0

Target is hostile or has superior standing +5

Target is an enemy +10

Target is in weakened position -10

Request is something target would do anyway or target feels is of minor importance 0

Request is illegal or highly dangerous +10

Target is on guard or actively resisting* +10

*Do not include this modifier if you are using the active mental defense described in the “Mental Defenses” sidebar.

*Interrogation Modifiers —*

Target… Modifier

Feels information is unimportant -10

Feels information is of minor importance 0

Feels information is important +5

Feels information is very important +10

Would rather die than reveal information +10 or more

=== Combat Skills

Skills covered: brawling, dodge, marksmanship, melee combat, missile weapons, throwing

Difficulties for these skills are included in the “Combat” chapter.

For throwing, see also that skill’s entry in this chapter.

=== Business, Scholar (Knowledge)

See the “Knowledge-Based Skills” for difficulties and modifiers related to using this skill.

=== Charm, Con, Intimidation (Presence)

Charm, con, and intimidation can enhance a character’s attacks and defenses.
The player adds one-half of the difference (positive or negative) between the difficulty and the charm, con, or intimidation roll to any one attack or defense attempt (not both) made at Point Blank or Short range.
The character must use the benefit from scaring (intimidation), tricking (con), or seducing (charm) the target on the same turn as or on the round after the interaction endeavor.

The user’s appearance and demeanor can also affect charm, con, or intimidation attempts.
The more threatening the character looks or seems, the less effective charm and con actions are, while intimidation attempts are more effective.
Use the “Generic Modifiers” table in the “Game Basics” chapter to decide how much the appearance and demeanor affect the target, if a Disadvantage or Special Ability doesn’t already provide one.
See also “Presence-Based Skills” for other difficulties and modifiers for these skills.

=== Flying (Reflexes), Running, Swimming (Physique)

Difficulties for these skills are included in the “Movement” chapter.

=== Hide (Perception), Sneak (Reflexes)

The difficulty for a hide or sneak attempt is usually the opponent’s Perception, search (for hide), or tracking (for sneak), either as a die roll (if the opponent is actively trying to find the object or person) or as a derived value equal to the number in front of the “D” in the opponent’s attribute or skill times 2 and add the pips.

*Condition Modifier*

Heavy rain or snow -3

Dawn, dusk, fog, many trees, large crowd, etc.
-2

Night -5

Inattentive observer -5

Dense concealment (thick jungle, crowd of people in costume) -5

Many distractions (party, parade, combat) -5

Attentive observer +6

Open terrain +6

Good lighting +6

Several observers +9

=== Acrobatics (Reflexes)

Using acrobatics can also improve many of a character’s climbing, jumping, and running attempts.
The Game Master determines the difficulty of the acrobatics stunt.
One-half of the difference (rounded up) between the difficulty and the acrobatics roll is added to the complementary skill.
The acrobatics attempt and the climbing, jumping, or running try must be done on the same turn.

Instead of adding a modifier to the running or swimming difficulty for particularly challenging obstacle courses, the Game Master may have the hero make an acrobatics roll in addition to a running or swimming roll.
Acrobatics can make a character appear more intimidating.
The player may add one-half of the difference (rounded up) between the difficulty and the successful acrobatics roll to her intimidation attempt.
The intimidating attempt may be made on the same turn as the acrobatics roll or on the next round.

During a fall, acrobatics may be used to reduce bodily harm.
If the character has not already used his turn for the round, he may rely on acrobatics in an attempt to land properly.
The character generates an acrobatics total.
For every five points over the base difficulty number of 10, the hero reduces the damage total by one point, in addition to a base reduction of one point.
The damage total, however, cannot be lower than zero.

*Maneuver Difficulty*

Somersault; pirouette 5

Handspring; cartwheel; handstand 10

Swing over a obstacle 10

Round-off; backflip 15

Vaulting over an obstacle 15

Bouncing off a surface to reach a specific destination 20

Walking up a wall* 30

*The character may “walk” a maximum of her Move in one round; she must have a flat surface to stop on at the end of her turn or she falls and takes damage from the fall.

*Condition Modifier*

Flat surface to flat surface 0

Unlimited landing area -3

Limited landing area +3

Almost no landing area +6

Rough or unsteady landing area +3 or more

High surface to low surface +3

Low surface to high surface +6

Slippery surface +3

Strong wind +3

Add a twist of the body (per twist) +3

Performing the maneuver underwater or backwards +3

Performing the maneuver in the air (such as on a trapeze or bars) +9

Performing the maneuver on a narrow surface +6

Note: Characters may combine one or more maneuvers in the same action.
In this case, use the difficulty of the most challenging maneuver, add 3 for each additional maneuver (up to five additional maneuvers), and include modifiers as if the complex stunt was one maneuver.

=== Animal Handling (Presence)

When attempting to get an animal to do a trick, the character must also roll against its willpower roll (the Game Master generates this). Examples of tricks include rolling over, getting into a cage, jumping up, and obeying commands.
The character’s animal handling total may be modified by the attitude of the animal toward the character.
The success of tricks are determined by a roll of the animal’s attributes or skills.

*Animal’s Attitude toward Character Skill Modifier*

Friendly or trusting +5

Neutral 0

Hostile -5

*Willpower > Animal Handling Result*

1–2 Animal looks at the handler in a confused way.

3–6 Animal lies down for one round.

7–11 Animal lies down for two rounds.

12+ Animal snaps at the handler; if hit, the beast will attack the handler until subdued.

=== Artist (Perception)

*Quality of Piece Difficulty*

Amateur 9 Time required: A few minutes to half hour

Professional 15 Time required: Minimum one day

Emotionally moving 18 Time required: Minimum one day

Prize-winning 24 Time required: Minimum one week

Complexity of Piece Modifier

Simple; has one or two parts -5

Moderate; has a few parts 0

Complex; has many parts +10

=== Climbing (Reflexes)

Difficulties for this skill are included in the “Movement” chapter.
Note that taking care in climbing and carrying 50% or more of the character’s body weight slows the character down by two meters or more per round.

*Condition Modifier*

Taking care in climbing -5

Less than a 90-degree angle -3

Less than a 60-degree angle -6

Less than a 45-degree angle -9

Prepared for climbing -6

Carrying 25% of body weight +3

Carrying 50% of body weight +6

Carrying 100% of body weight +15

Many handholds -10

=== Command (Presence)

The command skill governs the act of convincing individuals to comply with specific directions, as well as maintaining morale during group undertakings (such as combat or building large pieces of equipment). This skill is typically used only with the Game Master’s characters, though it can be sometimes attempted with the players’ characters (such situations should be role played first, with a bonus or penalty to the command roll based on how well the group participated in the activity together). A high command roll can complement individual participants’ rolls in a group activity, while a low command roll can impose negative modifiers.
It generally requires at least one round of planning to perform effectively.

Characters can use this skill to combine their attacks.
One person is designated the leader and makes the command roll.
If successful, everyone goes on the leader’s initiative.
Participants make their attacks with the hit location modifier (to reflect that they’re aiming at a designated location), but the target resists the combined total of all damage done it.
If the command roll fails, determine initiative and actions individually.

*Complexity Difficulty*

Uncomplicated; imprecise 3

Easy; minimal precision required 7

Requires effort or precision 12

Difficult; requires high degree of precision 17

Requires much effort or extreme precision 22

Requires care and thoughtfulness, or exacting precision 28

*Team Modifier*

All members willing to follow leader’s orders no matter what -20

All members willing to sacrifice life for others -15

Trained together frequently to work as unit -10

Trained together briefly to work as unit -5

Work together regularly, or willing to work together 0

Worked together on a few occasions +5

Seldom work together +10

Never worked together before, or more than half of the members hate each other +15

No interest in working together; all members despise each other; or members can’t communicate with each other +20

=== Contortion (Reflexes)

The chart below contains sample difficulty numbers for escaping from various kinds of restraints.
Modify the difficulty based on the circumstances of the escape, such as the conditions the character works under or specially designed restraints.
The character may not use this skill if completely immobilized.
If in multiple restraints, the character must make a separate roll for each one.
A Critical Failure indicates that the character has pulled a muscle (and he does his Strength Damage to himself). The Game Master decides whether he may try again.

Note that this skill does not substitute for the lockpicking skill.
The character may be able to pull his arms over his head to use his hands, but he may not be able to slip out of the handcuffs unless they are improperly secured.

*Sample Restraints Difficulty*

Ropes 13

Wires, chain 15

Handcuffs 16

Straitjacket 18

=== Demolitions (Knowledge)

The base difficulty is 5.
For extra damage and special effects, the character must spend one round per difficulty number setting up the explosives.
The character also needs to indicate how much explosive she’s using.
If the attempt is successful, compare the skill total with the object’s damage resistance total (its Toughness modified by size, thickness, flaws, supports, etc.). Items that take at least 13 points above their damage resistance total are severely damaged, if not destroyed.
Items taking less than that are weakened, and another attempt may be made (with the object having a reduced damage resistance total and possibly other problems).

Remember that, while a character may think an object is constructed of one type of material, it may not be.
Though this does not alter the difficulty of setting the explosive, it may change the results of special effects.
For instance, an explosive set for thin wood won’t do much good if that’s only veneer for reinforced steel.

*Example Result Modifier*

Rigging a bomb so a car explodes the next time it starts 0

Blowing something open without leaving permanent marks or burns +5

Rigging an explosion so its force goes in a specific direction +10

Rigging an explosion so that only a certain, small piece of a much larger object is damaged +15

Extra damage +5 per +1D

Familiarity with Target Modifier

Very familiar or common (tree, wall) 0

Familiar (bulkhead, bridge support) +5

Unfamiliar (building of unknown construction) +10

Completely unknown item or construction +20 or more

*Object Construction Toughness*

Flimsy (plywood door) 1D

Tough (hard wooden door, most guns) 2D

Sturdy (bolted steel door, personal safe) 3D

Very sturdy (a few layers of steel) 4D

Reinforced (numerous layers of steel) 6D

=== Disguise (Presence)

A character’s skill total in creating the disguise serves two related purposes.
First, the higher the roll, the less likely an observer will be to question the disguise.
Second, the total becomes the difficulty number for Perception or investigation efforts to see through it.
If the investigation check is higher than the disguise total, the disguise has been penetrated.

If at any time while the character is disguised she performs an action inconsistent with the disguise, any observer has a chance to see through it.

Although one character may use disguise on another character, the disguised character must actively work at keeping up the disguise using her own disguise skill or Presence.

*Condition Modifier*

Specific person +15

Other sex +6

Different race or species +3

Great age difference +3

Much larger build +5

Much smaller build +10

Resembles the disguise already -5

Using skill on another character +6

Using skill unaided +3

=== Forgery (Knowledge)

The artist skill may complement this skill, or the Game Master may require it to be used instead, with the forgery modifiers applied as appropriated.
Reduce the amount of time spent on creating a forgery if the character has repeatedly succeeded at creating similar items in the past.

*Item Forged Difficulty*

Unofficial note or correspondence 6 Time required: 10 minutes or more

Signature 12 Time required: 5 minutes

Official document (driver’s license, legal tender) 18 Time required: 20 minutes or more

Familiarity with Item Modifier

Intimately familiar or has sample -10

Somewhat familiar; has seen it quite often -5

Slightly familiar 0

Has only had it described +5

Guessing blindly +15

*Tools Modifier*

Have necessary tools and some special ones -5

Have necessary tools 0

Have some tools +5

Missing important tools +10 or more

Forgery Inspector

*Familiarity with Item Forged Difficulty*

Intimately familiar 6

Moderately familiar 12

Unfamiliar 18

Completely unfamiliar 24

*Situation Modifier*

Have sample -5

Have special tools for detecting forgeries -5

Item poorly forged* 0

Item well forged* +5

Item superiorly forged* +10

*The Game Master may add one-half (round up) of the number of points above the forging difficulty to the inspector’s difficulty instead of using one of these modifiers.

=== Gambling (Perception)

Gambling doesn’t affect games that are purely random, but does influence games with an element of strategy, like poker.
All characters make opposed gambling rolls, without spending Character or Fate Points, and the highest roll wins.
A character may cheat by using Character or Fate Points on the roll, and the Game Master may give bonuses to rolls for people looking for a cheater or helping the cheater.
The Game Master should consider as many “angles” as possible when using the gambling skill, and add these as modifiers to one or more participants’ rolls.

=== Investigation (Perception)

When used to research a topic, a separate roll must be made for each source checked.

*Research Situation Difficulty*

Common knowledge 7

Requires searching through several sources; introductory theories 12

Sources are of varying reliability; cutting-edge information; specific information about harmless individual or event 18

Esoteric information; specific information about dangerous individual or event 24

*Condition Modifier*

Information closely guarded +5

Character unsure of information sought +5

Character knows exactly what information is sought -5

When used to figure out clues from a scene, the base difficulty is 10.
The character must use search first to find the clues or evidence (or have them pointed out); investigation helps the character figure out what they mean.

*Situation Modifier*

Information about subject/event is sketchy +15

Information about subject/event is extensive -15

Evidence is fairly clear; many clues; familiar objects with expected use -6 or more

Evidence is only partly clear; several clues; familiar objects with uncommon use, or unfamiliar objects with common use 0

Evidence is obscure; few clues +3

Evidence is unusual or with no apparent significance; uncommon objects with uncommon use +6

Repeatedly commits similar crimes (per crime) -3

Distance between crimes (per 50 miles) +3

Time between crimes (per 6 months*) +3

*While the crimes may have been committed over a greater time interval, the maximum value for this modifier is +30.

*Roll > Difficulty Result*

0–2 Basic information about the situation (a rope was used, type of gun).

3–6 Precise information about situation (probable manufacturing origin of evidence, small details about items in room).

7–11 Previous results plus how all items in an area were put to use.

12+ Reconstruction of events from the evidence.

=== Jumping (Reflexes)

Difficulties for this skill are included in the “Movement” chapter.

*Condition Modifier*

Flat surface to flat surface 0

Unlimited landing area -5

Limited landing area +5

Almost no landing area +10

Rough, slick, or unsteady landing area +3 or more

Uphill (more than 30 degrees) +6

Carrying 50% of own weight +6

Carrying 75% of own weight +9

Carrying 100% of own weight +12

=== Know-how (Perception)

To use this skill to help with an activity covered by another skill (which the character does not have), the character spends the round before examining the situation, performing no other actions, and making a roll of this skill versus the difficulty set for the action.
The character gets neither the unskilled modifier nor the preparing modifier.
Within the next 30 seconds (six rounds), the character may add the difference between the difficulty and the know-how skill roll to total roll for the attribute dictated by the actual skill required.
The character may not use this skill in place of a skill she already has.
The Game Master may limit the number of times per hour this skill may be used on the same action.

=== Languages (Knowledge)

Characters with a specialization in the language they are using who succeed at the skill roll receive a +3 bonus to determining the comprehension level.

*Situation Difficulty*

Idea is very simple, consisting of a short phrase 3

Idea is simple; no slang; children’s book 7

Idea is of average complexity; most adult nonfiction 12

Idea is complex; slang involved; most adult fiction 18

Idea is very complex; technical jargon involved; academic writing 24

*Situation Modifier*

One or two common, basic words -5

Has a translating aid (book, computer program, electronic pocket device, hand signals)* -5

Different dialect of own language 0

Language is derived from common root language (ex., understanding Spanish if you understand French) +5

Completely foreign language (ex., Chinese has nothing in common with English) +10

Obscure language; reading lips +15

Language is unique to an uncontacted culture, from a dead culture, or unpronounceable by the character trying to understand +20

Language includes many concepts nearly beyond the character’s understanding or experience +25

*Translation aids might provide their own bonuses, which are used instead of this.

*Roll > Difficulty Comprehension Level*

0–2 Gist of idea; most words understood or conveyed properly; word usage seems stilted

3–6 Literal translation; slang expressed/translated incorrectly

7+ Subtle connotations

=== Lifting (Physique)

At the Game Master’s discretion, a player may make a lifting check when his character first picks up an object.
(Generally, if the object’s weight would give it a difficulty equal to or greater than one-half of the character’s lifting, rounded up, or the object is being lifted hastily or under stress, the Game Master should require a lifting roll.)

For each round the object is carried, the character makes another check to see if he can continue to carry the object.
If the player fails the roll, his character is too exhausted and must put the object down.
If the character is doing anything else at the time (other than walking slowly or talking), continuing to carry the object counts as a multiple action.

*Abridged Lifting Table*

*Weight Difficulty*

1 kg 1

10 kg 3

50 kg 7

100 kg 12

120 kg 13

200 kg 17

250 kg 18

500 kg 23

750 kg 28

1000 kg (1 ton) 33

1100–2000 kg 34-43 (+1 to base of 33 per 100 kg over 1000 kg)

2500–10,000 kg 44-59 (+1 to base of 43 per 500 kg over 2000 kg)

15,000–100,000 kg 60-77 (+1 per to base of 59 per 5000 kg over 10,000 kg)

The Game Master may further subdivide the lifting chart if desired to include the weights for the difficulties not listed here.

*Lifting Fatigue Modifier*

*Time – Skill Modifier*

1–6 rounds 0

7 rounds to 3 minutes -5

3–10 minutes -10

10–30 minutes -15

30–60 minutes -20

Note: After the first hour, the character must make a check once per hour at the same difficulty as one hour.
If the character fails the roll, then he must rest for twice as long as he was lifting the weight.

=== Lockpicking (Coordination)

Characters may not attempt to pick locks without some kind of tools (hairpins, wire coat hanger, telekinesis, etc.). Improvised tools do not add to character’s skill roll, but specialized tools will.

*Type of Lock Difficulty*

Simple key lock 6

Complex key lock 12

Combination lock 18

*Lock Condition Modifier*

Poorly constructed -6

Well constructed +2

Military or security style +6

High security style +9

Lock blueprints and diagrams -4

=== Medicine (Knowledge)

For game mechanics on using medicine to heal damage, see the end of the “Healing” chapter.

*Medicine Diagnosing*

*Action Difficulty*

Determine existence of disease or injury 7 Time required: 1 round

Determine toxicity of substance 7 Time required: 1 minute

Determine type of disease, toxin, or injury 12 Time required: 1 minute

Determine medicine, procedure, or antidote required 18 Time required: 1 round to 1 hour

Determine cause 24 Time required: 1 day to 1 week

=== Navigation (Knowledge)

The base difficulty is 10.

*Condition Modifier*

No idea which way is north +10

General idea which way is north 0

Familiar with terrain 0

Terrain completely foreign +5

Completely lost +10

Have a compass or similar navigational tools -5

Plotting a way through a simple course 0

Plotting a way through a complex course +6

Plotting a way through a dangerous course +9

Determine exact location +15

*Skill Condition Modifier*

Have a poorly drawn map +1D

Have a sketchy but accurate map +2D

Have a well-drawn map +3D

=== Persuasion (Presence)

Characters can use persuasion to “pay” another person to behave dishonorably, such as through ignoring duty, looking the other way, or divulging secret information.
Success depends greatly on the target.
A target who is loyal or wealthy or fears being caught is less likely to accept bribes.
Use the difficulties listed under “Presence-Based Skills” and further modified by such factors as the value of the money, goods, or information offered, the extent of favors given and received, and the target’s attitude toward the bribe.

See also “Presence-Based Skills” for other difficulties and modifiers for this skill.

*Value of Bribe Modifier*

Less than 50% of what is reasonable +10

50% to 90% of what is reasonable +5

Larger than expected -5

Significantly larger than expected -10

=== Piloting (Coordination)

See the “Movement” chapter for details on using this skill.

=== Repair (Perception)

The base difficulty to fix or modify any piece of equipment or vehicle is 10.
The amount of damage sustained, the character’s familiarity with the item, availability of parts, and complexity of the task can modify the difficulty.
The Game Master may require a separate tech roll to determine whether the character can figure out how to repair an unknown item.
Destroyed parts must be replaced, which raises the difficulty.
Additionally, if the character rushes the job, not only is there an increased chance of failure, but the item could also break again soon after its next use.

*Situation Modifier*

Light repairs/modifications 0

Heavy repairs/modifications +5

Extensive repairs/modifications +10 or more

Built or modified item -10

Has item’s designs -5

Common item 0

Has seen but not used item +5

Has never seen item +10

All parts available 0

Some parts available +10

No parts available +20

Correct tools* 0

Makeshift tools +15

*Tool kits might provide their own bonuses, which are used instead of this.

=== Riding (Reflexes)

When a character first mounts a ridable animal, she must make a riding roll against the creature’s willpower roll (the Game Master generates this). The character’s animal handling total may be modified by the attitude of the animal toward the character.
The character stays in control if she ties or beats the beast’s roll.
If she fails, consult the table below for what occurs.

When attempting to get the beast to perform a special maneuver or during events that might frighten it, the character must also roll against the animal’s Presence or willpower.
Examples of special maneuvers include jumping a fence, crossing a raging river, moving faster, or slowing down quickly.
(The success of special maneuvers are determined with the animal’s attributes or skills.)

Characters attacking from the back of a beast take a multi-action penalty for having to both control the mount and use their weapon.

*Animal’s Attitude toward Character Skill Modifier*

Friendly or trusting +5

Neutral 0

Hostile or wounded -5

*Willpower > Riding Result*

1–2 Beast stops and refuses to move for 5 seconds.

3–6 Beast stops and refuses to move for 10 seconds.

7–11 Beast bolts in a random direction for 1D rounds.

12+ Beast bucks rider; rider must make a Moderate riding roll to avoid being thrown off.

=== Search (Perception)

When used to eavesdrop on or secretly watch an event or another character, the skill total indicates the amount of information gained from the surveillance.
Use the “Observation Difficulties” table.
A Critical Failure could mean anything from no information obtained to being immediately spotted by the character being observed, depending on the situation.

When searching for a hidden object or person, the difficulty is generally the hide roll used to conceal the target.
Otherwise, the base difficulty is 5, modified by the table below.

See also “Perception-Based Skills” for more difficulties and modifiers for this skill.

*Situation Modifier*

Character knows target’s exact location 0

Character knows target’s approximate location +5

Character has vague information about the target or its location +15

Character has only general idea of what she’s looking for; searching for small objects +20

Character has no idea what she’s looking for; searching for obscure or tiny objects +25

Searching for microscopic objects* +30

*Might not be possible without special equipment or abilities.

=== Security (Knowledge)

To install a security system, use the chart select an appropriate difficulty number.
The Game Master may award one-half of the points above the difficulty as a modifier to future disarm rolls.
This represents the character adding a few extra improvements to the base system.

To disarm or circumvent a system, the character first needs to find an access to it, which requires applying the search skill.
Once found, the character rolls her security against this chart, modified by how well it was original installed.

*Type of System Difficulty*

No special protection 4

Regular security system 8

High-quality system 14

Bank 20

High-security complex 25

Cutting-edge security measures 30

Disarm Situation Modifier

No special system set-up* 0

Good system set-up* +5

Superior system set-up* +10

*The Game Master may add one-half (round up) of the number of points above the security setting difficulty to the disarmer’s difficulty instead of using one of these modifiers.

Sleight of Hand (Coordination)

The difficulty for a sleight of hand attempt is usually the opponent’s Perception or search, either as a die roll (if the opponent is actively watching for tricks) or as a derived value equal to the number in front of the “D” in the opponent’s attribute or skill times 2 and add the pips.

*Situation Modifier*

Watchful target; few distractions +9

Observant target; light crowd +6

Suspicious target +3

Challenging act (such as palming a baseball) +6 or more

Unobservant target; target constantly jostled; major distractions -9

Confused or distracted target; crowded conditions; minor distractions -6

Simple act (such as palming a tiny object or sliding a hand into one’s own pocket unnoticed) -6 or more

=== Stamina (Physique)

Game Masters may allow a character to make a multi-action stamina roll to complement a strenuous activity, such as lifting or running.
The difficulty equals 5 times the current fatigue modifier.
The character may add one-half (rounded up) of the difference between the successful stamina roll and the difficulty.
The strenuous activity still receives the fatigue modifier.

Whenever a character fails a stamina roll, she is fatigued; all actions are at -1D for every stamina check failed until the character rests for as long as she exerted herself.

Characters can still continue if they are fatigued, until they fail a third stamina check.
At this point, the character is completely exhausted and must rest for twice the amount of time that she exerted herself to remove the penalty.

To avoid the effects of a toxin (inhaled, ingested, or absorbed) or disease (encountered in any manner), a character makes a stamina roll.
(The first attempt after initial exposure does not count as an action; subsequent attempts to resist the toxin do.) Several factors figure into the difficulty of the attempt, including the deadliness and dosage of the poison in question.
For example, a fatal bout of botulism has a difficulty of 9, while a killing dose of cyanide has a difficulty of 42.

Game Masters might call for stamina rolls against falling asleep or unconscious.
(This counts as an action.) Resisting sleep is a difficulty of 5 per hour beyond the normal awake time, modified by environmental factor (too warm or too cold, noise level, etc.). For unconsciousness caused by wounds, see the “Wound Levels” table in the “Damage” chapter.

=== Streetwise (Perception)

Streetwise helps characters get around urban environments.
Some situations call for seeking out those living outside the local law, while others can be handled through upstanding citizens.
Generally, the modifiers are the same for each situation, but the Game Master should adjust them depending on the circumstances.
It is possible, though generally unlikely, that a character would be well-liked by both upstanding residents and local criminals.

Example: In a village, a character would find it easier to gather information about a particular person (and thus the city-size modifier would be -15 instead of +15), but he might have a harder time getting someone to trust him enough to tell him about it (making the tolerance modifier +15).

*Seeking… Difficulty*

Things that are usually easy to find 4 (ex., directions to the nearest police station)

Things that require discretion or careful investigation 7 (ex., asking if the local law is straight or crooked)

Risky services; finding illegal and well-regulated items 14 (ex., finding out an appropriate bribe for the local law)

Services of unusual skills; finding dangerous or carefully controlled items 18 (ex., seeking a fence or a safecracker)

A specific criminal in hiding; finding items whose possession means immediate imprisonment 28

*Size of City Modifier*

Large city (one million or more citizens) 0

Small city (several hundred thousand citizens) +5

Town (several thousand citizens) +10

Village (several hundred citizens) +15

Amount of Law Enforcement or Tolerance of Residents Modifier

Martial law or no tolerance for criminals or outsiders +15

Criminal activity overlooked as long as it’s discreet; slight tolerance of outsiders +10

Criminal activity overlooked as long as it’s not dangerous to the general public; tolerance of outsiders +5

Criminal activity overlooked as long as it’s not dangerous to the local government; outsiders welcome 0

Anarchy; outsiders given same respect as residents -10

*Reputation of Seeker Modifier*

Never been to the location; no contacts; not trusted by local underworld or residents +10 or more

Rarely visited; only passing knowledge of how the local underworld operates +1-9

Minor contacts; knows what to avoid; criminals or residents have no reason not to trust character 0

Somewhat favorably known by local underworld or residents; several contacts -1–9

Well-known and liked by underworld or residents +10 or more

=== Survival (Perception)

Character can rely on survival to figure what to eat, where to sleep, how best to deal with native dangers, and other information needed to get out of wilderness situation alive.
(Use streetwise for help in urban situations.)

*Situation Difficulty*

Woods 4

High mountains, ocean (near floor) 12

Desert, ocean (above) 15

Polar region 18

Different, non-Earth-like dimension or planet 25

Space 35

*Skill Situation Modifier*

Has been to this location frequently +1D

Has been to this location within the past 10 years 0

Has never been to this location -1D

=== Tech (Knowledge)

The base difficulty is 10.
The difficulty charts for computer and programming can give Game Masters an idea of how to make tables for other complex pieces of technology.
If using this skill to operate communication or sensor equipment, refer to the “Observation Difficulties” or “Information Difficulties” charts to determine how much information the character has learned.

*Complexity of Device Modifier*

Simple 0

Average +4

Complex +7

Prototype +10

From a culture with a lower technological level -5

From a culture with a much higher technological level +10

Consists of many integrated systems +5

Consists of hundreds of integrated systems +10

Has a manual for the device in a language the character can understand -3

*Roll > Difficulty Result*

0–2 Basic idea of what the device can do, but not how to operate it.

3–6 Basic idea of what the device can do and how to operate it; may add the result point bonus to using the device on the next round if the character does not have an appropriate skill to use the device.

7–11 Previous result and may add the result point bonus to a repair attempt on the device, if proper tools and materials are available.

12+ Previous two results and can design a similar device, if proper resources are available.

*Computer Use Situation Modifier*

Open-access personal computer or mainframe 0

Networked computer 0

Isolated computer +3

Accessible by a few people +3

Accessible by owner only +6

Password protected +3

Firewall protection +6

Files encrypted +3 or more

*Programming Situation Modifier*

Simple programming language 0

Complex programming language +3

Encrypting program +6

Number of tasks program designed to accomplish (per task) +3

Designed to work on multiple +6 operating systems (per additional system)

*Condition Modifier*

Character unfamiliar with the program’s language +3

Character experienced with the program’s language -3

=== Throwing (Coordination)

In addition to being useful for tossing items, the throwing skill enhances a character’s ability to grab projectiles out of the air.
The difficulty of catching an object is typically the thrower’s throwing or missile weapons roll.
If the thrower wants the catcher to get the object, and thus takes care to throw well, reduce the thrower’s skill total by 9.

Combat difficulties for this skill are included in the “Combat” chapter.

=== Tracking (Perception)

The base difficulty is 10 or the target’s sneak roll, if the target is actively trying to hide her trail.
Characters can also use tracking to shadow a target.
A shadowed character can attempt to spot the shadow with a search roll versus the shadowing character’s tracking roll.
Game Masters may opt to include relevant hide modifiers to the tracking roll, if the shadow is being cautious.

*Condition Modifier*

Trail is a day old +3

Trail is a few days old +6

Trail is a week old +9

Tracking during inclement weather +6

Soft dirt, mud, snow -3

Grassland 0

Forest, thin crowd +3

Rain forest, dense crowd +6

Desert, arctic wasteland, hard surface +9

Number of people being tracked (for every 2 people) -3

Tracking a wheeled vehicle -6

Per additional vehicle -3

=== Willpower (Presence)

Willpower is generally used to resist interaction attempts and mentally damaging attacks.
See the “Mental Defense” sidebar earlier in this chapter for details.
Characters with this skill may generally use it instead of stamina to resist fatigue, sleep, and unconsciousness, though there may be some situations the Game Master restricts its substitution.
See the stamina entry in this chapter for information on difficulties.

Game Master can also use willpower (or Presence) to determine the reactions of players’ and Game Master’s characters to each other and to their surroundings.
The more the Game Master believes that the character should be at ease or frightened, the greater the difficulty.
Use the descriptions of standard difficulties to determine the level.
This passive application of willpower is not an action.
